import assert from'node:assert/strict';import{test}from'node:test';import{generate,check,stageSeed}from'../lib/puzzles.ts';import{trialStep,trialGoal,SEGMENTS}from'../lib/engine/trial.ts';
test('traffic always requires moving another car and rises in measured difficulty',()=>{for(const L of[1,8,12,16,20])for(let seed=0;seed<40;seed++){const p=generate('traffic',L,seed);let s=p.data.initial;for(let i=0;i<10;i++){const next=trialStep(p,s,{car:0,delta:1});if(!next)break;s=next;}assert.equal(trialGoal(p,s),false,`${L}/${seed}`);assert.ok(check(p,p.solution));if(L===20)assert.ok(p.data.minimum>=23);}});
test('pancakes start with a meaningful mix of at least two flips',()=>{const forms=new Set();for(let seed=0;seed<80;seed++){const p=generate('pancake',1,seed);forms.add(JSON.stringify(p.data.initial));assert.ok(p.data.minimum>=2);}assert.ok(forms.size>8);});
test('advanced jug tasks vary capacities and river requires multiple decisions',()=>{const caps=new Set();for(let seed=0;seed<80;seed++){caps.add(JSON.stringify(generate('jugs',20,seed).data.caps));assert.ok(generate('river',20,seed).data.minimum>=6);}assert.ok(caps.size>20);});
test('key-door solutions must leave the direct route and revisit junctions',()=>{for(const L of[1,10,20])for(let seed=0;seed<30;seed++){const p=generate('keydoors',L,seed);let s=p.data.initial;const visited=new Set([s.pos]);let repeat=false;for(const action of p.solution){s=trialStep(p,s,action);repeat ||= visited.has(s.pos);visited.add(s.pos);}assert.ok(repeat,`${L}/${seed}`);assert.ok(check(p,p.solution));}});
test('advanced robots must both travel with real command depth',()=>{for(let seed=0;seed<40;seed++){const p=generate('programbot',20,seed);assert.notEqual(p.data.initial.pos,p.data.target.pos);assert.ok(p.solution.length>=8);const q=generate('twobots',20,seed);assert.ok(q.data.initial.positions.every((v,i)=>v!==q.data.target[i]));assert.ok(q.data.minimum>=10);}});
test('matchstick puzzles begin with readable false arithmetic',()=>{for(const L of[1,10,20])for(let seed=0;seed<40;seed++){const p=generate('matchsticks',L,seed);assert.ok(p.data.initial.masks.every(m=>SEGMENTS.includes(m)),`${L}/${seed}`);assert.equal(trialGoal(p,p.data.initial),false);assert.ok(check(p,p.solution));}});
test('trainyard cannot send every train directly to output',()=>{for(const L of[1,10,20])for(let seed=0;seed<40;seed++){const p=generate('trainyard',L,seed);assert.equal(check(p,p.data.initial.input.map(()=>({from:'in',to:'out'}))),false);}});

test('traffic stages never repeat a board within a difficulty band',()=>{for(let band=0;band<5;band++){const seen=new Set();for(let stage=band*16+1;stage<=band*16+16;stage++)for(let i=0;i<10;i++){const p=generate('traffic',Math.floor((stage-1)/4)+1,stageSeed('traffic',stage,i)),k=JSON.stringify([p.data.cars,p.data.initial]);assert.ok(!seen.has(k),`repeat ${stage}/${i}`);seen.add(k);}}});
test('matchstick move bands use the minimum to any correct equation',()=>{for(const L of[10,17,20])for(const seed of[94988815,...Array.from({length:40},(_,i)=>i)]){const p=generate('matchsticks',L,seed),d=p.data,[wa,wb,wc]=d.groups;let min=Infinity;const count=m=>m.toString(2).replaceAll('0','').length,total=d.initial.masks.reduce((s,m)=>s+count(m),0);for(let a=wa===1?0:10**(wa-1);a<10**wa;a++)for(let b=wb===1?0:10**(wb-1);b<10**wb;b++){const c=a+b;if(String(c).length!==wc)continue;const masks=[...String(a),...String(b),...String(c)].map(v=>SEGMENTS[Number(v)]);if(masks.reduce((s,m)=>s+count(m),0)!==total)continue;min=Math.min(min,masks.reduce((s,m,i)=>s+count(m^d.initial.masks[i]),0)/2);}assert.equal(min,d.maxMoves,`${L}/${seed}`);}});
test('trainyard stages provide distinct yards with increasing required rearrangement',()=>{for(let band=0;band<5;band++){const seen=new Set();for(let stage=band*16+1;stage<=band*16+16;stage++)for(let i=0;i<10;i++){const p=generate('trainyard',Math.floor((stage-1)/4)+1,stageSeed('trainyard',stage,i)),k=JSON.stringify(p.data.initial);assert.ok(!seen.has(k),`repeated train ${stage}/${i}`);seen.add(k);assert.ok(p.data.minimumExtraMoves>=[2,3,4,5,6][band]);assert.equal(p.data.initial.output.length,0);assert.ok(check(p,p.solution));}}});
test('flood levels require an increasing number of actual color decisions',()=>{for(const L of[1,5,10,15,20])for(let seed=0;seed<50;seed++){const p=generate('flood',L,seed);assert.ok(p.data.minimum>=2+Math.floor(L/4),`${L}/${seed}:${p.data.minimum}`);assert.ok(check(p,p.solution));}});
