import assert from'node:assert/strict';import{test}from'node:test';import{generate,check,norm}from'../lib/puzzles.ts';import{canExtract,rotateAxis,tilt}from'../lib/engine/space.ts';
const sig=c=>{const keys=[];for(let x=0;x<4;x++)for(let y=0;y<4;y++)for(let z=0;z<4;z++)keys.push(JSON.stringify(norm(rotateAxis(rotateAxis(rotateAxis(c,0,x),1,y),2,z))));return keys.sort()[0];};
test('3D rotation alternatives have same volume and only one congruent answer',()=>{for(const L of[1,5,20])for(let seed=0;seed<30;seed++){const p=generate('rotate3d',L,seed),key=sig(p.data.cubes);assert.equal(p.options.filter(v=>sig(v)===key).length,1,`${L}/${seed}`);assert.ok(p.options.every(v=>v.length===p.data.cubes.length));}});
test('extract pieces have actual blocking dependencies at every level',()=>{for(const L of[1,10,20])for(let seed=0;seed<40;seed++){const p=generate('extract3d',L,seed),blocked=p.data.pieces.filter((_,i)=>!canExtract(p.data.pieces,[],i)).length;assert.ok(blocked>=(L<7?1:2),`${L}/${seed}:${blocked}`);assert.ok(check(p,p.solution));}});
test('falling piece answers have no fixed total rank',()=>{const ranks=new Set();for(let seed=0;seed<80;seed++){const p=generate('drop3d',20,seed),sums=p.options.map(o=>o.values.reduce((a,b)=>a+b,0));ranks.add([...sums].sort((a,b)=>a-b).indexOf(sums[p.solution]));}assert.ok(ranks.size>=3);});
test('coordinates cannot always be read from per-column option modes',()=>{let wins=0;for(let seed=0;seed<80;seed++){const p=generate('voxelcoords',20,seed),opts=p.options.map(v=>v.split('・')),mode=[0,1,2].map(j=>{const counts=new Map();opts.forEach(o=>counts.set(o[j],(counts.get(o[j])||0)+1));return[...counts].sort((a,b)=>b[1]-a[1])[0][0];}).join('・');wins+=p.options[p.solution]===mode;}assert.ok(wins<55);});
test('all contact count options are physically possible counts',()=>{for(let seed=0;seed<60;seed++){const p=generate('contact3d',20,seed);assert.ok(p.options.every(v=>v>=0&&v<=6));}});
test('tunnel choices are orientations of the same object',()=>{for(let seed=0;seed<30;seed++){const p=generate('tunnelpass',1,seed),key=sig(p.options[p.solution].cells);assert.ok(p.options.every(o=>sig(o.cells)===key));}});
test('gravity alternatives all respect the last tilt',()=>{for(let seed=0;seed<30;seed++){const p=generate('gravitytray',20,seed),d=p.data;for(const o of p.options){const a=o.values.map((v,i)=>v==='●'?i:-1).filter(i=>i>=0);assert.deepEqual(tilt(a,d.n,d.walls,d.moves.at(-1)),a);}}});
