import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const source=resolve(new URL('..',import.meta.url).pathname);
const moduleAt=path=>import(pathToFileURL(resolve(source,path)).href);
const {generate,check}=await moduleAt('lib/puzzles.ts');
const {logicQuestionBody,logicMetrics,LOGIC_GOALS}=await moduleAt('lib/engine/logic-profiles.ts');
const R=n=>Array.from({length:n},(_,i)=>i),permutations=a=>a.length?a.flatMap((v,i)=>permutations(a.filter((_,j)=>j!==i)).map(p=>[v,...p])):[[]],body=p=>JSON.stringify(logicQuestionBody(p));
import {test} from 'node:test';
const summary=[];
function orderRule(a,r){const pos=new Map(a.map((v,i)=>[v,i])),x=pos.get(r.a),y=pos.get(r.b),z=pos.get(r.c);switch(r.op){case'before':return x<y;case'adjacent':return Math.abs(x-y)===1;case'notAdjacent':return Math.abs(x-y)>1;case'gap':return Math.abs(x-y)===r.gap;case'position':return x===r.position;case'end':return x===0||x===a.length-1;case'between':return Math.min(x,z)<y&&y<Math.max(x,z);default:throw Error(r.op);}}
function chosen(p){return p.options[p.solution];}
test('24 games expose five goals and finite structural metrics',()=>{assert.equal(Object.keys(LOGIC_GOALS).length,24);for(const [id,goals]of Object.entries(LOGIC_GOALS)){assert.equal(goals.length,5);for(const level of [1,5,9,13,17,20]){const p=generate(id,level,4107);assert.ok(Number.isFinite(logicMetrics(p).score));assert.ok(logicQuestionBody(p));assert.ok(check(p,p.solution),id);}}});
test('revised original six dispatch through their actual interaction checkers',()=>{for(const id of ['pattern','matrix','sudoku','order','balance','odd'])for(const L of [2,6,10,14,18,20]){const p=generate(id,L,2027);assert.ok(check(p,p.solution),`${id} valid witness`);const wrong=p.kind==='visual-choice'?(p.solution+1)%p.options.length:p.kind==='arrange'?Array(p.solution.length).fill(0):p.kind==='card-select'?[]:p.solution.map(()=>0);assert.ok(!check(p,wrong),`${id} wrong answer must fail`);}});
test('order clauses have one independently enumerated satisfying permutation',()=>{for(let L=1;L<=20;L++)for(let seed=0;seed<12;seed++){const p=generate('order',L,seed),valid=permutations(R(p.data.values.length)).filter(a=>p.data.orderRules.every(r=>orderRule(a,r)));assert.equal(valid.length,1);assert.deepEqual(valid[0],p.solution);assert.ok(check(p,valid[0]));}});
test('matrix forward and inverse blanks satisfy the displayed calculation schema',()=>{for(let L=1;L<=20;L++)for(let seed=0;seed<12;seed++){const p=generate('matrix',L,seed),d=p.data,a=chosen(p);if(d.ruleFamily==='additive-cross')assert.equal(a,d.values[1]+d.values[2]-d.values[0]);else {const grid=d.values.map(v=>v==='？'?a:v);for(let r=0;r<3;r++){const[x,y,z]=grid.slice(r*3,r*3+3),expected=d.ruleFamily==='add'?x+y:d.ruleFamily==='subtract'?x-y:d.ruleFamily==='multiply'?x*y:d.ruleFamily==='multiply-plus'?x*d.coefficient+y:x*y+d.offset;assert.equal(z,expected);}}}});
test('cipher follows every key in the displayed forward or reverse order',()=>{for(let L=1;L<=20;L++)for(let seed=0;seed<12;seed++){const p=generate('cipher',L,seed),d=p.data,keys=d.reverse?[...d.maps].reverse():d.maps,expected=d.message.map(v=>{for(const key of keys)v=d.reverse?key.findIndex(w=>w===v):key[v];return v+1;}).join(' ');assert.equal(chosen(p),expected);assert.ok(check(p,p.solution));}});
test('family queries use parent hops, ancestor intersection or shortest path',()=>{for(let L=1;L<=20;L++)for(let seed=0;seed<12;seed++){const p=generate('familytree',L,seed),d=p.data;let expected;if(d.relation==='path-distance'){const q=[[d.target,0]],seen=new Set([d.target]);for(const[v,dist]of q){if(v===d.otherTarget){expected=String(dist);break;}const near=[d.parents[v],...R(d.parents.length).filter(i=>d.parents[i]===v)].filter(i=>i>=0);for(const at of near)if(!seen.has(at)){seen.add(at);q.push([at,dist+1]);}}}else if(d.relation==='common-ancestor'){const ancestors=new Set();for(let at=d.target;at>=0;at=d.parents[at])ancestors.add(at);let at=d.otherTarget;while(!ancestors.has(at))at=d.parents[at];expected=d.scene.labels[at];}else {let at=d.target;for(let i=0;i<d.steps;i++)at=d.parents[at];expected=d.scene.labels[at];}assert.equal(chosen(p),expected);}});
test('fingerprints ignore annotation, option order, clue order and symmetric relation wording',()=>{for(const id of Object.keys(LOGIC_GOALS))for(const L of [1,5,9,13,17,20]){const p=generate(id,L,1943),q=structuredClone(p);q.seed++;q.level=99;q.hint='cosmetic';if(q.options)q.options.reverse();if(q.data.clues&&Array.isArray(q.data.clues)&&Array.isArray(q.data.clues[0]))q.data.clues.reverse();if(q.data.orderRules)for(const r of q.data.orderRules){if(['adjacent','notAdjacent','gap'].includes(r.op))[r.a,r.b]=[r.b,r.a];if(r.op==='between')[r.a,r.c]=[r.c,r.a];}assert.equal(body(q),body(p),id);}});
test('fixed-question logic tasks cannot create more stages by changing their distractors',()=>{for(const id of ['pattern','matrix','balance','rulemachine','familytree','cipher'])for(const L of [1,5,9,13,17]){const p=generate(id,L,1943),q=structuredClone(p);q.options=[];assert.equal(body(q),body(p),id);}});
test('repaired finite themes each provide at least ten fresh semantic tasks',()=>{for(const id of ['schedule','familytree','liar','loopclues','circuit','rulemachine']){const prior=new Set(),counts=[];for(let theme=0;theme<5;theme++){const seen=new Set();for(let step=1;step<=4;step++)for(let seed=0;seed<100;seed++){const p=generate(id,4*theme+step,seed);assert.ok(check(p,p.solution),id);const key=body(p);if(!prior.has(key))seen.add(key);}assert.ok(seen.size>=10,`${id} theme ${theme+1}: ${seen.size}`);counts.push(seen.size);for(const key of [...seen].sort().slice(0,10))prior.add(key);}summary.push({id,availableFreshBodies:counts});}});
