import {generateLogicCurriculum,orderRuleHolds,assignmentRuleHolds} from './logic-curriculum.ts';
import{islandSolutions}from'./islands-solver.mjs';
import{BINARY_CODES}from'./binary-boards.ts';
import {context,range,equal,key,adjacent,sceneText,sceneRow,sceneGrid,type Puzzle,type Meta} from './shared.ts';
export const LOGIC_META:Meta[]=[
 ['nonogram','ぬって はっけん','logic','すうじの とおりに ぬろう','外の数字は続けて塗るマスの数。二つの数字の間は1マス以上空けます。タップで色、長押しの代わりに×ボタンで空白の印を付けられます。'],
 ['liar','ほんとの はなし','logic','ヒントに あうのは だれ？','本当の話の数が決まっています。全員の話を比べ、条件に合う相手を選びます。'],
 ['zebra','だれの カード？','logic','ひとりに ひとつずつ わたそう','各行の候補から一つ選びます。同じカードは二人には渡せません。'],
 ['venn','なかまを あつめて','logic','じょうけんに あうものを ぜんぶ','「かつ」は両方、「または」は片方以上です。条件を満たすカードを全部選びます。'],
 ['minestars','ほしの かくれんぼ','logic','かくれた ほしを みつけよう','数字は斜めを含む周囲8マスの星の数です。星のあるマスを全部塗ります。'],
 ['bridges','はしを かけよう','logic','すうじの ほんすうで つなごう','丸の数字と同じ本数の橋をつなぎます。橋は0・1・2本と変わり、全部の丸を一つにつなぎます。'],
 ['loopclues','ぐるっと ひとまわり','logic','ひとつの わっかを つくろう','数字はそのマスの周りの線の数。枝分かれせず、一つだけの輪を作ります。'],
 ['islands','しまを つくろう','logic','すうじの ひろさの しまに','色を塗って海を作ります。白い島には数字が一つ、広さはその数字。海は全部つながり、海の2×2は作りません。'],
 ['tents','きの となりに','logic','き ひとつに テント ひとつ','木の上下左右に一つずつテント。テント同士は斜めにも触れません。縦横の数も合わせます。'],
 ['binary','しろと くろ','logic','ふたつを はんぶんずつ','各行・列に○（白）と●（黒）を同数入れます。同じ印を三つ続けず、同じ並びの行・列も作りません。'],
 ['circuit','ひかりの かいろ','logic','スイッチで ライトを つけよう','指定の個数だけスイッチを入れます。ANDは両方、ORは片方以上、XORは片方だけのとき光が通ります。'],
 ['rulemachine','まほうの はこ','logic','はこを とおると どうなる？','例と同じ規則で形が変わります。形・色・数の変化をそれぞれ見つけましょう。'],
 ['schedule','じゅんばん ミッション','logic','やくそくを まもって ならべよう','矢印の左が先、右が後です。間が空いても大丈夫。全ての約束を守る並びを作ります。'],
 ['domino','つながる ドミノ','logic','おなじ かずで つなげよう','同じ数の端同士をつなぎ、全カードを使います。カードの回転ボタンで左右を入れ替えられます。'],
 ['familytree','つながりの き','logic','つながりを たどると だれ？','線は親子のつながりで、上の人が親です。指定した人の先祖、二人の共通の先祖、二人をつなぐ線の本数を、問題の指示に合わせて調べます。'],
 ['settriple','ぴったり 3まい','logic','みっつの きまりで 3まい','形・色・個数のそれぞれが「全部同じ」か「全部違う」になる3枚を選びます。'],
 ['mintree','みじかく つなごう','logic','ぜんぶを いちばん みじかく','道の数字は長さです。全ての丸をつなぐ道を選び、合計をいちばん小さくします。'],
 ['cipher','ひみつの ことば','logic','カギを つかって よみとこう','対応表の矢印に沿って記号を読み替えます。表は一つから三つ。指定の順に使い、逆向きの問題では最後の表から戻します。'],
];
export function runs(a:number[]){const out:number[]=[];let n=0;for(const v of [...a,0]){if(v)n++;else if(n){out.push(n);n=0;}}return out.length?out:[0];}
export function lineClues(bits:number[],n:number){return {rows:range(n).map(y=>runs(bits.slice(y*n,(y+1)*n))),cols:range(n).map(x=>runs(range(n).map(y=>bits[y*n+x])))};}
export function nonogramSolutions(rows:number[][],cols:number[][],given:number[],limit=2){const n=rows.length,patterns=range(2**n).map(v=>range(n).map(i=>(v>>i)&1)),rowOptions=rows.map((clue,y)=>patterns.filter(a=>equal(runs(a),clue)&&a.every((v,x)=>given[y*n+x]<0||given[y*n+x]===v))),colOptions=cols.map(clue=>patterns.filter(a=>equal(runs(a),clue))),stack:number[][]=[],solutions:number[][]=[];function go(y:number){if(solutions.length>=limit)return;if(y===n){solutions.push(stack.flat());return;}for(const row of rowOptions[y]){stack.push(row);if(range(n).every(x=>colOptions[x].some(col=>range(y+1).every(i=>col[i]===stack[i][x]))))go(y+1);stack.pop();}}go(0);return solutions;}
export function components(bits:number[],n:number,value:number){const seen=new Set<number>(),out:number[][]=[];for(let i=0;i<bits.length;i++)if(bits[i]===value&&!seen.has(i)){const q=[i];seen.add(i);for(let j=0;j<q.length;j++)for(const k of adjacent(q[j],n))if(bits[k]===value&&!seen.has(k)){seen.add(k);q.push(k);}out.push(q);}return out;}
const neighbors8=(i:number,n:number)=>range(n*n).filter(j=>j!==i&&Math.abs(j%n-i%n)<=1&&Math.abs(Math.floor(j/n)-Math.floor(i/n))<=1);
const permutation=(a:number[]):number[][]=>a.length?a.flatMap((v,i)=>permutation(a.filter((_,j)=>j!==i)).map(p=>[v,...p])):[[]];
export function validBinary(a:number[],n:number){if(a.length!==n*n||a.some(v=>v!==0&&v!==1))return false;const rows=range(n).map(y=>a.slice(y*n,(y+1)*n)),cols=range(n).map(x=>range(n).map(y=>a[y*n+x]));return [rows,cols].every(lines=>new Set(lines.map(key)).size===n&&lines.every(line=>line.reduce((a,b)=>a+b,0)===n/2&&!line.some((v,i)=>i>1&&v===line[i-1]&&v===line[i-2])));}
export function circuitValue(tree:any,bits:number[]):number{if(typeof tree==='number')return bits[tree]||0;const a=circuitValue(tree.left,bits),b=circuitValue(tree.right,bits);return tree.op==='AND'?a&b:tree.op==='OR'?a|b:a^b;}
export function isSet(cards:any[]){return cards.length===3&&['shape','color','count'].every(k=>[1,3].includes(new Set(cards.map(c=>c[k])).size));}
export function cardRule(card:any,rule:any):boolean{if(rule.op==='not')return !cardRule(card,rule.child);if(rule.op==='and')return cardRule(card,rule.left)&&cardRule(card,rule.right);if(rule.op==='or')return cardRule(card,rule.left)||cardRule(card,rule.right);return card[rule.attr]===rule.value;}
export function connectedEdges(count:number,edges:number[][],values:number[]){const seen=new Set([0]),q=[0];for(let i=0;i<q.length;i++)edges.forEach(([a,b],j)=>{if(!values[j])return;const v=a===q[i]?b:b===q[i]?a:-1;if(v>=0&&!seen.has(v)){seen.add(v);q.push(v);}});return seen.size===count;}
export function mstWeight(count:number,edges:number[][],weights:number[]){const parent=range(count),root=(i:number):number=>parent[i]===i?i:(parent[i]=root(parent[i]));let sum=0;for(const i of range(edges.length).sort((a,b)=>weights[a]-weights[b])){const[a,b]=edges[i],x=root(a),y=root(b);if(x!==y){parent[x]=y;sum+=weights[i];}}return sum;}
function blankBits(n:number){return Array(n*n).fill(0);}
export function generateLogic(id:string,level:number,seed:number):Puzzle|undefined{return generateLogicCurriculum(id,level,seed,generateLogicBase);}
export function generateLogicBase(id:string,level:number,seed:number):Puzzle|undefined{
 if(!LOGIC_META.some(m=>m[0]===id))return;const c=context(id,level,seed),{L,int,pick,shuffle,base,choice,numeric}=c;
 if(id==='nonogram'){const n=L<5?3:L<9?4:L<15?5:6,solution=range(n*n).map(()=>int(0,1));if(solution.every(v=>v===0))(solution as number[])[int(0,n*n-1)]=1;if(solution.every(v=>v===1))(solution as number[])[int(0,n*n-1)]=0;const clues=lineClues(solution,n),given=Array(n*n).fill(-1);for(let k=0;k<n*n;k++){const sols=nonogramSolutions(clues.rows,clues.cols,given);if(sols.length===1)break;const other=sols.find(s=>!equal(s,solution))!,diff=shuffle(range(n*n).filter(i=>other[i]!==solution[i]));given[diff[0]]=solution[diff[0]];}return base('binary-grid',{n,...clues,given,initial:given.map(v=>v<0?0:v),scene:sceneText('つづく マスを ぬろう')},solution,'すべて ぬれる れつや、おおきい すうじから かんがえよう。');}
 if(id==='liar'){const n=L<7?3:L<14?4:5,people=range(n).map(i=>String.fromCharCode(65+i));let statements:any[]=[],target=0,trueCount=0;for(let trial=0;trial<100;trial++){statements=range(n+Math.floor(L/7)).map(()=>({person:int(0,n-1),is:int(0,1)===1}));const counts=range(n).map(v=>statements.filter(s=>(v===s.person)===s.is).length),single=range(n).filter(v=>counts.filter(x=>x===counts[v]).length===1);if(single.length){target=pick(single);trueCount=counts[target];break;}if(trial===99){target=n-1;statements=range(n-1).map(person=>({person,is:true}));trueCount=0;}}return choice(people[target],people.filter((_,i)=>i!==target),{type:'statements',people,statements,trueCount},`ほんとうの はなしが ${trueCount}こに なる ひとを さがそう。`,{people,statements,trueCount});}
 if(id==='zebra'){const n=L<7?3:L<14?4:5,solution=shuffle(range(n)),allowed=range(n).map(i=>range(n).filter(v=>v===solution[i]||int(0,2)===0)),perms=permutation(range(n));for(let k=0;k<n*n;k++){const alternatives=perms.filter(p=>p.every((v,i)=>allowed[i].includes(v)));if(alternatives.length===1)break;const other=alternatives.find(a=>!equal(a,solution))!,row=pick(range(n).filter(i=>other[i]!==solution[i]));allowed[row]=allowed[row].filter(v=>v!==other[row]);}return base('assignment',{n,allowed,initial:range(n).map(()=>-1),scene:{type:'assignment',allowed}},solution,'えらべる カードが ひとつの ひとを さきに きめよう。');}
 if(id==='venn'){
  const attrs=shuffle(['shape','color','count']),left={attr:attrs[0],value:attrs[0]==='count'?int(1,3):int(0,2)},right={attr:attrs[1],value:attrs[1]==='count'?int(1,3):int(0,2)},rule=L<5?left:L<12?{op:'and',left,right}:{op:pick(['and','or']),left:{op:'not',child:left},right},deck=range(27).map(i=>({type:'symbol',shape:i%3,color:Math.floor(i/3)%3,count:Math.floor(i/9)+1})),yes=shuffle(deck.filter(v=>cardRule(v,rule))),no=shuffle(deck.filter(v=>!cardRule(v,rule))),count=L<6?6:L<14?9:12,chosenYes=yes.slice(0,int(1,Math.min(yes.length,count-2))),cards=shuffle([...chosenYes,...no.slice(0,count-chosenYes.length)]),solution=range(cards.length).filter(i=>cardRule(cards[i],rule));
  return base('card-select',{cards,rule,scene:{type:'rule',rule}},solution,'「かつ」は どちらも。「または」は ひとつでも あてはまれば いいよ。');
 }
 if(id==='minestars'){const n=L<7?3:L<14?4:5,solution=blankBits(n),mines=shuffle(range(n*n)).slice(0,Math.min(6,1+Math.floor(L/4)));mines.forEach(i=>solution[i]=1);let unknown=[...new Set([...mines,...shuffle(range(n*n).filter(i=>!solution[i])).slice(0,Math.min(6,2+Math.floor(L/4)))])],given=range(n*n).map(i=>unknown.includes(i)?-1:solution[i]);const counts=range(n*n).map(i=>neighbors8(i,n).reduce((s,j)=>s+solution[j],0));function alternatives(){const out:number[][]=[];for(let mask=0;mask<2**unknown.length;mask++){const a=[...solution];unknown.forEach((at,j)=>a[at]=(mask>>j)&1);if(range(n*n).filter(i=>given[i]===0).every(i=>neighbors8(i,n).reduce((s,j)=>s+a[j],0)===counts[i])){out.push(a);if(out.length>=2)break;}}return out;}for(let k=0;k<n*n;k++){const sols=alternatives();if(sols.length===1)break;const other=sols.find(a=>!equal(a,solution))!,at=pick(unknown.filter(i=>other[i]!==solution[i]));given[at]=solution[at];unknown=unknown.filter(i=>i!==at);}if(mines.every(i=>given[i]===1)){const at=mines.find(i=>neighbors8(i,n).some(j=>given[j]===0));if(at!==undefined)given[at]=-1;}return base('binary-grid',{n,given,counts,initial:given.map(v=>v<0?0:v)},solution,'すうじの まわりの 8ますを みよう。0の となりに ほしは ないよ。');}
 if(id==='bridges'){const n=L<10?2:3,nodes=range(n*n).map(i=>[i%n,Math.floor(i/n)]),edges:number[][]=[];range(n*n).forEach(i=>{if(i%n<n-1)edges.push([i,i+1]);if(i<n*(n-1))edges.push([i,i+n]);});const solution=edges.map(()=>0),seen=new Set([0]);while(seen.size<n*n){const es=shuffle(range(edges.length).filter(i=>seen.has(edges[i][0])!==seen.has(edges[i][1]))),e=es[0];solution[e]=int(1,2);edges[e].forEach(v=>seen.add(v));}range(edges.length).forEach(i=>{if(!solution[i]&&int(0,3)===0)solution[i]=1;});const degrees=range(nodes.length).map(v=>edges.reduce((s,e,i)=>s+(e.includes(v)?solution[i]:0),0));return base('edge-grid',{n,nodes,edges,degrees,max:2,initial:edges.map(()=>0)},solution,'おおきな すうじの しまから、ひつような はしを かぞえよう。');}
 if(id==='loopclues'){const n=L<3?2:L<7?3:L<15?4:5,nodes=range((n+1)**2).map(i=>[i%(n+1),Math.floor(i/(n+1))]),edges:number[][]=[];range(nodes.length).forEach(i=>{if(i%(n+1)<n)edges.push([i,i+1]);if(i<n*(n+1))edges.push([i,i+n+1]);});const shape=[int(0,n*n-1)],target=int(Math.max(1,Math.floor(n*n*.3)),Math.max(2,Math.floor(n*n*.75)));for(let tries=0;shape.length<target&&tries<300;tries++){const options=shuffle(range(n*n).filter(i=>!shape.includes(i)&&adjacent(i,n).some(j=>shape.includes(j))));let added=false;for(const at of options){const trial=[...shape,at],bits=range(n*n).map(i=>trial.includes(i)?1:0);if(components(bits,n,0).length<=1&&!range((n-1)**2).some(i=>{const x=i%(n-1),y=Math.floor(i/(n-1)),v=[bits[y*n+x],bits[y*n+x+1],bits[(y+1)*n+x],bits[(y+1)*n+x+1]];return equal(v,[1,0,0,1])||equal(v,[0,1,1,0]);})){shape.push(at);added=true;break;}}if(!added)break;}const inside=range(n*n).map(i=>shape.includes(i)?1:0),solution=edges.map(([a,b])=>{const[x,y]=nodes[a],[xx,yy]=nodes[b];if(y===yy)return ((y>0?inside[(y-1)*n+x]:0)^(y<n?inside[y*n+x]:0));return ((x>0?inside[y*n+x-1]:0)^(x<n?inside[y*n+x]:0));}),cellEdges=range(n*n).map(i=>{const x=i%n,y=Math.floor(i/n),v=y*(n+1)+x,vs=[v,v+1,v+n+1,v+n+2];return range(edges.length).filter(j=>edges[j].every(v=>vs.includes(v)));}),clues=cellEdges.map(es=>es.reduce((s,i)=>s+solution[i],0));return base('edge-grid',{n,nodes,edges,clues,cellEdges,max:1,initial:edges.map(()=>0)},solution,'0の まわりに せんは ないよ。3の まわりは ひとつだけ あくよ。');}
 if(id==='islands'){
  const n=L<5?3:L<11?4:5;let solution:number[]=[],clues:Record<number,number>={};
  for(let attempt=0;attempt<10000;attempt++){
   const candidate=range(n*n).map(()=>int(0,99)<55?1:0),land=components(candidate,n,0);
   if(land.every(island=>island.length===1)||land.length<2||land.length>Math.ceil(n*n/2)||land.some(a=>a.length>2+Math.floor((L-1)/4))||components(candidate,n,1).length!==1)continue;
   if(range(n*n).some(i=>i%n<n-1&&i<n*(n-1)&&[i,i+1,i+n,i+n+1].every(j=>candidate[j])))continue;
   const proposed:Record<number,number>={};for(const island of land)proposed[pick(island)]=island.length;const result=islandSolutions(n,proposed);if(result.aborted||result.count!==1)continue;solution=candidate;clues=proposed;break;
  }if(!solution.length)throw Error('island generation failed');
  const given=range(n*n).map(i=>clues[i]?0:-1);
  return base('binary-grid',{n,clues,given,initial:blankBits(n)},solution,'すうじ 1の しまは その マスだけ。しまの あいだを うみで わけよう。');
 }
 if(id==='tents'){const n=L<5?4:L<11?5:6,trees:number[]=[],tents:number[]=[];for(const at of shuffle(range(n*n))){if(tents.length>=2+Math.floor((L-1)/3))break;if(trees.includes(at)||tents.some(t=>neighbors8(t,n).includes(at)))continue;const places=shuffle(adjacent(at,n).filter(i=>!trees.includes(i)&&!tents.includes(i)));if(!places.length)continue;tents.push(at);trees.push(places[0]);}const solution=range(n*n).map(i=>tents.includes(i)?1:0),rows=range(n).map(y=>solution.slice(y*n,(y+1)*n).reduce<number>((a,b)=>a+b,0)),cols=range(n).map(x=>range(n).reduce((s,y)=>s+solution[y*n+x],0));return base('binary-grid',{n,trees,rows,cols,given:range(n*n).map(i=>trees.includes(i)?0:-1),initial:blankBits(n)},solution,'0の れつには テントを おけないよ。きと テントを ひとつずつ ペアに。');}
 if(id==='binary'){
  const n=L<7?4:6,code=pick(BINARY_CODES[n]),solution=range(n*n).map(i=>Math.floor(code/2**i)%2),given=[...solution];let maskLo=n===4?65535:-1,maskHi=n===4?0:15,removed=0;
  for(const at of shuffle(range(n*n))){
   if(removed>=Math.min(n*n-4,(n===4?2:5)+L))break;const lo=at<32?maskLo&~(1<<at):maskLo,hi=at>=32?maskHi&~(1<<(at-32)):maskHi;
   let count=0;for(const candidate of BINARY_CODES[n])if(((candidate>>>0)&lo)===((code>>>0)&lo)&&((Math.floor(candidate/2**32))&hi)===((Math.floor(code/2**32))&hi)){count++;if(count===2)break;}
   if(count===1){given[at]=-1;maskLo=lo;maskHi=hi;removed++;}
  }return base('binary-grid',{n,given,initial:[...given]},solution,'おなじ しるしが ふたつ ならんだら、となりは ちがう しるしだよ。');
 }
 if(id==='circuit'){
  const n=L<3?3:L<9?4:L<15?5:6;
  for(let attempt=0;attempt<100;attempt++){
   function make(indices:number[]):any{if(indices.length===1)return indices[0];const k=int(1,indices.length-1);return{op:pick(L<5?['AND','OR']:['AND','OR','XOR']),left:make(indices.slice(0,k)),right:make(indices.slice(k))};}
   const tree=make(shuffle(range(n))),all=range(2**n).map(mask=>range(n).map(i=>(mask>>i)&1)),counts=shuffle(range(n-1).map(i=>i+1));
   for(const required of counts){const candidates=all.filter(a=>a.reduce((s,v)=>s+v,0)===required),valid=candidates.filter(a=>circuitValue(tree,a)===1);if(!valid.length||valid.length===candidates.length||L>10&&valid.length/candidates.length>.65)continue;
    return base('switches',{n,tree,required,initial:range(n).map(()=>0),scene:{type:'circuit',tree,n}},pick(valid),`スイッチは ${required}こ。はこの きまりを でぐちから たどろう。`);
   }
  }throw Error('circuit generation failed');
 }
 if(id==='rulemachine'){const shift={shape:L<5?int(1,2):int(0,2),color:L<5?0:int(0,2),count:L<10?0:int(1,2)},transform=(s:any)=>({type:'symbol',shape:(s.shape+shift.shape)%3,color:(s.color+shift.color)%3,count:(s.count-1+shift.count)%3+1}),inputs=range(3).map(i=>({type:'symbol',shape:i,color:i,count:i+1})),target={type:'symbol',shape:int(0,2),color:int(0,2),count:int(1,3)},answer=transform(target),wrong=shuffle(range(27).map(i=>({type:'symbol',shape:i%3,color:Math.floor(i/3)%3,count:Math.floor(i/9)+1})).filter(v=>!equal(v,answer))).slice(0,3);return choice(answer,wrong,{type:'machine',examples:inputs.map(v=>[v,transform(v)]),target},'かたち・いろ・かずが、じゅんばんに ひとつずつ まわっているよ。',{shift,target});}
 if(id==='schedule'){const n=L<6?3:L<14?5:6,solution=shuffle(range(n)),clues=solution.slice(0,-1).map((a,i)=>[a,solution[i+1]]);if(L>=10){clues.splice(int(0,clues.length-1),1);for(let k=0;k<Math.floor(L/5);k++){const a=int(0,n-2),b=int(a+1,n-1);if(!clues.some(p=>equal(p,[solution[a],solution[b]])))clues.push([solution[a],solution[b]]);}}const displayed=shuffle(clues);return base('arrange',{values:range(n).map(i=>String.fromCharCode(65+i)),clues:displayed,scene:{type:'precedence',clues:displayed,n}},solution,'まだ まえに だれも いない カードから ならべよう。');}
 if(id==='domino'){const n=L<5?3:L<9?4:L<13?5:L<17?7:8,chain=range(n+1).map(()=>int(0,L<7?3:6)),raw=range(n).map(i=>({pair:[chain[i],chain[i+1]],original:i,flip:int(0,1)===1})),shuffled=shuffle(raw),tiles=shuffled.map(v=>v.flip?[...v.pair].reverse():v.pair),solution={order:range(n).map(i=>shuffled.findIndex(v=>v.original===i)),flips:range(n).map(i=>shuffled.find(v=>v.original===i)!.flip)};return base('domino-chain',{tiles,start:chain[0],end:chain[n],initial:{order:[],flips:[]},scene:sceneText(`${chain[0]} → ${chain[n]}`,'ぜんぶの ドミノを つかおう')},solution,'つぎに つながる すうじを さがそう。カードは まわせるよ。');}
 if(id==='familytree'){
  const depth=L<6?2:L<14?3:4,parents=[-1],depths=[0];let row=[0];
  for(let y=1;y<=depth;y++){const next:number[]=[];for(const parent of row){const children=next.length+2+(row.length-row.indexOf(parent)-1)<=7?int(1,2):1;for(let k=0;k<children;k++){next.push(parents.length);parents.push(parent);depths.push(y);}}row=next;}
  const steps=int(1,L<6?1:L<14?2:3),target=pick(range(parents.length).filter(i=>depths[i]>=steps));let answer=target;for(let i=0;i<steps;i++)answer=parents[answer];const labels=parents.map((_,i)=>String(i+1)),others=shuffle(range(parents.length).filter(i=>i!==answer)).slice(0,3).map(i=>labels[i]);
  return choice(labels[answer],others,{type:'family',parents,target,steps,labels},`「おや」を ${steps}かい。せんを うえへ たどるよ。`,{parents,target,steps});
 }
 if(id==='settriple'){const colors=L<5?2:3,deck=range(3*colors*3).map(i=>({type:'symbol',shape:i%3,color:Math.floor(i/3)%colors,count:Math.floor(i/(3*colors))+1})),cards=shuffle(deck).slice(0,9);let solution:number[]=[];for(let a=0;a<cards.length;a++)for(let b=a+1;b<cards.length;b++)for(let d=b+1;d<cards.length;d++)if(isSet([cards[a],cards[b],cards[d]])&&!solution.length)solution=[a,b,d];if(!solution.length){cards.splice(0,3,...range(3).map(i=>({type:'symbol',shape:i,color:0,count:1})));solution=[0,1,2];}return base('card-select',{cards,scene:sceneText('おなじ？ ぜんぶ ちがう？','かたち・いろ・かず を べつべつに')},solution,'ふたつ おなじで ひとつだけ ちがう、は ダメだよ。');}
 if(id==='mintree'){const n=L<7?4:L<14?5:6,nodes=range(n).map(i=>[Math.cos(-Math.PI/2+i*2*Math.PI/n)*2+2,Math.sin(-Math.PI/2+i*2*Math.PI/n)*2+2]),edges=range(n).map(i=>[i,(i+1)%n]);for(let i=2;i<n-1;i++)edges.push([0,i]);const weights=edges.map(()=>int(1,L<7?5:12)),parent=range(n),root=(i:number):number=>parent[i]===i?i:(parent[i]=root(parent[i])),solution=edges.map(()=>0);for(const i of range(edges.length).sort((a,b)=>weights[a]-weights[b])){const[a,b]=edges[i],x=root(a),y=root(b);if(x!==y){parent[x]=y;solution[i]=1;}}return base('edge-grid',{n,nodes,edges,weights,minimum:mstWeight(n,edges,weights),max:1,initial:edges.map(()=>0)},solution,'みじかい みちから えらぼう。すでに つながっている ところの わっかは いらないよ。');}
 if(id==='cipher'){const n=L<7?3:6,map=shuffle(range(n)),map2=L<13?null:shuffle(range(n)),message=range(L<7?2:L<14?3:4).map(()=>int(0,n-1)),answer=message.map(i=>map2?map2[map[i]]+1:map[i]+1).join(' '),wrong=shuffle(permutation(range(n)).map(mapping=>message.map(i=>mapping[i]+1).join(' ')).filter(v=>v!==answer)).slice(0,12);return choice(answer,wrong,{type:'cipher',map,map2,message},map2?'さいしょの カギで かえてから、つぎの カギで もういちど。':'おなじ しるしは おなじ すうじに かわるよ。',{map,map2,message});}
}
export function checkLogic(p:Puzzle,a:any):boolean{
 if(a===null||a===undefined)return false;const d=p.data,id=p.id;
 if(p.kind==='binary-grid'){
  if(!Array.isArray(a)||a.length!==d.n*d.n||a.some(v=>v!==0&&v!==1)||d.given.some((v:number,i:number)=>v>=0&&a[i]!==v))return false;const n=d.n;
  if(id==='nonogram'){const c=lineClues(a,n);return equal(c.rows,d.rows)&&equal(c.cols,d.cols);}
  if(id==='minestars')return range(n*n).filter(i=>d.given[i]===0).every(i=>neighbors8(i,n).reduce((s,j)=>s+a[j],0)===d.counts[i]);
  if(id==='binary')return validBinary(a,n);
  if(id==='islands'){if(components(a,n,1).length!==1)return false;for(let y=0;y<n-1;y++)for(let x=0;x<n-1;x++)if([y*n+x,y*n+x+1,(y+1)*n+x,(y+1)*n+x+1].every(i=>a[i]))return false;return components(a,n,0).every(g=>{const clues=g.filter(i=>d.clues[i]);return clues.length===1&&d.clues[clues[0]]===g.length;});}
  if(id==='tents'){const tents=range(n*n).filter(i=>a[i]);if(tents.length!==d.trees.length||tents.some(i=>neighbors8(i,n).some(j=>a[j])))return false;if(!range(n).every(y=>a.slice(y*n,(y+1)*n).reduce((s:number,v:number)=>s+v,0)===d.rows[y]&&range(n).reduce((s,x)=>s+a[x*n+y],0)===d.cols[y]))return false;function match(i:number,used:Set<number>):boolean{if(i===d.trees.length)return true;for(const t of tents)if(!used.has(t)&&adjacent(d.trees[i],n).includes(t)){used.add(t);if(match(i+1,used))return true;used.delete(t);}return false;}return match(0,new Set());}
 }
 if(p.kind==='edge-grid'){
  if(!Array.isArray(a)||a.length!==d.edges.length||a.some(v=>!Number.isInteger(v)||v<0||v>d.max))return false;
  if(id==='bridges')return d.degrees.every((v:number,node:number)=>d.edges.reduce((s:number,e:number[],i:number)=>s+(e.includes(node)?a[i]:0),0)===v)&&connectedEdges(d.nodes.length,d.edges,a);
  if(id==='mintree')return a.reduce((s:number,v:number)=>s+v,0)===d.nodes.length-1&&connectedEdges(d.nodes.length,d.edges,a)&&a.reduce((s:number,v:number,i:number)=>s+v*d.weights[i],0)===d.minimum;
  if(id==='loopclues'){if(!d.clues.every((v:number|null,j:number)=>v===null||d.cellEdges[j].reduce((s:number,i:number)=>s+a[i],0)===v))return false;const degrees=d.nodes.map((_:any,node:number)=>d.edges.reduce((s:number,e:number[],i:number)=>s+(e.includes(node)?a[i]:0),0));if(degrees.some((v:number)=>v!==0&&v!==2))return false;const active=range(d.nodes.length).filter(i=>degrees[i]>0);if(!active.length)return false;const seen=new Set([active[0]]),q=[active[0]];for(let k=0;k<q.length;k++)d.edges.forEach(([u,v]:number[],i:number)=>{if(!a[i])return;const next=u===q[k]?v:v===q[k]?u:-1;if(next>=0&&!seen.has(next)){seen.add(next);q.push(next);}});return seen.size===active.length;}
 }
 if(p.kind==='assignment')return Array.isArray(a)&&a.length===d.n&&new Set(a).size===d.n&&a.every((v,i)=>d.allowed[i].includes(v))&&(!d.relations||d.relations.every((r:any)=>assignmentRuleHolds(a,r)));
 if(p.kind==='card-select'){if(!Array.isArray(a)||new Set(a).size!==a.length||a.some(i=>!Number.isInteger(i)||!d.cards[i]))return false;return id==='odd'?equal(a,[d.oddAnswer]):id==='settriple'?isSet(a.map(i=>d.cards[i])):equal([...a].sort((a,b)=>a-b),range(d.cards.length).filter(i=>cardRule(d.cards[i],d.rule)));}
 if(p.kind==='switches')return Array.isArray(a)&&a.length===d.n&&a.every(v=>v===0||v===1)&&a.reduce((s,v)=>s+v,0)===d.required&&circuitValue(d.tree,a)===1;
 if(p.kind==='arrange')return Array.isArray(a)&&a.length===d.values.length&&new Set(a).size===a.length&&a.every(i=>Number.isInteger(i)&&i>=0&&i<d.values.length)&&d.clues.every(([u,v]:number[])=>a.indexOf(u)<a.indexOf(v))&&(!d.orderRules||d.orderRules.every((r:any)=>orderRuleHolds(a,r)));
 if(p.kind==='domino-chain'){if(!a||!Array.isArray(a.order)||!Array.isArray(a.flips)||a.order.length!==d.tiles.length||a.flips.length!==d.tiles.length||new Set(a.order).size!==a.order.length||a.order.some((i:number)=>!Number.isInteger(i)||!d.tiles[i])||a.flips.some((v:any)=>typeof v!=='boolean'))return false;const tiles=a.order.map((j:number,i:number)=>a.flips[i]?[...d.tiles[j]].reverse():d.tiles[j]);return tiles[0][0]===d.start&&tiles[tiles.length-1][1]===d.end&&tiles.every((t:number[],i:number)=>i===0||tiles[i-1][1]===t[0]);}
 if(p.kind==='visual-choice')return Number.isInteger(a)&&a===p.solution;
 return false;
}
