import {runs,isSet,circuitValue,components} from './logic.ts';
import {islandSolutions} from './islands-solver.mjs';

const range=n=>Array.from({length:n},(_,i)=>i),sum=a=>a.reduce((s,v)=>s+v,0),uniq=a=>[...new Set(a)],j=JSON.stringify;
const adjacent=(i,n)=>[i%n?i-1:-1,i%n<n-1?i+1:-1,i>=n?i-n:-1,i<n*(n-1)?i+n:-1].filter(x=>x>=0);
const near8=(i,n)=>range(n*n).filter(k=>k!==i&&Math.abs(i%n-k%n)<=1&&Math.abs(Math.floor(i/n)-Math.floor(k/n))<=1);
const log=x=>Math.log2(Math.max(1,x));
const canon=a=>{const ids=new Map();return a.map(v=>{if(!ids.has(v))ids.set(v,ids.size);return ids.get(v);});};
const strip=v=>Array.isArray(v)?v.map(strip):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).filter(([k])=>!['extended','scene','initial','solution','minimum','witness'].includes(k)).map(([k,v])=>[k,strip(v)])):v;
const profiles={};

function sudokuMetrics(p){
 const {n,bw,initial}=p.data,bh=n/bw,board=[...initial],groups=[];for(let y=0;y<n;y++)groups.push(range(n).map(x=>y*n+x));for(let x=0;x<n;x++)groups.push(range(n).map(y=>y*n+x));for(let gy=0;gy<n/bh;gy++)for(let gx=0;gx<n/bw;gx++)groups.push(range(n).map(k=>(gy*bh+Math.floor(k/bw))*n+gx*bw+k%bw));
 const peers=range(n*n).map(i=>uniq(groups.filter(a=>a.includes(i)).flat()).filter(k=>k!==i));
 const options=()=>board.map((v,i)=>v?[]:range(n).map(v=>v+1).filter(v=>peers[i].every(k=>board[k]!==v)));
 let rounds=0,naked=0,hidden=0,initialForced=0,maxDomain=0,totalInformation=0;
 const first=options();maxDomain=Math.max(...first.map(a=>a.length));totalInformation=sum(first.map(a=>log(a.length)));
 while(rounds<60){const opts=options(),fills=new Map();for(let i=0;i<board.length;i++)if(!board[i]&&opts[i].length===1)fills.set(i,{v:opts[i][0],type:'naked'});for(const group of groups)for(let v=1;v<=n;v++){const cells=group.filter(i=>!board[i]&&opts[i].includes(v));if(cells.length===1&&!fills.has(cells[0]))fills.set(cells[0],{v,type:'hidden'});}if(!fills.size)break;if(!rounds)initialForced=fills.size;for(const [i,{v,type}]of fills){board[i]=v;if(type==='naked')naked++;else hidden++;}rounds++;}
 const unresolved=board.filter(v=>!v).length;
 return{n,blanks:initial.filter(v=>!v).length,initialForced,propagationRounds:rounds,nakedSingles:naked,hiddenSingles:hidden,unresolved,maxDomain,totalInformation,score:rounds+hidden*.7+unresolved*2+log(totalInformation+1),concept:`${n}x${n}/${unresolved?'search':hidden?'hidden-singles':'naked-singles'}`};
}
const patternsCache=new Map();
function patterns(n){if(!patternsCache.has(n))patternsCache.set(n,range(2**n).map(mask=>range(n).map(i=>mask>>i&1)));return patternsCache.get(n);}
function linePropagation(p,type){
 const {n,given}=p.data,board=[...given],groups=[...range(n).map(y=>range(n).map(x=>y*n+x)),...range(n).map(x=>range(n).map(y=>y*n+x))],all=patterns(n);
 const base=type==='binary'?groups.map(()=>all.filter(a=>sum(a)===n/2&&!a.some((v,i)=>i>1&&v===a[i-1]&&v===a[i-2]))):[...p.data.rows,...p.data.cols].map(clue=>all.filter(a=>j(runs(a))===j(clue)));
 let rounds=0,initialForced=0,forced=0,uniqueLineEliminations=0,initialEntropy=0,maxDomain=0;
 for(let step=0;step<60;step++){
  const domains=groups.map((g,gi)=>base[gi].filter(a=>g.every((at,k)=>board[at]<0||board[at]===a[k])));
  if(type==='binary')for(let gi=0;gi<groups.length;gi++){const group=gi<n?range(n):range(n).map(i=>i+n);for(const gj of group)if(gj!==gi&&groups[gj].every(at=>board[at]>=0)){const filled=groups[gj].map(at=>board[at]),before=domains[gi].length;domains[gi]=domains[gi].filter(a=>j(a)!==j(filled));uniqueLineEliminations+=before-domains[gi].length;}}
  if(!step){maxDomain=Math.max(...domains.map(a=>a.length));initialEntropy=sum(domains.map(a=>log(a.length)));}
  const fills=new Map();groups.forEach((g,gi)=>{if(!domains[gi].length)return;g.forEach((at,k)=>{if(board[at]<0&&domains[gi].every(a=>a[k]===domains[gi][0][k]))fills.set(at,domains[gi][0][k]);});});if(!fills.size)break;if(!rounds)initialForced=fills.size;for(const [at,v]of fills)board[at]=v;rounds++;forced+=fills.size;
 }
 const unknown=given.filter(v=>v<0).length,unresolved=board.filter(v=>v<0).length;
 return{n,unknown,givens:n*n-unknown,initialForced,propagationRounds:rounds,forced,unresolved,initialEntropy,maxDomain,uniqueLineEliminations,score:rounds+unresolved*1.5+log(initialEntropy+1)+uniqueLineEliminations*.3,concept:`${n}x${n}/${unresolved?'lookahead':'line-propagation'}`};
}
function minesMetrics(p){const{n,given,counts}=p.data,a=[...given];let rounds=0,direct=0,subset=0,initialForced=0,contradiction=false;const unknown=given.filter(v=>v<0).length;
 for(let step=0;step<40;step++){const cons=range(n*n).filter(i=>given[i]===0).map(i=>({cells:near8(i,n).filter(j=>a[j]<0),need:counts[i]-sum(near8(i,n).filter(j=>a[j]>=0).map(j=>a[j]))})).filter(c=>c.cells.length);const fills=new Map();for(const c of cons){if(c.need===0||c.need===c.cells.length)for(const at of c.cells)fills.set(at,{v:c.need?1:0,type:'direct'});}
  for(const c of cons)for(const b of cons)if(c!==b&&c.cells.length>b.cells.length&&b.cells.every(at=>c.cells.includes(at))){const diff=c.cells.filter(at=>!b.cells.includes(at)),need=c.need-b.need;if(need===0||need===diff.length)for(const at of diff)if(!fills.has(at))fills.set(at,{v:need?1:0,type:'subset'});}
  if(!fills.size)break;if(!rounds)initialForced=fills.size;for(const [at,{v,type}]of fills){a[at]=v;if(type==='direct')direct++;else subset++;}rounds++;
 }
 const unresolved=a.filter(v=>v<0).length,hiddenStars=given.filter((v,i)=>v<0&&p.solution[i]===1).length,revealedStars=given.filter(v=>v===1).length;
 return{n,unknown,hiddenStars,revealedStars,clues:given.filter(v=>v===0).length,initialForced,direct,subset,propagationRounds:rounds,unresolved,score:rounds+subset*.75+unresolved*2+log(hiddenStars+1),concept:`${n}x${n}/${unresolved?'lookahead':subset?'subset':'direct'}`};
}
function bridgesMetrics(p){const{nodes,edges,degrees}=p.data,incident=nodes.map((_,node)=>edges.flatMap((e,i)=>e.includes(node)?[i]:[])),domains=edges.map(()=>[0,1,2]);let rounds=0,initialForced=0;
 function propagate(ds){let changes=true,steps=0;while(changes){changes=false;steps++;for(let ni=0;ni<nodes.length;ni++){const es=incident[ni],lo=sum(es.map(i=>Math.min(...ds[i]))),hi=sum(es.map(i=>Math.max(...ds[i])));if(lo>degrees[ni]||hi<degrees[ni])return{ok:false,steps};for(const i of es){const othersLo=lo-Math.min(...ds[i]),othersHi=hi-Math.max(...ds[i]),kept=ds[i].filter(v=>v+othersLo<=degrees[ni]&&v+othersHi>=degrees[ni]);if(!kept.length)return{ok:false,steps};if(kept.length!==ds[i].length){ds[i]=kept;changes=true;}}}}return{ok:true,steps:steps-1};}
 const res=propagate(domains);rounds=res.steps;initialForced=domains.filter(a=>a.length===1).length;
 let count=0,searchNodes=0;function dfs(ds){if(++searchNodes>20000||count>=100)return;const q=propagate(ds);if(!q.ok)return;let at=-1;for(let i=0;i<ds.length;i++)if(ds[i].length>1&&(at<0||ds[i].length<ds[at].length))at=i;if(at<0){const seen=new Set([0]),queue=[0];for(let k=0;k<queue.length;k++)incident[queue[k]].forEach(i=>{if(ds[i][0])for(const v of edges[i])if(!seen.has(v)){seen.add(v);queue.push(v);}});if(seen.size===nodes.length)count++;return;}for(const v of ds[at]){const next=ds.map(a=>[...a]);next[at]=[v];dfs(next);}}
 dfs(domains.map(a=>[...a]));const unresolved=domains.filter(a=>a.length>1).length;
 return{nodes:nodes.length,edges:edges.length,cycleRank:edges.length-nodes.length+1,doubleBridges:p.solution.filter(v=>v===2).length,initialForced,propagationRounds:rounds,unresolved,solutions:count,solverNodes:searchNodes,solverCapped:searchNodes>20000||count>=100?1:0,score:rounds+unresolved*.75+log(searchNodes)+Math.max(0,2-log(count+1)),concept:`grid${p.data.n}/cycle-rank${edges.length-nodes.length+1}`};
}
function loopMetrics(p){const{n,nodes,edges,clues,cellEdges}=p.data,incident=nodes.map((_,node)=>edges.flatMap((e,i)=>e.includes(node)?[i]:[])),constraints=[...cellEdges.flatMap((cells,i)=>clues[i]===null?[]:[{cells,valid:[clues[i]]}]),...incident.map(cells=>({cells,valid:[0,2]}))];
 function propagate(board){let rounds=0,initialForced=0;for(let step=0;step<100;step++){const fills=new Map();for(const c of constraints){const fixed=sum(c.cells.filter(i=>board[i]>=0).map(i=>board[i])),unknown=c.cells.filter(i=>board[i]<0),valid=c.valid.filter(v=>v>=fixed&&v<=fixed+unknown.length);if(!valid.length)return{ok:false,rounds,initialForced};for(const at of unknown){const vals=[0,1].filter(v=>valid.some(t=>t>=fixed+v&&t<=fixed+v+unknown.length-1));if(vals.length===1){if(fills.has(at)&&fills.get(at)!==vals[0])return{ok:false,rounds,initialForced};fills.set(at,vals[0]);}}}if(!fills.size)break;if(!step)initialForced=fills.size;for(const [at,v]of fills)board[at]=v;rounds++;}return{ok:true,rounds,initialForced};}
 const board=edges.map(()=>-1),first=propagate(board);let searchNodes=0,count=0,aborted=false;
 function dfs(a){if(++searchNodes>10000){aborted=true;return;}if(count>=2||aborted)return;const prop=propagate(a);if(!prop.ok)return;const at=a.findIndex(v=>v<0);if(at<0){const active=nodes.map((_,i)=>i).filter(i=>incident[i].some(k=>a[k])),seen=new Set(active.slice(0,1)),queue=active.slice(0,1);for(let k=0;k<queue.length;k++)incident[queue[k]].forEach(i=>{if(a[i])for(const v of edges[i])if(!seen.has(v)){seen.add(v);queue.push(v);}});if(active.length&&seen.size===active.length)count++;return;}for(const v of [0,1]){const next=[...a];next[at]=v;dfs(next);}}
 dfs([...board]);const unresolved=board.filter(v=>v<0).length;
 return{n,edges:edges.length,missingClues:clues.filter(v=>v===null).length,zeroClues:clues.filter(v=>v===0).length,threeClues:clues.filter(v=>v===3).length,initialForced:first.initialForced,propagationRounds:first.rounds,unresolved,solutionsCapped2:count,solverNodes:searchNodes,solverAborted:aborted?1:0,loopLength:sum(p.solution),score:first.rounds+log(unresolved+1)*2+log(searchNodes),concept:`${n}x${n}/${unresolved?'loop-lookahead':'local-count'}`};
}
function tentsMetrics(p){const{n,trees,rows,cols}=p.data,poss=trees.map(t=>adjacent(t,n).filter(at=>!trees.includes(at)&&rows[Math.floor(at/n)]>0&&cols[at%n]>0)),r=rows.map(()=>0),c=cols.map(()=>0),selected=[],solutions=new Set();let nodes=0,maxBranch=0;
 const order=range(trees.length).sort((a,b)=>poss[a].length-poss[b].length);function dfs(k){nodes++;if(k===order.length){if(j(r)===j(rows)&&j(c)===j(cols))solutions.add(j([...selected].sort((a,b)=>a-b)));return;}const choices=poss[order[k]].filter(at=>!selected.some(i=>i===at||near8(i,n).includes(at))&&r[Math.floor(at/n)]<rows[Math.floor(at/n)]&&c[at%n]<cols[at%n]);maxBranch=Math.max(maxBranch,choices.length);for(const at of choices){const y=Math.floor(at/n),x=at%n;selected.push(at);r[y]++;c[x]++;dfs(k+1);c[x]--;r[y]--;selected.pop();}}
 dfs(0);const zeroLines=rows.concat(cols).filter(v=>v===0).length,forcedTrees=poss.filter(a=>a.length===1).length,candidateCells=uniq(poss.flat()).length;
 return{n,trees:trees.length,candidateCells,zeroLines,forcedTrees,solutions:solutions.size,solverNodes:nodes,maxBranch,score:log(nodes)+log(candidateCells-trees.length+1)+trees.length-forcedTrees,concept:`${n}x${n}/${trees.length}pairs/${solutions.size===1?'unique':'multiple-valid'}`};
}
function assignmentMetrics(p){const{n,allowed}=p.data,ds=allowed.map(a=>[...a]);let rounds=0,initialForced=0,forcedRows=0,forcedColumns=0;for(let step=0;step<30;step++){const fills=new Map();for(let i=0;i<n;i++)if(ds[i].length===1)fills.set(i,ds[i][0]);for(let v=0;v<n;v++){const rs=range(n).filter(i=>ds[i].includes(v));if(rs.length===1&&ds[rs[0]].length>1){ds[rs[0]]=[v];fills.set(rs[0],v);forcedColumns++;}}let changed=false;for(const [i,v]of fills)for(let k=0;k<n;k++)if(k!==i&&ds[k].includes(v)){ds[k]=ds[k].filter(x=>x!==v);changed=true;}if(!step)initialForced=fills.size;if(!changed)break;rounds++;}const unresolved=ds.filter(a=>a.length>1).length;
 return{n,totalOptions:sum(allowed.map(a=>a.length)),initialSingletonRows:allowed.filter(a=>a.length===1).length,initialSingletonColumns:range(n).filter(v=>allowed.filter(a=>a.includes(v)).length===1).length,initialForced,propagationRounds:rounds,forcedColumns,unresolved,maxChoices:Math.max(...allowed.map(a=>a.length)),score:rounds+forcedColumns*.7+log(sum(allowed.map(a=>a.length))-n+1)+unresolved*2,concept:`${n}people/${unresolved?'matching-lookahead':'singleton-elimination'}`};
}
function treeMetrics(t){if(typeof t==='number')return{depth:0,ops:[],leaves:[t],balanced:0};const a=treeMetrics(t.left),b=treeMetrics(t.right);return{depth:1+Math.max(a.depth,b.depth),ops:[t.op,...a.ops,...b.ops],leaves:[...a.leaves,...b.leaves],balanced:a.balanced+b.balanced+(a.depth>0&&b.depth>0?1:0)};}
function eulerPossible(tiles,current,end){if(!tiles.length)return current===end;const degree=new Map(),adj=new Map();for(const [a,b]of tiles){degree.set(a,(degree.get(a)||0)+1);degree.set(b,(degree.get(b)||0)+1);if(!adj.has(a))adj.set(a,[]);if(!adj.has(b))adj.set(b,[]);adj.get(a).push(b);adj.get(b).push(a);}if(!degree.get(current))return false;for(const [v,d]of degree)if((d%2)!==+(current!==end&&(v===current||v===end)))return false;const seen=new Set([current]),q=[current];for(let k=0;k<q.length;k++)for(const v of adj.get(q[k])||[])if(!seen.has(v)){seen.add(v);q.push(v);}return seen.size===degree.size;}
function dominoMetrics(p){const{tiles,start,end}=p.data,degree={};for(const [a,b]of tiles){degree[a]=(degree[a]||0)+1;degree[b]=(degree[b]||0)+1;}let used=new Set(),current=start,branchSteps=0,trapChoices=0,maxBranch=0;for(let k=0;k<tiles.length;k++){const choices=tiles.flatMap(([a,b],i)=>used.has(i)?[]:a===current?[[i,b]]:b===current?[[i,a]]:[]);const distinct=uniq(choices.map(([i,to])=>j([tiles[i].slice().sort((a,b)=>a-b),to]))).length;if(distinct>1)branchSteps++;maxBranch=Math.max(maxBranch,distinct);for(const [i,to]of choices)if(!eulerPossible(tiles.filter((_,j)=>!used.has(j)&&j!==i),to,end))trapChoices++;const at=p.solution.order[k],flipped=p.solution.flips[k],t=flipped?[...tiles[at]].reverse():tiles[at];used.add(at);current=t[1];}
 const uniqueTiles=uniq(tiles.map(t=>j([...t].sort((a,b)=>a-b)))).length,loops=tiles.filter(([a,b])=>a===b).length,junctions=Object.values(degree).filter(v=>v>2).length;
 return{tiles:tiles.length,uniqueTiles,loops,junctions,branchSteps,trapChoices,maxBranch,sameEnds:+(start===end),score:branchSteps+trapChoices*2+junctions*.5+log(uniqueTiles),concept:`${tiles.length}tiles/${trapChoices?'ordering-traps':branchSteps?'free-branches':'forced-chain'}`};
}
function scheduleMetrics(p){const n=p.data.values.length,clues=p.data.clues,reach=range(n).map(i=>range(n).map(k=>i===k?1:0));for(const[a,b]of clues)reach[a][b]=1;for(let k=0;k<n;k++)for(let a=0;a<n;a++)for(let b=0;b<n;b++)if(reach[a][k]&&reach[k][b])reach[a][b]=1;const comparable=range(n).reduce((s,a)=>s+range(n).filter(b=>b!==a&&reach[a][b]).length,0),essential=clues.filter(([a,b])=>!clues.some(([u,v])=>u===a&&v!==b&&reach[v][b])).length;let count=0,branchStates=0,maxBranch=0;function dfs(order){if(order.length===n){count++;return;}const choices=range(n).filter(v=>!order.includes(v)&&clues.every(([a,b])=>b!==v||order.includes(a)));if(choices.length>1)branchStates++;maxBranch=Math.max(maxBranch,choices.length);for(const v of choices)dfs([...order,v]);}dfs([]);const longest=range(n).map(v=>{const walk=(x,seen)=>Math.max(1,...clues.filter(([a])=>a===x&&!seen.includes(a)).map(([a,b])=>1+walk(b,[...seen,a])));return walk(v,[]);});
 return{n,clues:clues.length,essentialClues:essential,redundantClues:clues.length-essential,comparablePairs:comparable,validOrders:count,branchStates,maxBranch,longestChain:Math.max(...longest),score:essential+n*.5+range(n).filter(v=>clues.filter(([a])=>a===v).length>1||clues.filter(([,b])=>b===v).length>1).length+Math.max(...longest)*.25,concept:`${n}cards/${count===1?'full-chain':'partial-order'}`};}
function mstMetrics(p){const{nodes,edges,weights}=p.data,n=nodes.length;const costs=[];let greedyCycleSkips=0;for(let mask=0;mask<2**edges.length;mask++){const selected=range(edges.length).filter(i=>mask>>i&1);if(selected.length!==n-1)continue;const seen=new Set([0]),q=[0];for(let k=0;k<q.length;k++)for(const i of selected)if(edges[i].includes(q[k]))for(const v of edges[i])if(!seen.has(v)){seen.add(v);q.push(v);}if(seen.size===n)costs.push(sum(selected.map(i=>weights[i])));}costs.sort((a,b)=>a-b);const min=costs[0],optimal=costs.filter(v=>v===min).length,next=costs.find(v=>v>min),parent=range(n),root=i=>parent[i]===i?i:(parent[i]=root(parent[i]));let chosen=0;for(const i of range(edges.length).sort((a,b)=>weights[a]-weights[b])){const[a,b]=edges[i],ra=root(a),rb=root(b);if(ra===rb){if(chosen<n-1)greedyCycleSkips++;}else{parent[ra]=rb;chosen++;}}
 return{nodes:n,edges:edges.length,cycleRank:edges.length-n+1,distinctWeights:uniq(weights).length,optimalTrees:optimal,spanningTrees:costs.length,secondBestGap:next===undefined?0:next-min,greedyCycleSkips,score:edges.length-n+1+greedyCycleSkips*2+log(costs.length/optimal)+1/(1+(next===undefined?0:next-min)),concept:`fan${n}/${greedyCycleSkips?'cycle-rejection':'direct-cheapest'}`};}

export function logicMetricsRaw(p){const d=p.data,id=p.id;if(d.curriculumMetrics)return {...d.curriculumMetrics};let m={};
 if(id==='pattern'){const seq=d.seq,period=range(seq.length).slice(1).find(k=>seq.every((v,i)=>i<k||v===seq[i-k]))||seq.length,unit=seq.slice(0,period),turnback=unit.length>uniq(unit).length;const phase=seq.length%period;m={period,symbols:uniq(seq).length,shown:seq.length,phase,turnback:+turnback,score:uniq(seq).length+turnback*2+(phase>0?.5:0),concept:`${turnback?'out-and-back':'cycle'}-${period}`,semantic:j([canon(unit),phase])};}
 else if(id==='matrix'){const{n,values}=d,dx=values[1]-values[0],dy=values[n]-values[0];m={n,dx,dy,equalSteps:+(dx===dy),maxValue:Math.max(...values),reasoningOperations:2,independentRules:2,score:2+(dx!==dy?.7:0)+log(Math.max(dx,dy))*.15,concept:'constant-additive-row-and-column',semantic:j([n,dx,dy])};}
 else if(id==='sudoku')m=sudokuMetrics(p);
 else if(id==='order'){m={n:d.n,clues:d.clues.length,directAdjacencyClues:d.clues.length,inferenceDepth:1,solutionPermutations:1,score:1+Math.max(0,d.n-3)*.25,concept:'fully-disclosed-adjacency-chain',semantic:`chain-${d.n}`};}
 else if(id==='balance'){const steps=d.targetShape===0?1:d.cb===1?2:3;m={reasoningOperations:steps,targetShape:d.targetShape,coefficientA:d.ca,coefficientB:d.cb,unknownA:d.aTotal/d.ca,unknownB:d.second-d.aTotal/d.ca,maxDisplayed:Math.max(d.aTotal,d.second),score:steps+(d.ca>2?.25:0)+(d.cb>1?.25:0),concept:`${steps}operations`,semantic:j([d.targetShape,d.ca,d.cb])};}
 else if(id==='odd')m={n:d.n,items:d.n*d.n,featureDifferences:1,baseGlyph:d.base,direction:+(d.variant==='direction'),score:1+(d.variant==='direction'?.5:0)+log(d.n*d.n)*.1,concept:`single-${d.variant}-outlier`,semantic:d.variant};
 else if(id==='nonogram'){m=linePropagation(p,'nonogram');m.clueRuns=sum(d.rows.concat(d.cols).map(a=>a.filter(v=>v>0).length));m.trivialLines=d.rows.concat(d.cols).filter(a=>a[0]===0||sum(a)+a.length-1===d.n).length;}
 else if(id==='liar'){const n=d.people.length,counts=range(n).map(v=>d.statements.filter(s=>(v===s.person)===s.is).length),distinct=uniq(d.statements.map(s=>j(s))),negative=d.statements.filter(s=>!s.is).length,contradictory=range(n).filter(v=>d.statements.some(s=>s.person===v&&s.is)&&d.statements.some(s=>s.person===v&&!s.is)).length,extreme=+(d.trueCount===0||d.trueCount===d.statements.length);m={people:n,statements:d.statements.length,distinctStatements:distinct.length,negativeStatements:negative,contradictoryPeople:contradictory,trueCount:d.trueCount,extremeTruthCount:extreme,candidateCount:p.options.length,minTruthCountGap:Math.min(...counts.filter(v=>v!==d.trueCount).map(v=>Math.abs(v-d.trueCount))),score:distinct.length+negative*.5+contradictory*.75-extreme*2,concept:`unary-statements/${extreme?'all-or-none':'count-truth'}`,semantic:j([canon(d.statements.map(s=>s.person)),d.statements.map(s=>s.is),d.trueCount])};}
 else if(id==='zebra')m=assignmentMetrics(p);
 else if(id==='venn'){function ruleStats(r){if(!r.op)return{atoms:1,ops:0,neg:0,depth:0};const a=ruleStats(r.child||r.left),b=r.right?ruleStats(r.right):{atoms:0,ops:0,neg:0,depth:0};return{atoms:a.atoms+b.atoms,ops:a.ops+b.ops+1,neg:a.neg+b.neg+(r.op==='not'?1:0),depth:1+Math.max(a.depth,b.depth)};}const s=ruleStats(d.rule);let truthClasses=1,nearMisses=0;if(d.rule.left){const raw=d.rule.left.child||d.rule.left,b=d.rule.right;const masks=d.cards.map(c=>`${+(c[raw.attr]===raw.value)}${+(c[b.attr]===b.value)}`);truthClasses=uniq(masks).length;nearMisses=masks.filter(v=>v==='01'||v==='10').length;}m={cards:d.cards.length,selected:p.solution.length,atoms:s.atoms,operators:s.ops,negations:s.neg,depth:s.depth,truthClasses,nearMisses,score:s.atoms+s.ops*2+s.neg+truthClasses*.5,concept:d.rule.op?`${d.rule.left?.op||'positive'}-${d.rule.op}`:'one-attribute',semantic:j(d.rule)};}
 else if(id==='minestars')m=minesMetrics(p);
 else if(id==='bridges')m=bridgesMetrics(p);
 else if(id==='loopclues')m=loopMetrics(p);
 else if(id==='islands'){const exact=islandSolutions(d.n,d.clues),sizes=Object.values(d.clues);m={n:d.n,islands:sizes.length,nonSingletonIslands:sizes.filter(v=>v>1).length,maxIslandSize:Math.max(...sizes),unknown:d.given.filter(v=>v<0).length,regionCandidates:sum(exact.candidateCounts),maxRegionCandidates:Math.max(...exact.candidateCounts),solverNodes:exact.nodes,solverAborted:+exact.aborted,solutionsCapped2:exact.count,score:log(exact.nodes)+log(sum(exact.candidateCounts)+1)+sizes.filter(v=>v>1).length*.5,concept:`${d.n}x${d.n}/max-island${Math.max(...sizes)}`};}
 else if(id==='tents')m=tentsMetrics(p);
 else if(id==='binary')m=linePropagation(p,'binary');
 else if(id==='circuit'){const t=treeMetrics(d.tree),all=range(2**d.n).map(mask=>range(d.n).map(i=>mask>>i&1)),candidates=all.filter(a=>sum(a)===d.required),valid=candidates.filter(a=>circuitValue(d.tree,a));m={switches:d.n,required:d.required,depth:t.depth,gateKinds:uniq(t.ops).length,xorGates:t.ops.filter(v=>v==='XOR').length,branchingSubtrees:t.balanced,candidateAssignments:candidates.length,validAssignments:valid.length,validFraction:valid.length/candidates.length,score:t.depth+uniq(t.ops).length+log(candidates.length/valid.length)+t.balanced*.5,concept:`${d.n}switches/${uniq(t.ops).sort().join('+')}/${d.required}on`,semantic:j([d.tree,d.required])};}
 else if(id==='rulemachine'){const shifts=Object.values(d.shift),changed=shifts.filter(v=>v!==0).length,answer=p.options[p.solution],dist=p.options.filter((_,i)=>i!==p.solution).map(v=>['shape','color','count'].filter(k=>v[k]!==answer[k]).length);m={changedAttributes:changed,shapeShift:d.shift.shape,colorShift:d.shift.color,countShift:d.shift.count,identity:+(changed===0),examples:d.scene.examples.length,minDistractorDifferences:Math.min(...dist),nearMissDistractors:dist.filter(v=>v===1).length,score:changed*2+dist.filter(v=>v===1).length*.5,concept:`${changed}attribute-cyclic-shift`,semantic:j(d.shift)};}
 else if(id==='schedule')m=scheduleMetrics(p);
 else if(id==='domino')m=dominoMetrics(p);
 else if(id==='familytree'){const depth=i=>i<0?-1:1+depth(d.parents[i]),depths=d.parents.map((_,i)=>depth(i));let at=d.target,pathBranches=0;for(let k=0;k<d.steps;k++){const parent=d.parents[at];pathBranches+=+(d.parents.filter(v=>v===parent).length>1);at=parent;}m={nodes:d.parents.length,treeDepth:Math.max(...depths),targetDepth:depths[d.target],requiredHops:d.steps,pathBranches,answerIsRoot:+(at===0),score:d.steps+pathBranches*.15,concept:`repeat-parent-${d.steps}`,semantic:`parent-${d.steps}/targetDepth-${depths[d.target]}`};}
 else if(id==='settriple'){const sets=[];for(let a=0;a<d.cards.length;a++)for(let b=a+1;b<d.cards.length;b++)for(let c=b+1;c<d.cards.length;c++)if(isSet([d.cards[a],d.cards[b],d.cards[c]]))sets.push([a,b,c]);const varying=sets.map(s=>['shape','color','count'].filter(k=>uniq(s.map(i=>d.cards[i][k])).length===3).length),minVary=Math.min(...varying);m={cards:d.cards.length,colorCount:uniq(d.cards.map(c=>c.color)).length,validTriples:sets.length,minVaryingAttributes:minVary,maxVaryingAttributes:Math.max(...varying),oneAttributeSets:varying.filter(v=>v===1).length,twoAttributeSets:varying.filter(v=>v===2).length,threeAttributeSets:varying.filter(v=>v===3).length,score:minVary*3+log(84/sets.length),concept:`9cards/${minVary}minimum-changing-attributes`};}
 else if(id==='mintree')m=mstMetrics(p);
 else if(id==='cipher'){const distinct=uniq(d.message).length,layers=d.map2?2:1,composed=d.map.map((v,i)=>d.map2?d.map2[v]:v),fixed=uniq(d.message).filter(i=>composed[i]===i).length;m={alphabet:d.map.length,messageLength:d.message.length,distinctSymbols:distinct,layers,lookupSteps:distinct*layers,fixedTargetSymbols:fixed,optionsCount:p.options.length,repeatedOnly:+(distinct===1),score:distinct*layers+Math.max(0,layers-1)-fixed*.25,concept:`${layers}lookup-layers/${distinct}distinct-symbols`,semantic:j([layers,canon(d.message),fixed])};}
 else throw Error(id);
 m.score=Math.round(m.score*1000)/1000;return m;
}

