import{context,range,key,equal,normalize,rotate,adjacent,perimeter,connected,sceneShape,sceneText,sceneGrid,type Puzzle,type Meta}from'./shared.ts';
export const PLANE_META:Meta[]=[
['perimeter','ぐるっと フェンス','plane','まわりは いくつぶん？','マスの辺を1として、外周の長さを数えます。中に穴があれば、その周りも数えます。'],
['tiling','しきつめ パズル','plane','ぜんぶ ぴったり はめよう','ピースを選び、床のマスをタップして置きます。回転できます。重ねず、すべての床を埋めましょう。'],
['equalparts','おなじ ひろさ','plane','おうちごとに おなじ ひろさに','家を選んでマスを塗ります。各庭に家が1つ、広さが同じ、庭のマス同士が縦横につながれば成功です。'],
['translate','すいすい ずらそう','plane','やじるしの とおりに うごかそう','形の向きは変えず、矢印の数だけマスを移動します。最後の位置を選びます。'],
['foldpunch','おって あなあけ','plane','ひらくと あなは どこ？','紙を矢印の向きに半分ずつ折り、丸の所に穴を開けます。元の紙の穴になるマスを全部選びます。'],
['angles','かくどの パズル','plane','？の かくどは いくつ？','半回転は180度、1周は360度。図に書いた角度を使って、残りの角度を選びます。'],
['circlecenter','えんの まんなか','plane','3つの てんから おなじ きょりは？','3つの赤い点を通る円の中心を選びます。中心から3点までの距離は、すべて同じです。'],
['triangulate','さんかくの へや','plane','ぜんぶ さんかくに わけよう','角を2つ選んで対角線を引きます。線を交差させず、すべての部屋を三角形にします。点線の禁止線は使えません。'],
['pairroutes','ペアの おさんぽ','plane','おなじ しるしを つなごう','ペアを選んで道をなぞります。道を交差させず、全部のマスを使って同じ番号を結びます。ひとつ前のマスで戻せます。'],
['mapcolor','となりは べついろ','plane','となりを ちがう いろに','色を選んで地域を塗ります。辺で接する地域は違う色にします。角だけで接する地域は同じでも大丈夫です。'],
['inside','かこいの なか','plane','なかの てんを ぜんぶ えらぼう','曲がった囲いをよく見て、内側にある点をすべて選びます。'],
['jigsaw','つながる ピース','plane','となりの しるしを あわせよう','ピースを選び、置きたい場所をタップします。となりの同じ数字の＋と−をつなぎ、外側は0にします。回転できます。'],
['mirrorbeam','ひかりの みち','plane','かがみを まわして とどけよう','鏡をタップして向きを変えます。入口から出た光を星の出口へ届けましょう。'],
['scale','おおきく コピー','plane','ばいに すると どの かたち？','縦も横も同じ倍率に広げます。元の1マスが、2倍なら2×2マスになります。'],
['separator','いっぽんの しきり','plane','まると ほしを わけよう','外側の点を2つ選んで直線を引きます。どの点にも触れず、丸と星を両側に分けましょう。'],
['hull','ぴんと ゴムバンド','plane','ゴムが ひっかかる かどは？','全部の点を囲むゴムをぴんと張ったとき、角になる点をすべて選びます。一直線の途中の点は選びません。'],
['parallel','へいこう レール','plane','おなじ むきの せんは どれ？','お手本と平行な線をすべて選びます。長さや場所が違っても、同じ傾きなら仲間です。'],
['coinparking','まるい ちゅうしゃじょう','plane','かさならないように おこう','決められた数の円を置きます。円同士が重ならず、箱からはみ出さなければ成功。ぴったり触れるのは大丈夫です。'],
];
export const cross=(a:number[],b:number[],c:number[])=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
export function pointInside(p:number[],poly:number[][]){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const[a,b]=[poly[i],poly[j]];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
export function hullIndices(points:number[][]){const indices=range(points.length).sort((a,b)=>points[a][0]-points[b][0]||points[a][1]-points[b][1]),half=(arr:number[])=>{const out:number[]=[];for(const i of arr){while(out.length>=2&&cross(points[out.at(-2)!],points[out.at(-1)!],points[i])<=0)out.pop();out.push(i);}return out;};return[...half(indices).slice(0,-1),...half([...indices].reverse()).slice(0,-1)];}
export function mixPath(n:number,rows:number,c:ReturnType<typeof context>){let path=range(n*rows).map(i=>{const y=Math.floor(i/n);return y*n+(y%2?n-1-i%n:i%n);});for(let k=0;k<30+10*n;k++){if(c.int(0,1))path.reverse();const choices=adjacent(path[0],n,rows).map(v=>path.indexOf(v)).filter(i=>i>=2);if(choices.length){const at=c.pick(choices);path=[...path.slice(0,at).reverse(),...path.slice(at)];}}return path;}
export function beamTrace(n:number,mirrors:number[],values:number[],row:number){let x=-1,y=row,dir=1;const cells:number[]=[],seen=new Set<string>();for(let k=0;k<n*n*4+1;k++){x+=[0,1,0,-1][dir];y+=[-1,0,1,0][dir];if(x<0||y<0||x>=n||y>=n)return{cells,exit:{side:y<0?0:x>=n?1:y>=n?2:3,index:y<0||y>=n?x:y},loop:false};const at=y*n+x,state=key([at,dir]);if(seen.has(state))return{cells,exit:null,loop:true};seen.add(state);cells.push(at);const m=mirrors.indexOf(at);if(m>=0)dir=values[m]===0?[1,0,3,2][dir]:[3,2,1,0][dir];}return{cells,exit:null,loop:true};}
export function tileEdges(edges:number[],q:number){return range(4).map(i=>edges[(i-q+4)%4]);}
const sorted=(a:number[])=>[...a].sort((a,b)=>a-b);
function planeShape(c:ReturnType<typeof context>,phase:number,level:number){
 const {int,pick}=c;
 if(phase===0)return c.shape(int(4,7));
 const w=int(phase>=3?5:4,phase>=3?7:6),h=int(phase>=3?5:4,6);let cells=range(w*h).map(i=>[i%w,Math.floor(i/w)]);
 if(phase===1){const cutW=int(1,w-2),cutH=int(1,h-2);cells=cells.filter(([x,y])=>x<w-cutW||y<h-cutH);}
 else if(phase===2){const hx=int(1,w-2),hy=int(1,h-2),hw=int(1,Math.min(2,w-1-hx)),hh=int(1,Math.min(2,h-1-hy));cells=cells.filter(([x,y])=>x<hx||x>=hx+hw||y<hy||y>=hy+hh);}
 else {const holes=c.shuffle(range((w-2)*(h-2)).map(i=>[i%(w-2)+1,Math.floor(i/(w-2))+1])),[first,second]=pick(holes.flatMap((a,i)=>holes.slice(i+1).filter(b=>Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1])>=3).map(b=>[a,b])));cells=cells.filter(v=>!equal(v,first)&&!equal(v,second));if(phase>=4){const corners=c.shuffle([[0,0],[w-1,0],[0,h-1],[w-1,h-1]]).slice(0,int(1,3));cells=cells.filter(v=>!corners.some(q=>equal(q,v)));}}
 return rotate(cells,pick([0,1,2,3]));
}
const planeLineDistance=(p:number[],a:number[],b:number[])=>Math.abs(cross(a,b,p))/Math.hypot(b[0]-a[0],b[1]-a[1]);
function planeParkingGraph(points:number[][],radius:number,k:number){
 const masks=points.map((p,i)=>points.reduce((m,q,j)=>i!==j&&(p[0]-q[0])**2+(p[1]-q[1])**2<4*radius**2?m|(1<<j):m,0));let maximum=0,count=0;const valid=new Uint8Array(1<<points.length),sizes=new Uint8Array(valid.length);valid[0]=1;for(let mask=1;mask<valid.length;mask++){const bit=mask&-mask,i=31-Math.clz32(bit),rest=mask^bit;if(valid[rest]&&!(masks[i]&rest)){valid[mask]=1;sizes[mask]=sizes[rest]+1;maximum=Math.max(maximum,sizes[mask]);if(sizes[mask]===k)count++;}}return{maximum,count,masks};
}
export function generatePlane(id:string,level:number,seed:number):Puzzle|undefined{
 if(!PLANE_META.some(m=>m[0]===id))return;const c=context(id,level,seed),{L,int,pick,shuffle,base,choice,numeric,shape}=c,phase=Math.floor((L-1)/4),step=(L-1)%4;
 if(id==='perimeter'){const cells=planeShape(c,phase,L);return numeric(perimeter(cells),sceneShape(cells,{grid:true}),'へこみや あなの まわりも、1へんずつ たどろう。',1,{cells,concept:phase});}
 if(id==='tiling'){
  const n=phase===0?(step===3?4:3):phase===4?5:4,rows=phase<2?2+Math.floor(step/2):4,k=phase===0?2:phase===1?3:phase<4?4:5,path=mixPath(n,rows,c),sizes=range(k).map(()=>2);for(let j=2*k;j<path.length;j++)sizes[int(0,k-1)]++;
  let at=0;const groups=sizes.map(size=>{const g=path.slice(at,at+size);at+=size;return g;}),turns=groups.map(()=>L<=2?0:int(0,3)),order=shuffle(range(k)),pieces=order.map(i=>rotate(normalize(groups[i].map(at=>[at%n,Math.floor(at/n)])),turns[i])),solution=groups.map((g,i)=>({piece:order.indexOf(i),x:Math.min(...g.map(i=>i%n)),y:Math.min(...g.map(i=>Math.floor(i/n))),q:(4-turns[i])%4}));
  return base('tiling',{n,rows,pieces,initial:[],concept:phase},solution,phase<2?'かどと まっすぐな へんを あわせよう。':'くぼみに はまる ピースから。のこりの すきまも たしかめよう。');
 }
 if(id==='equalparts'){
  const dimensions=phase===0?[[3,2,2],[4,2,2],[3,4,2],[4,3,2]][step]:[[3,2,2],[4,3,3],[4,4,4],[5,4,4],[5,5,5]][phase],[n,rows,k]=dimensions,path=mixPath(n,rows,c),groups=range(k).map(i=>path.slice(i*path.length/k,(i+1)*path.length/k));
  const homes=groups.map((g,i)=>{if(phase<2)return pick(g);const other=groups.filter((_,j)=>j!==i).flat();return [...g].sort((a,b)=>Math.min(...other.map(v=>Math.abs(a%n-v%n)+Math.abs(Math.floor(a/n)-Math.floor(v/n))))-Math.min(...other.map(v=>Math.abs(b%n-v%n)+Math.abs(Math.floor(b/n)-Math.floor(v/n))))||c.r()-.5)[0];}),solution=range(n*rows).map(at=>groups.findIndex(g=>g.includes(at)));
  return base('district',{n,rows,k,homes,initial:range(n*rows).map(i=>homes.indexOf(i)),concept:phase},solution,phase<2?'1つの にわの マスすうを さきに きめよう。':'となりあう いえの にわを のばして、つながる みちを のこそう。');
 }
 if(id==='translate'){
  const n=6+Math.floor(L/7),cells=shape(3+Math.floor(L/7)),w=Math.max(...cells.map(a=>a[0]))+1,h=Math.max(...cells.map(a=>a[1]))+1,lengths=[1+Math.floor(step/2),3+Math.floor(step/2),5+Math.floor(step/2),7+Math.floor(step/2),9+Math.floor(step/2)],length=lengths[phase];
  for(let attempt=0;attempt<1000;attempt++){const start=[int(0,n-w),int(0,n-h)],moves:number[]=[];let pos=[...start];for(let k=0;k<length;k++){let ds=range(4).filter(d=>{const x=pos[0]+[0,1,0,-1][d],y=pos[1]+[-1,0,1,0][d];return x>=0&&x<=n-w&&y>=0&&y<=n-h;});if(phase===0&&moves.length)ds=ds.filter(d=>d===moves[0]);if(!ds.length)break;const d=pick(ds);moves.push(d);pos=[pos[0]+[0,1,0,-1][d],pos[1]+[-1,0,1,0][d]];}const net=Math.abs(pos[0]-start[0])+Math.abs(pos[1]-start[1]),axes=new Set(moves.map(d=>d%2)).size,turns=moves.slice(1).filter((d,i)=>d%2!==moves[i]%2).length;if(moves.length!==length||net===0||phase>=1&&axes<2||phase===1&&net!==length||phase>=2&&length-net<2||phase>=3&&turns<3)continue;
   const sc=(p:number[])=>sceneShape(cells.map(([x,y])=>[x+p[0],y+p[1]]),{extent:n,grid:true}),wrong=shuffle(range((n-w+1)*(n-h+1)).map(i=>[i%(n-w+1),Math.floor(i/(n-w+1))]).filter(p=>!equal(p,pos))).sort((a,b)=>Math.abs(a[0]-pos[0])+Math.abs(a[1]-pos[1])-Math.abs(b[0]-pos[0])-Math.abs(b[1]-pos[1])).slice(0,3).map(sc);return choice(sc(pos),wrong,{type:'translation',cells:cells.map(([x,y])=>[x+start[0],y+start[1]]),n,moves},phase<2?'よこと たてを べつべつに たどろう。':'はんたいむきの やじるしを うちけしてから うごかそう。',{moves,start,pos,concept:phase});
  }throw Error('translation structure generation');
 }
 if(id==='foldpunch'){
  const n=phase===0&&step<2?4:8,folds=phase===0?[pick(['x','y'])]:phase===1?shuffle(['x','y']):phase===2?[pick(['x','y']),'' ]:phase===3?shuffle(['x','x','y']):shuffle(['x','x','y','y']);if(phase===2)folds[1]=folds[0];if(phase===3&&int(0,1))for(let i=0;i<folds.length;i++)folds[i]=folds[i]==='x'?'y':'x';let w=n,h=n;for(const f of folds)if(f==='x')w/=2;else h/=2;
  const punches=phase===0?1+Number(step>=2):phase===1?1+Math.floor((step+1)/2):phase===2?1+Number(step>=2):phase===3?2+Number(step>=2):2+Number(step>=2),holes=shuffle(range(w*h)).slice(0,punches),solution=range(n*n).map(i=>{let x=i%n,y=Math.floor(i/n),ww=n,hh=n;for(const f of folds)if(f==='x'){x=x>=ww/2?ww-1-x:x;ww/=2;}else{y=y>=hh/2?hh-1-y:y;hh/=2;}return holes.includes(y*w+x)?1:0;});return base('fold-grid',{n,folds,w,h,holes,initial:range(n*n).map(()=>0),scene:{type:'folds',n,folds,w,h,holes},concept:phase},solution,'さいごの おりめから、じゅんばんを もどして ひらこう。');
 }
 if(id==='angles'){
  const total=phase===0?90:phase<3?180:360,count=phase===0?2+Number(step===3):phase===1?2:phase<4?3:4+Number(step>=2),unit=phase===0?[15,10,5,5][step]:phase<3?10:5,cuts=shuffle(range(total/unit-1).map(i=>(i+1)*unit)).slice(0,count-1).sort((a,b)=>a-b),edges=[0,...cuts,total],parts=edges.slice(1).map((v,i)=>v-edges[i]),missing=int(0,count-1);return choice(parts[missing],shuffle(range(total/unit-1).map(i=>(i+1)*unit).filter(v=>v!==parts[missing])).slice(0,3),{type:'angles',parts,total,missing,label:total===90?'ちょっかく':total===180?'はんかいてん':'1しゅう'},`ぜんぶで ${total}ど。わかる かくどを あわせて ひこう。`,{parts,total,missing,concept:phase});
 }
 if(id==='circlecenter'){
  const [a,b]=pick((phase===0?[[2,0]]:phase===1?[[3,0],[2,1]]:phase===2?[[3,1],[3,2]]:phase===3?[[4,1],[3,2]]:[[4,3],[4,1]]) as number[][]),n=phase>=3?12:10,margin=Math.max(a,b),center=[int(margin,n-margin),int(margin,n-margin)],offsets=Array.from(new Map([[a,b],[a,-b],[-a,b],[-a,-b],[b,a],[b,-a],[-b,a],[-b,-a]].map(v=>[key(v),v])).values());let selected:number[][]=[];
  for(let t=0;t<100;t++){selected=shuffle(offsets).slice(0,3);const ds=selected.map((v,i)=>{const q=selected[(i+1)%3];return(v[0]-q[0])**2+(v[1]-q[1])**2;});if(phase>=2&&ds.includes(4*(a*a+b*b)))continue;if(phase>=3&&new Set(ds).size<3)continue;break;}
  const points=selected.map(([x,y])=>[x+center[0],y+center[1]]),delta=phase===0?[[2,0],[0,2],[-2,0],[0,-2],[1,1],[-1,1],[1,-1],[-1,-1],[2,1],[-2,1],[1,-2],[-1,-2]]:phase===1?[[1,0],[0,1],[-1,1],[1,-1]]:[[1,0],[0,1],[-1,1],[1,-1],[-1,0],[0,-1]],wrong=shuffle(delta).filter(([x,y])=>!points.some(p=>equal(p,[center[0]+x,center[1]+y]))).slice(0,3).map(([x,y])=>[center[0]+x,center[1]+y]),candidates=shuffle([center,...wrong]),answer=candidates.findIndex(p=>equal(p,center));return choice(String.fromCharCode(65+answer),range(4).filter(i=>i!==answer).map(i=>String.fromCharCode(65+i)),{type:'circlecenter',points,candidates,n},phase===0?'むかいあう 2てんの まんなかを たしかめよう。':'2てんまでの きょりだけで きめず、3てんめも たしかめよう。',{points,candidates,concept:phase});
 }
 if(id==='triangulate'){
  const n=phase===0?Math.min(6,4+step):phase===1?6+Number(step>=2):Math.min(9,4+phase+Number(step>=2)),nodes=range(n).map(i=>{const angle=-Math.PI/2+(i+c.r()*.2)*2*Math.PI/n;return[3+2.7*Math.cos(angle),3+2.7*Math.sin(angle)];});let solution:number[][]=[];
  do{const polygon=range(n);solution=[];while(polygon.length>3){const at=int(0,polygon.length-1),a=polygon[(at+polygon.length-1)%polygon.length],b=polygon[(at+1)%polygon.length];solution.push([a,b].sort((a,b)=>a-b));polygon.splice(at,1);}}while(phase>=2&&range(n).some(v=>solution.every(e=>e.includes(v))));
  const possible=shuffle(range(n).flatMap(a=>range(n).filter(b=>b>a+1&&!(a===0&&b===n-1)).map(b=>[a,b])).filter(e=>!solution.some(v=>equal(e,v)))),banned:number[][]=[];
  if(phase>=2)for(let root=0;root<n;root++){const fan=possible.filter(e=>e.includes(root));if(!banned.some(e=>e.includes(root))&&fan.length)banned.push(pick(fan));}
  const target=phase===0?(step===0?0:step===3?2:1):phase===1?2+Number(step>=2):phase===2?banned.length:phase===3?n-2:n+1;for(const e of possible)if(banned.length<target&&!banned.some(v=>equal(v,e)))banned.push(e);
  return base('chords',{n,nodes,banned,initial:[],concept:phase},solution,phase<2?'1つの かどから、さんかくを つくろう。':'ひける せんが すくない かどから。できた さんかくを よけて かんがえよう。');
 }
 if(id==='pairroutes'){
  const n=phase===0?(step>=2?4:3):phase<3?4:5,k=phase===0?2:phase===1?2+Number(step>=2):phase===2?3:phase===3?3+Number(step>=2):4+Number(step>=2),minimum=[0,2,4,6,8][phase];
  for(let attempt=0;attempt<1000;attempt++){const path=mixPath(n,n,c),sizes=range(k).map(()=>2);for(let i=2*k;i<path.length;i++)sizes[int(0,k-1)]++;let at=0;const solution=sizes.map(size=>{const out=path.slice(at,at+size);at+=size;return out;}),pairs=solution.map(a=>[a[0],a.at(-1)!]),distance=pairs.reduce((s,[a,b])=>s+Math.abs(a%n-b%n)+Math.abs(Math.floor(a/n)-Math.floor(b/n)),0),detour=n*n-k-distance,interior=pairs.flat().some(i=>i%n>0&&i%n<n-1&&i>=n&&i<n*(n-1));if(detour<minimum||phase>=3&&!interior)continue;return base('pairpaths',{n,pairs,initial:pairs.map(p=>[p[0]]),concept:phase},solution,'みじかく つなぐだけでは、あきマスが のこるよ。ほかの ペアの みちも のこそう。');}throw Error('pair route structure generation');
 }
 if(id==='mapcolor'){
  const n=phase<2?3:phase<4?4:5,k=[4,5,6,7,9][phase],colors=phase===0?4:3;
  for(let attempt=0;attempt<1000;attempt++){const seeds=shuffle(range(n*n)).slice(0,k),regions=range(n*n).map(i=>seeds.indexOf(i)),front=[...seeds];for(let t=0;t<front.length;t++)for(const j of shuffle(adjacent(front[t],n)))if(regions[j]<0){regions[j]=regions[front[t]];front.push(j);}const edges:number[][]=[];range(n*n).forEach(i=>adjacent(i,n).forEach(j=>{const e=[regions[i],regions[j]].sort((a,b)=>a-b);if(e[0]!==e[1]&&!edges.some(a=>equal(a,e)))edges.push(e);}));let triangles=0;for(let a=0;a<k;a++)for(let b=a+1;b<k;b++)for(let d=b+1;d<k;d++)if([[a,b],[a,d],[b,d]].every(e=>edges.some(v=>equal(e,v))))triangles++;if(phase>=2&&triangles<phase-1)continue;const solution=range(k).map(()=>-1);function solve(i:number):boolean{if(i===k)return true;for(let col=0;col<colors;col++)if(edges.filter(e=>e.includes(i)).every(e=>solution[e.find(j=>j!==i)!]!==col)){solution[i]=col;if(solve(i+1))return true;}solution[i]=-1;return false;}if(!solve(0))continue;const order=range(k).sort((a,b)=>edges.filter(e=>e.includes(b)).length-edges.filter(e=>e.includes(a)).length),fixed=phase<3?[order[0],edges.find(e=>e.includes(order[0]))!.find(v=>v!==order[0])!]:[order[0]],initial=solution.map((v,i)=>fixed.includes(i)?v:-1);return base('region-color',{n,regions,edges,k,initial,colors,concept:phase},solution,phase<2?'となりの いろを みて、つかえる いろを えらぼう。':'3つが たがいに となりあう ところから、いろを きめよう。');}throw Error('color structure generation');
 }
 if(id==='inside'){
  const templates=[[[0,0],[6,0],[6,6],[0,6]],[[0,0],[6,0],[6,2],[3,2],[3,6],[0,6]],[[0,0],[6,0],[6,6],[4,6],[4,2],[2,2],[2,6],[0,6]],[[0,0],[6,0],[6,2],[4,2],[4,4],[6,4],[6,6],[0,6],[0,4],[2,4],[2,2],[0,2]],[[0,0],[6,1],[5,6],[3,4],[1,6],[2,3],[0,4]]],q=int(0,3),mirror=int(0,1),poly=templates[phase].map(([x,y])=>{if(mirror)x=6-x;for(let i=0;i<q;i++)[x,y]=[6-y,x];return[x,y];}),all=range(225).map(i=>[i%15*.5-.5,Math.floor(i/15)*.5-.5]).filter(p=>poly.every((a,i)=>{const b=poly[(i+1)%poly.length],vx=b[0]-a[0],vy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*vx+(p[1]-a[1])*vy)/(vx*vx+vy*vy)));return Math.hypot(p[0]-a[0]-t*vx,p[1]-a[1]-t*vy)>.13;})),inside=shuffle(all.filter(p=>pointInside(p,poly))),outside=shuffle(all.filter(p=>!pointInside(p,poly))),hull=hullIndices(poly).map(i=>poly[i]),notches=outside.filter(p=>pointInside(p,hull)),chosen=[...inside.slice(0,2+phase),...outside.slice(0,2)];if(phase>0)chosen.push(...notches.slice(0,1+Math.floor(phase/2)));const points=shuffle([...new Map([...chosen,...shuffle(all).slice(0,4+Math.floor(step/2))].map(p=>[key(p),p])).values()]),solution=range(points.length).filter(i=>pointInside(points[i],poly));return base('point-select',{poly,points,n:7,scene:{type:'points',points,poly},concept:phase},solution,phase<2?'へんを こえて そとへ でるか、よく みよう。':'へこみや ななめの へんに ちかい てんを、1つずつ たしかめよう。');
 }
 if(id==='jigsaw'){
  const n=phase<2?2:3,raw=range(n*n).map(()=>[0,0,0,0]),labelCount=[9,4,8,4,2][phase];for(let i=0;i<n*n;i++){if(i%n<n-1){const v=int(1,labelCount)*(phase>=1&&int(0,1)?-1:1);raw[i][1]=v;raw[i+1][3]=-v;}if(i<n*(n-1)){const v=int(1,labelCount)*(phase>=1&&int(0,1)?-1:1);raw[i][2]=v;raw[i+n][0]=-v;}}const order=shuffle(range(n*n)),qs=range(n*n).map(()=>L===1?0:int(0,3)),tiles=order.map((i,j)=>tileEdges(raw[i],qs[j])),solution={slots:range(n*n).map(i=>order.indexOf(i)),turns:qs.map(q=>(4-q)%4)};return base('jigsaw',{n,tiles,initial:{slots:range(n*n).map(()=>-1),turns:range(n*n).map(()=>0)},concept:phase},solution,phase<2?'0を そとへ むけて、となりの ＋と−を あわせよう。':'おなじ すうじが あっても、ほかの へんと ＋−まで たしかめよう。');
 }
 if(id==='mirrorbeam'){
  const n=phase<1?3:phase<3?4:5,count=[4,6,7,9,10][phase],required=phase+1;
  for(let attempt=0;attempt<3000;attempt++){
   const row=int(0,n-1),mirrors=shuffle(range(n*n)).slice(0,count),states=range(2**count).map(mask=>range(count).map(i=>(mask>>i)&1)),traces=states.map(a=>beamTrace(n,mirrors,a,row));
   const targets=shuffle(range(states.length).filter(i=>traces[i].exit&&traces[i].cells.filter(at=>mirrors.includes(at)).length>=required+1));
   for(const targetIndex of targets.slice(0,16)){const target=traces[targetIndex].exit,goals=range(states.length).filter(i=>equal(traces[i].exit,target)),candidates=shuffle(range(states.length)).filter(i=>goals.every(g=>states[g].filter((v,j)=>v!==states[i][j]).length>=required));if(!candidates.length)continue;const at=candidates[0],distances=goals.map(g=>states[g].filter((v,j)=>v!==states[at][j]).length),minimum=Math.min(...distances),best=goals[distances.indexOf(minimum)];return base('mirrors',{n,row,mirrors,target,initial:states[at],minimum,concept:phase},states[best],'でぐちからも ひかりの みちを たどって、ひつような かがみを きめよう。');}
  }throw Error('mirror challenge generation failed');
 }
 if(id==='scale'){
  const cells=phase<2?shape(4+phase+int(0,2)+Math.floor(step/2)):phase===2?planeShape(c,1,8):planeShape(c,2,12),factor=phase<2?2:phase===2?3:phase===3?2:3,n=Math.max(...cells.flat())+1,expand=(kx:number,ky:number)=>cells.flatMap(([x,y])=>range(kx*ky).map(i=>[x*kx+i%kx,y*ky+Math.floor(i/kx)])),answer=expand(factor,factor),sc=(v:number[][])=>sceneShape(v,{extent:n*factor,grid:true}),wrong:number[][][]=[];
  if(phase<2)wrong.push(expand(1,factor),expand(factor,1));else{wrong.push(expand(factor-1,factor+1));const mirrored=normalize(answer.map(([x,y])=>[-x,y]));if(!equal(mirrored,normalize(answer)))wrong.push(mirrored);}
  for(let attempt=0;wrong.length<3&&attempt<100;attempt++){const v=answer.map(p=>[...p]),removed=int(0,v.length-1);v.splice(removed,1);const empty=shuffle(range(n*n*factor*factor).map(i=>[i%(n*factor),Math.floor(i/(n*factor))])).find(p=>!answer.some(q=>equal(p,q)));if(empty)v.push(empty);v.sort((a,b)=>key(a).localeCompare(key(b)));if(!wrong.some(a=>equal(a,v)))wrong.push(v);}return choice(sc(answer),wrong.map(sc),{type:'scale',cells,factor,n},'へこんだ ところや あなの はばも、おなじ ばいに なるよ。',{cells,factor,concept:phase});
 }
 if(id==='separator'){
  const anchors=range(16).map(i=>i<4?[i*1.5,0]:i<8?[6,(i-4)*1.5]:i<12?[6-(i-8)*1.5,6]:[0,6-(i-12)*1.5]),all=range(36).map(i=>[(i%6)+.5,Math.floor(i/6)+.5]),count=2+Math.floor(phase/2)+Number(step>=2),lines=shuffle(range(16).flatMap(a=>range(16-a-1).map(i=>[a,a+i+1])));
  for(const solution of lines){const[a,b]=solution.map(i=>anchors[i]),axis=a[0]===b[0]||a[1]===b[1];if(phase===0&&!axis||phase>=1&&axis)continue;const margin=phase<2?.55:.18,negative=shuffle(all.filter(p=>cross(a,b,p)<0&&planeLineDistance(p,a,b)>=margin)),positive=shuffle(all.filter(p=>cross(a,b,p)>0&&planeLineDistance(p,a,b)>=margin));if(negative.length<count||positive.length<count)continue;
   for(let attempt=0;attempt<40;attempt++){let aa=shuffle(negative).slice(0,count),bb=shuffle(positive).slice(0,count);if(phase>=3){aa[0]=[...negative].sort((p,q)=>planeLineDistance(p,a,b)-planeLineDistance(q,a,b))[0];bb[0]=[...positive].sort((p,q)=>planeLineDistance(p,a,b)-planeLineDistance(q,a,b))[0];if(new Set(aa.map(key)).size<count||new Set(bb.map(key)).size<count)continue;}const overlap=(axis:number)=>Math.min(Math.max(...aa.map(p=>p[axis])),Math.max(...bb.map(p=>p[axis])))>=Math.max(Math.min(...aa.map(p=>p[axis])),Math.min(...bb.map(p=>p[axis])));if(phase>=2&&(!overlap(0)||!overlap(1)))continue;const points=[...aa,...bb],groups=points.map((_,i)=>i<aa.length?0:1);return base('separator',{anchors,points,groups,n:6,initial:[],concept:phase},solution,phase<2?'まると ほしの あいだを とおる せんを さがそう。':'ななめの すきまを みつけて、すべての てんが わかれるか たしかめよう。');}
  }throw Error('separator structure generation');
 }
 if(id==='hull'){
  for(let attempt=0;attempt<1000;attempt++){const core=phase===0?(step<2?[[1,1],[7,1],[7,7],[1,7]]:[[1,1],[7,int(0,2)],[int(6,8),7],[int(0,2),int(6,8)]]):shuffle(range(81)).slice(0,6+Math.floor(phase/2)).map(i=>[i%9,Math.floor(i/9)]),hull=hullIndices(core).map(i=>core[i]);if(hull.length<(phase>=3?5:4))continue;const pool=range(81).map(i=>[i%9,Math.floor(i/9)]).filter(p=>!hull.some(q=>equal(p,q))),boundary=pool.filter(p=>hull.some((a,i)=>{const b=hull[(i+1)%hull.length];return cross(a,b,p)===0&&p[0]>=Math.min(a[0],b[0])&&p[0]<=Math.max(a[0],b[0])&&p[1]>=Math.min(a[1],b[1])&&p[1]<=Math.max(a[1],b[1]);})),inner=pool.filter(p=>pointInside(p,hull)&&!boundary.some(q=>equal(p,q))),near=inner.filter(p=>Math.min(...hull.map((a,i)=>planeLineDistance(p,a,hull[(i+1)%hull.length])))<=.8),deep=inner.filter(p=>!near.some(q=>equal(p,q)));if(phase>=2&&!boundary.length||phase>=3&&near.length<2||!deep.length)continue;const wanted=[...hull,...shuffle(deep).slice(0,1+Math.floor(step/2)),...(phase>=2?shuffle(boundary).slice(0,phase===4?2:1):[]),...(phase>=3?shuffle(near).slice(0,2+Number(step>=2)):[])],points=shuffle([...new Map(wanted.map(p=>[key(p),p])).values()]),solution=hullIndices(points);return base('point-select',{points,n:9,scene:{type:'points',points},concept:phase},solution,phase<2?'いちばん そとの かどを つなごう。':'へんの とちゅうの てんと、へんに ちかい なかの てんは、かどでは ないよ。');}throw Error('hull structure generation');
 }
 if(id==='parallel'){
  const references=[[[1,0],[0,1]],[[1,1],[1,-1]],[[1,2],[2,1],[2,-1]],[[2,3],[3,2],[3,-2]],[[3,4],[4,3],[3,5],[5,-3]]],vector=pick(references[phase]),all=[[1,0],[0,1],[1,1],[1,-1],[1,2],[2,1],[2,-1],[2,3],[3,2],[3,-2],[3,4],[4,3],[3,5],[5,-3]],angle=(v:number[])=>Math.acos(Math.min(1,Math.abs(v[0]*vector[0]+v[1]*vector[1])/(Math.hypot(...v)*Math.hypot(...vector))))*180/Math.PI,wrong=shuffle(all.filter(v=>v[0]*vector[1]!==v[1]*vector[0]&&angle(v)>=(phase>=3?5:15))).sort((a,b)=>phase>=2?angle(a)-angle(b):0),count=5+phase+Number(step>=2),targets=2+Number(step>=2),vectors=shuffle([...range(targets).map(()=>{const scale=pick(phase===0?[1,2]:[1,2,-1]);return vector.map(v=>v*scale);}),...(phase>=2?[wrong[0],...shuffle(wrong.slice(1)).slice(0,count-targets-1)]:shuffle(wrong).slice(0,count-targets))]),solution=range(vectors.length).filter(i=>vectors[i][0]*vector[1]===vectors[i][1]*vector[0]);return base('card-select',{cards:vectors.map(vector=>({type:'segment',vector,length:int(23,35),offset:[int(-6,6),int(-6,6)]})),vector,scene:{type:'segment',vector,label:'おてほん'},concept:phase},solution,phase<2?'ながさや ばしょではなく、せんの むきを くらべよう。':'よこに いくつで、たてに いくつ すすむかを くらべよう。');
 }
 if(id==='coinparking'){
  const radius=phase<2?1.05:1.1,k=[2,3,4,5,6][phase],n=10;
  if(phase>=2){for(let attempt=0;attempt<1000;attempt++){const radiusRing=phase===2?2.65:phase===3?3.05:3.15,offset=c.r()*Math.PI*2,planted=range(k).map(i=>[5+radiusRing*Math.cos(offset+i*2*Math.PI/k),5+radiusRing*Math.sin(offset+i*2*Math.PI/k)]),decoys=range(k).map(i=>planted[i].map((v,j)=>(v+planted[(i+1)%k][j])/2)),extras=range(phase-1).map(()=>{const v=pick(decoys),angle=c.r()*Math.PI*2;return[v[0]+.65*Math.cos(angle),v[1]+.65*Math.sin(angle)];}),raw=[...planted,...decoys,...extras].map(p=>p.map(v=>Math.round(v*10)/10));if(raw.some(p=>p.some(v=>v<radius||v>n-radius))||raw.some((p,i)=>raw.slice(0,i).some(q=>Math.hypot(p[0]-q[0],p[1]-q[1])<.55)))continue;const graph=planeParkingGraph(raw,radius,k);if(graph.maximum!==k||graph.masks.some(m=>!m))continue;const points=shuffle(raw),solution=range(points.length).filter(i=>raw.slice(0,k).some(v=>equal(v,points[i])));return base('parking',{points,radius,k,n,initial:[],concept:phase},solution,'1つ おくと、どの てんが つかえなくなるか。のこりも みて えらぼう。');}throw Error('parking constraint generation');}
  const planted:number[][]=[];for(let tries=0;planted.length<k&&tries<2000;tries++){const v=[int(15,85)/10,int(15,85)/10];if(planted.every(p=>Math.hypot(p[0]-v[0],p[1]-v[1])>=radius*2+.5))planted.push(v);}const decoys:number[][]=[];for(let tries=0;decoys.length<k+1&&tries<1000;tries++){const source=pick(planted),angle=c.r()*Math.PI*2,dist=radius*(.9+c.r()*.6),v=source.map((x,i)=>Math.round((x+dist*(i?Math.sin(angle):Math.cos(angle)))*10)/10);if(v.every(x=>x>=radius&&x<=n-radius)&&[...planted,...decoys].every(p=>Math.hypot(p[0]-v[0],p[1]-v[1])>.65))decoys.push(v);}const points=shuffle([...planted,...decoys]),solution=range(points.length).filter(i=>planted.some(v=>equal(v,points[i])));return base('parking',{points,radius,k,n,initial:[],concept:phase},solution,'えんが かさならない てんの くみあわせを さがそう。');
 }
}
export function checkPlane(p:Puzzle,a:any):boolean{
 if(a===null||a===undefined)return false;const d=p.data,id=p.id;if(p.kind==='visual-choice')return Number.isInteger(a)&&a===p.solution;
 if(p.kind==='tiling'){if(!Array.isArray(a)||a.length!==d.pieces.length||new Set(a.map(v=>v.piece)).size!==d.pieces.length)return false;const used=new Set<string>();for(const v of a){if(!Number.isInteger(v.piece)||!d.pieces[v.piece]||![v.x,v.y,v.q].every(Number.isInteger)||v.q<0||v.q>3)return false;for(const[x,y]of rotate(d.pieces[v.piece],v.q)){const xx=x+v.x,yy=y+v.y,k=key([xx,yy]);if(xx<0||yy<0||xx>=d.n||yy>=d.rows||used.has(k))return false;used.add(k);}}return used.size===d.n*d.rows;}
 if(p.kind==='district'){if(!Array.isArray(a)||a.length!==d.n*d.rows||a.some(v=>!Number.isInteger(v)||v<0||v>=d.k))return false;return range(d.k).every(v=>{const cells=range(a.length).filter(i=>a[i]===v);return cells.length===a.length/d.k&&d.homes.filter((at:number)=>a[at]===v).length===1&&a[d.homes[v]]===v&&connected(cells.map(i=>[i%d.n,Math.floor(i/d.n)]));});}
 if(p.kind==='fold-grid')return Array.isArray(a)&&equal(a,p.solution);
 if(p.kind==='chords'){if(!Array.isArray(a)||a.length!==d.n-3)return false;const edges=a.map(v=>Array.isArray(v)?sorted(v):[]);if(edges.some(e=>e.length!==2||e.some(v=>!Number.isInteger(v)||v<0||v>=d.n)||e[1]-e[0]<=1||e[0]===0&&e[1]===d.n-1||d.banned.some((b:number[])=>equal(b,e)))||new Set(edges.map(key)).size!==edges.length)return false;return edges.every(([a,b],i)=>edges.every(([c,e],j)=>i===j||!((a<c&&c<b&&b<e)||(c<a&&a<e&&e<b))));}
 if(p.kind==='pairpaths'){if(!Array.isArray(a)||a.length!==d.pairs.length||a.some(v=>!Array.isArray(v)))return false;const flat=a.flat();return flat.length===d.n*d.n&&new Set(flat).size===flat.length&&a.every((path,i)=>path[0]===d.pairs[i][0]&&path.at(-1)===d.pairs[i][1]&&path.every((v:number,j:number)=>Number.isInteger(v)&&v>=0&&v<d.n*d.n&&(j===0||adjacent(path[j-1],d.n).includes(v))));}
 if(p.kind==='region-color')return Array.isArray(a)&&a.length===d.k&&a.every((v,i)=>Number.isInteger(v)&&v>=0&&v<(d.colors??4)&&(d.initial[i]<0||v===d.initial[i]))&&d.edges.every(([u,v]:number[])=>a[u]!==a[v]);
 if(p.kind==='point-select'||p.kind==='card-select')return Array.isArray(a)&&new Set(a).size===a.length&&equal(sorted(a),sorted(p.solution));
 if(p.kind==='jigsaw'){if(!a||!Array.isArray(a.slots)||!Array.isArray(a.turns)||a.slots.length!==d.n*d.n||a.turns.length!==d.tiles.length||new Set(a.slots).size!==d.tiles.length||a.slots.some((v:any)=>!Number.isInteger(v)||!d.tiles[v])||a.turns.some((v:any)=>!Number.isInteger(v)||v<0||v>3))return false;const tiles=a.slots.map((i:number)=>tileEdges(d.tiles[i],a.turns[i]));return tiles.every((e:number[],i:number)=>(i<d.n?e[0]===0:e[0]+tiles[i-d.n][2]===0)&&(i%d.n===d.n-1?e[1]===0:e[1]+tiles[i+1][3]===0)&&(i>=d.n*(d.n-1)?e[2]===0:true)&&(i%d.n===0?e[3]===0:true));}
 if(p.kind==='mirrors')return Array.isArray(a)&&a.length===d.mirrors.length&&a.every(v=>v===0||v===1)&&equal(beamTrace(d.n,d.mirrors,a,d.row).exit,d.target);
 if(p.kind==='separator'){if(!Array.isArray(a)||a.length!==2||a[0]===a[1]||a.some(v=>!Number.isInteger(v)||!d.anchors[v]))return false;const signs=d.points.map((v:number[])=>Math.sign(cross(d.anchors[a[0]],d.anchors[a[1]],v)));return signs.every((v:number,i:number)=>v!==0&&v===(d.groups[i]===d.groups[0]?signs[0]:-signs[0]));}
 if(p.kind==='parking'){if(!Array.isArray(a)||a.length!==d.k||new Set(a).size!==a.length||a.some(v=>!Number.isInteger(v)||!d.points[v]))return false;return a.every((v,i)=>{const[x,y]=d.points[v];return x>=d.radius&&y>=d.radius&&x<=d.n-d.radius&&y<=d.n-d.radius&&a.slice(0,i).every(w=>{const[xx,yy]=d.points[w];return(x-xx)**2+(y-yy)**2>=4*d.radius**2;});});}
 return false;
}
