import{PANCAKE_BANK}from'./pancake-bank.ts';
import{TRAIN_BANK}from'./train-bank.ts';
import{TRAFFIC_BANK}from'./traffic-bank.ts';
import{context,range,key,equal,adjacent,type Puzzle,type Meta}from'./shared.ts';
export const TRIAL_META:Meta[]=[
['sokoban','はこを おとどけ','trial','はこを ほしまで おそう','矢印で移動し、箱を星まで押します。箱は引けず、一度に1つだけ押せます。困ったら一手戻しましょう。'],
['hanoi','リングの おひっこし','trial','リングを ほしの ぼうへ','棒を2本順に選んで、一番上のリングを移します。大きいリングは小さいリングの上には置けません。'],
['river','なかよく かわわたり','trial','みんなを むこうぎしへ','乗せる仲間を選んで川を渡ります。⚡で結ばれた2人は、船頭がいない岸に一緒に残せません。空の船で戻ることもできます。'],
['jugs','みずの はかりかた','trial','おてほんの りょうに しよう','満杯にする・空にする・ほかへ注ぐ、だけで量を合わせます。注ぐと、相手が満杯か元が空になるまで移ります。'],
['pegs','ぴょんと ひとつ','trial','さいごの ひとつに しよう','丸を選んで、隣の丸を飛び越し2マス先の空きへ。飛び越した丸が消えます。縦か横にだけ跳べます。'],
['frogs','カエルの いれかえ','trial','ふたつの チームを いれかえよう','矢印の向きに1マス進むか、相手のカエル1匹を飛び越します。後ろへは戻れません。空きマスにだけ進めます。'],
['pancake','ぱたんと タワー','trial','ちいさい じゅんに ならべよう','区切りを押すと、上からそこまでが裏返ります。上から小さい順に並べましょう。'],
['traffic','でぐちを あけて','trial','1ばんの くるまを でぐちへ','車を選んで矢印で動かします。車は向いている方向にだけ動きます。1番の車を右の出口へ届けましょう。'],
['colorsort','いろいろ ボトル','trial','おなじ しるしを あつめよう','元のボトルと行き先を順に選び、一番上の玉を1つ移します。空のボトルか、同じしるしの上に置けます。各ボトルを空か同じしるしで満杯にします。'],
['trainyard','れっしゃの ならびかえ','trial','1から じゅんに しゅっぱつ','入口の先頭を待避線へ、または次の番号なら出口へ送ります。待避線は最後に入れた車両から出せます。'],
['programbot','ロボットに おねがい','trial','めいれいを ならべて ゴールへ','↑は前進、↶・↷はその場で回転。命令を並べて「うごかす」を押します。星のマスで、指定の矢印の向きに止まるとゴールです。数字付きの前進は、その回数だけ繰り返します。'],
['keydoors','カギを さがして','trial','カギを とって ドアの さきへ','同じ番号の鍵を取ると扉が通れます。鍵はなくなりません。矢印で動いて星まで進みましょう。'],
['twobots','ふたりで おさんぽ','trial','ふたりを おなじ しるしへ','一つの矢印で2人が同時に動きます。壁に当たる方は止まります。同じ場所へ入ろうとしたり、入れ替わろうとすると2人とも止まります。'],
['matchsticks','マッチの けいさん','trial','マッチを うごかして なおそう','ついている線と空いている線を順に選び、マッチを移します。＋と＝は動かせません。指定の手数以内で正しい式にしましょう。'],
['bridge','あかりを わたそう','trial','みんなで はしを わたろう','明かりのある岸から1人か2人で渡ります。かかる時間は遅い人の数字。明かりも一緒に動きます。合計を目標以内にします。'],
['ballweigh','かるい たまは？','trial','はかって ひとつに しぼろう','1つだけ軽い玉があります。左右に同じ個数を乗せて比べます。残りの候補が1つになるまで調べ、その玉を選びます。当てずっぽうでは正解になりません。'],
['codebreak','ひみつの カギ','trial','しるしの ならびを あてよう','並びを作って調べます。◎はしるしも場所も正解、△はしるしだけ正解。同じしるしを複数使う問題もあります。何度でも試せます。'],
['flood','いろの しまを ひろげよう','trial','ぜんぶ ひとつの しまに','左上からつながる島の色を変えます。隣の同じ色を取り込み、決められた手数以内に全部を一つにします。'],
];
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x)),sort=(a:number[])=>[...a].sort((a,b)=>a-b);
export const SEGMENTS=[0b1111110,0b0110000,0b1101101,0b1111001,0b0110011,0b1011011,0b1011111,0b1110000,0b1111111,0b1111011];
export function codeFeedback(secret:number[],guess:number[]){const exact=secret.filter((v,i)=>v===guess[i]).length,types=new Set([...secret,...guess]);let total=0;for(const t of types)total+=Math.min(secret.filter(v=>v===t).length,guess.filter(v=>v===t).length);return{exact,near:total-exact};}
export function directed(at:number,dir:number,n:number,rows=n){if(!Number.isInteger(dir)||dir<0||dir>3)return-1;const x=at%n+[0,1,0,-1][dir],y=Math.floor(at/n)+[-1,0,1,0][dir];return x<0||y<0||x>=n||y>=rows?-1:y*n+x;}
export function floodGrow(d:any,mask:number,color:number){let out=mask;for(let k=0;k<d.colors.length;k++){const prev=out;d.edges.forEach(([a,b]:number[])=>{if((out&(1<<a))&&d.colors[b]===color)out|=1<<b;if((out&(1<<b))&&d.colors[a]===color)out|=1<<a;});if(out===prev)break;}return out;}
export function trialStep(p:Pick<Puzzle,'id'|'data'>,state:any,action:any):any|null{
 const d=p.data,id=p.id;if(action===null||action===undefined)return null;
 if(id==='sokoban'){if(typeof action!=='number')return null;const next=directed(state.pos,action,d.n);if(next<0||d.walls.includes(next))return null;const boxes=[...state.boxes],i=boxes.indexOf(next);if(i>=0){const beyond=directed(next,action,d.n);if(beyond<0||d.walls.includes(beyond)||boxes.includes(beyond))return null;boxes[i]=beyond;}return{pos:next,boxes:sort(boxes)};}
 if(id==='hanoi'){const{from,to}=action;if(!Number.isInteger(from)||!Number.isInteger(to)||from<0||from>2||to<0||to>2||from===to)return null;const disk=state.indexOf(from),top=state.indexOf(to);if(disk<0||top>=0&&top<disk)return null;const a=[...state];a[disk]=to;return a;}
 if(id==='river'||id==='bridge'){const riders=action.riders;if(!Array.isArray(riders)||new Set(riders).size!==riders.length||riders.length>(id==='river'?d.capacity:2)||id==='bridge'&&!riders.length||riders.some((v:number)=>!Number.isInteger(v)||v<0||v>=d.n||state.banks[v]!==state.boat))return null;const banks=[...state.banks],boat=1-state.boat;riders.forEach((v:number)=>banks[v]=boat);if(id==='river'&&d.conflicts.some(([a,b]:number[])=>banks[a]===banks[b]&&banks[a]!==boat))return null;return id==='river'?{banks,boat}:{banks,boat,time:state.time+Math.max(...riders.map((v:number)=>d.times[v]))};}
 if(id==='jugs'){const{type,from,to}=action;if(!Number.isInteger(from)||from<0||from>=d.caps.length)return null;const a=[...state];if(type==='fill')a[from]=d.caps[from];else if(type==='empty')a[from]=0;else if(type==='pour'&&Number.isInteger(to)&&to>=0&&to<d.caps.length&&from!==to){const q=Math.min(a[from],d.caps[to]-a[to]);a[from]-=q;a[to]+=q;}else return null;return equal(a,state)?null:a;}
 if(id==='pegs'){const{from,to}=action;if(!Number.isInteger(from)||!Number.isInteger(to)||from<0||to<0||from>=d.n*d.n||to>=d.n*d.n)return null;const x=from%d.n,y=Math.floor(from/d.n),xx=to%d.n,yy=Math.floor(to/d.n);if(!((x===xx&&Math.abs(y-yy)===2)||(y===yy&&Math.abs(x-xx)===2)))return null;const mid=(from+to)/2;if(!state.includes(from)||!state.includes(mid)||state.includes(to))return null;return sort([...state.filter((i:number)=>i!==from&&i!==mid),to]);}
 if(id==='frogs'){if(!Number.isInteger(action)||action<0||action>=state.length||!state[action])return null;const empty=state.indexOf(0),dir=state[action],delta=empty-action;if(delta!==dir&&!(delta===2*dir&&state[action+dir]===-dir))return null;const a=[...state];a[empty]=dir;a[action]=0;return a;}
 if(id==='pancake'){if(!Number.isInteger(action)||action<2||action>state.length)return null;return[...state.slice(0,action).reverse(),...state.slice(action)];}
 if(id==='traffic'){const{car,delta}=action;if(!Number.isInteger(car)||!d.cars[car]||!Number.isInteger(delta)||Math.abs(delta)!==1)return null;const cfg=d.cars[car],pos=state[car]+delta;if(pos<0||pos+cfg.len>d.n)return null;const occupied=new Set<number>();d.cars.forEach((c:any,i:number)=>{if(i!==car)range(c.len).forEach(k=>occupied.add(c.axis==='h'?c.lane*d.n+state[i]+k:(state[i]+k)*d.n+c.lane));});if(range(cfg.len).some(k=>occupied.has(cfg.axis==='h'?cfg.lane*d.n+pos+k:(pos+k)*d.n+cfg.lane)))return null;const a=[...state];a[car]=pos;return a;}
 if(id==='colorsort'){const{from,to}=action;if(!Number.isInteger(from)||!Number.isInteger(to)||from===to||!state[from]?.length||!state[to]||state[to].length>=d.capacity)return null;const color=state[from].at(-1);if(state[to].length&&state[to].at(-1)!==color)return null;const a=clone(state);a[from].pop();a[to].push(color);return a;}
 if(id==='trainyard'){const{from,to}=action,a=clone(state);let v:number;if(from==='in'){if(!a.input.length)return null;v=a.input[0];}else if(Number.isInteger(from)&&a.sidings[from]?.length)v=a.sidings[from].at(-1);else return null;if(to==='out'){if(v!==a.output.length+1)return null;a.output.push(v);}else if(Number.isInteger(to)&&a.sidings[to]&&a.sidings[to].length<d.capacity&&from!==to)a.sidings[to].push(v);else return null;if(from==='in')a.input.shift();else a.sidings[from].pop();return a;}
 if(id==='programbot'){if(!(d.allowed??['F','L','R','F2','F3']).includes(action)||state.used>=d.budget)return null;const a={...state,used:state.used+1};if(action==='L')a.dir=(a.dir+3)%4;else if(action==='R')a.dir=(a.dir+1)%4;else for(let k=0;k<(action==='F'?1:Number(action[1]));k++){const next=directed(a.pos,a.dir,d.n);if(next<0||d.walls.includes(next))return null;a.pos=next;}return a;}
 if(id==='keydoors'){if(typeof action!=='number')return null;const next=directed(state.pos,action,d.n);if(next<0||d.walls.includes(next))return null;const door=d.doors.findIndex((at:number)=>at===next);if(door>=0&&!(state.keys&(1<<door)))return null;const found=d.keys.indexOf(next);return{pos:next,keys:found>=0?state.keys|(1<<found):state.keys};}
 if(id==='twobots'){if(typeof action!=='number')return null;const positions=state.positions.map((at:number)=>{const next=directed(at,action,d.n);return next<0||d.walls.includes(next)?at:next;});if(positions[0]===positions[1]||positions[0]===state.positions[1]&&positions[1]===state.positions[0])return null;return equal(positions,state.positions)?null:{positions};}
 if(id==='matchsticks'){const{from,to}=action,total=state.masks.length*7;if(!Number.isInteger(from)||!Number.isInteger(to)||from<0||to<0||from>=total||to>=total||from===to||state.used>=d.maxMoves)return null;const fi=Math.floor(from/7),ti=Math.floor(to/7),fb=1<<(6-from%7),tb=1<<(6-to%7);if(!(state.masks[fi]&fb)||(state.masks[ti]&tb))return null;const masks=[...state.masks];masks[fi]^=fb;masks[ti]^=tb;return{masks,used:state.used+1};}
 if(id==='ballweigh'){if(action.guess!==undefined){if(state.candidates.length!==1||action.guess!==state.candidates[0])return null;return{...state,guess:action.guess};}const{left,right}=action;if(!Array.isArray(left)||!Array.isArray(right)||!left.length||left.length!==right.length||new Set([...left,...right]).size!==left.length+right.length||[...left,...right].some(v=>!Number.isInteger(v)||v<0||v>=d.n)||state.observations.length>=d.budget)return null;const outcome=(culprit:number)=>left.includes(culprit)?-1:right.includes(culprit)?1:0,result=outcome(d.culprit);return{...state,candidates:state.candidates.filter((v:number)=>outcome(v)===result),observations:[...state.observations,{left,right,result}]};}
 if(id==='codebreak'){if(!Array.isArray(action)||action.length!==d.length||action.some(v=>!Number.isInteger(v)||v<0||v>=d.alphabet)||!d.repeats&&new Set(action).size!==action.length)return null;return{history:[...state.history,{guess:action, ...codeFeedback(d.secret,action)}]};}
 if(id==='flood'){if(!Number.isInteger(action)||action<0||action>=d.palette||action===state.color||state.used>=d.budget)return null;const mask=floodGrow(d,state.mask,action);return{mask,color:action,used:state.used+1};}
 return null;
}
export function trialGoal(p:Pick<Puzzle,'id'|'data'>,s:any){const d=p.data;switch(p.id){case'sokoban':return equal(sort(s.boxes),sort(d.goals));case'hanoi':return s.every((v:number)=>v===(d.goalPeg??2));case'river':return s.banks.every((v:number)=>v===1);case'jugs':return equal(s,d.target);case'pegs':return s.length===1;case'frogs':return equal(s,d.target);case'pancake':return s.every((v:number,i:number)=>v===i+1);case'traffic':return s[0]===d.n-d.cars[0].len;case'colorsort':return s.every((b:number[])=>!b.length||b.length===d.capacity&&b.every(v=>v===b[0]));case'trainyard':return s.output.length===d.n;case'programbot':return s.pos===d.target.pos&&s.dir===d.target.dir&&s.used<=d.budget;case'keydoors':return s.pos===d.goal;case'twobots':return equal(s.positions,d.target);case'matchsticks':{const digits=s.masks.map((m:number)=>SEGMENTS.indexOf(m));if(digits.some((v:number)=>v<0)||s.used>d.maxMoves)return false;let at=0;const values=d.groups.map((len:number)=>{const ds=digits.slice(at,at+len);at+=len;return len>1&&ds[0]===0?-999:ds.reduce((a:number,b:number)=>a*10+b,0);});return values.every((v:number)=>v>=0)&&values[0]+values[1]===values[2];}case'bridge':return s.banks.every((v:number)=>v===1)&&s.time<=d.budget;case'ballweigh':return s.candidates.length===1&&s.guess===s.candidates[0];case'codebreak':return s.history.at(-1)?.exact===d.length;case'flood':return s.mask===(1<<d.colors.length)-1&&s.used<=d.budget;default:return false;}}
export function replayTrial(p:Pick<Puzzle,'id'|'data'>,actions:any[]){let state=clone(p.data.initial);for(const action of actions){const next=trialStep(p,state,action);if(next===null)return null;state=next;}return state;}
export function checkTrial(p:Puzzle,a:any){if(!Array.isArray(a)||a.length>2000)return false;const s=replayTrial(p,a);return s!==null&&trialGoal(p,s);}
type Entry={state:any;parent:number;action:any;depth:number};
function explore(initial:any,next:(s:any)=>{state:any;action:any}[],limit=20000,stateKey=(s:any)=>key(s),goal?:(s:any)=>boolean){const entries:Entry[]=[{state:initial,parent:-1,action:null,depth:0}],seen=new Set([stateKey(initial)]);for(let i=0;i<entries.length&&i<limit;i++){if(goal?.(entries[i].state))return{entries,found:i};for(const v of next(entries[i].state)){const k=stateKey(v.state);if(seen.has(k)||entries.length>=limit)continue;seen.add(k);entries.push({...v,parent:i,depth:entries[i].depth+1});}}return{entries,found:-1};}
function path(entries:Entry[],at:number){const actions:any[]=[];for(let i=at;entries[i].parent>=0;i=entries[i].parent)actions.push(entries[i].action);return actions.reverse();}
const graphCache=new Map<string,Entry[]>();
function pushLowerBound(boxes:number[],goals:number[],n:number):number{if(!boxes.length)return 0;return Math.min(...goals.map((g,i)=>Math.abs(boxes[0]%n-g%n)+Math.abs(Math.floor(boxes[0]/n)-Math.floor(g/n))+pushLowerBound(boxes.slice(1),goals.filter((_,j)=>j!==i),n)));}

// These searches measure the resulting task, rather than the length of a random scramble.
class MinQueue<T extends {priority:number}>{items:T[]=[];push(item:T){let at=this.items.length;this.items.push(item);while(at){const parent=(at-1)>>1;if(this.items[parent].priority<=item.priority)break;this.items[at]=this.items[parent];at=parent;}this.items[at]=item;}pop(){const first=this.items[0],last=this.items.pop()!;if(this.items.length){let at=0;while(at*2+1<this.items.length){let child=at*2+1;if(child+1<this.items.length&&this.items[child+1].priority<this.items[child].priority)child++;if(this.items[child].priority>=last.priority)break;this.items[at]=this.items[child];at=child;}this.items[at]=last;}return first;}}
function colorLowerBound(initial:number[][],colors:number){const kept=range(colors).map(()=>0);for(const b of initial){if(!b.length)continue;let prefix=1;while(prefix<b.length&&b[prefix]===b[0])prefix++;kept[b[0]]=Math.max(kept[b[0]],prefix);}return initial.reduce((n,b)=>n+b.length,0)-kept.reduce((a,b)=>a+b,0);}
function colorPlan(initial:number[][],capacity:number,colors:number){
 const canonical=(s:number[][])=>s.map(b=>b.join(',')).sort().join('|'),p={id:'colorsort',data:{capacity}},entries:{state:number[][];parent:number;action:any;cost:number}[]=[{state:initial,parent:-1,action:null,cost:0}],best=new Map([[canonical(initial),0]]),queue=new MinQueue<{at:number;priority:number}>();queue.push({at:0,priority:colorLowerBound(initial,colors)});
 for(let scanned=0;queue.items.length&&scanned<20000;scanned++){const{at}=queue.pop(),entry=entries[at],state=entry.state;if(best.get(canonical(state))!==entry.cost)continue;if(trialGoal(p,state)){const solution:any[]=[];for(let i=at;entries[i].parent>=0;i=entries[i].parent)solution.push(entries[i].action);return{minimum:entry.cost,solution:solution.reverse()};}
  for(let from=0;from<state.length;from++)for(let to=0;to<state.length;to++){const action={from,to},next=trialStep(p,state,action);if(next===null)continue;const k=canonical(next),cost=entry.cost+1;if(cost>=(best.get(k)??Infinity))continue;best.set(k,cost);entries.push({state:next,parent:at,action,cost});queue.push({at:entries.length-1,priority:cost+colorLowerBound(next,colors)});}
 }return null;
}
function sokobanPlan(d:any,limit=12000){
 const walls=new Set<number>(d.walls),goals=sort(d.goals),reach=(pos:number,boxes:number[])=>{const blocked=new Set([...walls,...boxes]),cells=[pos],parents=new Map<number,{from:number;dir:number}>([[pos,{from:-1,dir:-1}]]);for(let i=0;i<cells.length;i++)for(let dir=0;dir<4;dir++){const next=directed(cells[i],dir,d.n);if(next<0||blocked.has(next)||parents.has(next))continue;parents.set(next,{from:cells[i],dir});cells.push(next);}return{cells,parents};};
 const startReach=reach(d.initial.pos,d.initial.boxes),entries:any[]=[{state:d.initial,parent:-1,actions:[],cost:0}],best=new Map([[key([d.initial.boxes,Math.min(...startReach.cells)]),0]]),queue=new MinQueue<{at:number;priority:number}>();queue.push({at:0,priority:pushLowerBound(d.initial.boxes,goals,d.n)});
 for(let scanned=0;queue.items.length&&scanned<limit;scanned++){const{at}=queue.pop(),entry=entries[at],s=entry.state,walk=reach(s.pos,s.boxes),canonical=key([s.boxes,Math.min(...walk.cells)]);if(best.get(canonical)!==entry.cost)continue;
  if(equal(s.boxes,goals)){const parts:number[][]=[];for(let i=at;entries[i].parent>=0;i=entries[i].parent)parts.push(entries[i].actions);return{minimumPushes:entry.cost,solution:parts.reverse().flat()};}
  for(let box=0;box<s.boxes.length;box++)for(let dir=0;dir<4;dir++){const from=s.boxes[box],behind=directed(from,(dir+2)%4,d.n),to=directed(from,dir,d.n);if(to<0||!walk.parents.has(behind)||walls.has(to)||s.boxes.includes(to))continue;
   if(!goals.includes(to)){const stop=(direction:number)=>{const q=directed(to,direction,d.n);return q<0||walls.has(q);};if((stop(0)||stop(2))&&(stop(1)||stop(3)))continue;}
   const boxes=sort(s.boxes.map((v:number,i:number)=>i===box?to:v)),state={pos:from,boxes},nextReach=reach(from,boxes),k=key([boxes,Math.min(...nextReach.cells)]),cost=entry.cost+1;if(cost>=(best.get(k)??Infinity))continue;
   const actions:number[]=[];for(let cell=behind;walk.parents.get(cell)!.from>=0;cell=walk.parents.get(cell)!.from)actions.push(walk.parents.get(cell)!.dir);actions.reverse();actions.push(dir);best.set(k,cost);entries.push({state,parent:at,actions,cost});queue.push({at:entries.length-1,priority:cost+pushLowerBound(boxes,goals,d.n)});
  }
 }return null;
}
function pegMoves(state:number[],n:number){return state.flatMap(from=>range(4).flatMap(dir=>{const mid=directed(from,dir,n),to=mid<0?-1:directed(mid,dir,n);return to>=0&&state.includes(mid)&&!state.includes(to)?[{from,to}]:[];}));}
function traceFeatures(p:any,solution:any[]){let s=clone(p.data.initial),turns=0,wallStops=0,choices=0,pours=0;for(const action of solution){if(p.id==='programbot'&&(action==='L'||action==='R'))turns++;if(p.id==='jugs'&&action.type==='pour')pours++;if(p.id==='pegs'&&pegMoves(s,p.data.n).length>1)choices++;const next=trialStep(p,s,action);if(next===null)break;if(p.id==='twobots'&&s.positions.filter((v:number,i:number)=>v!==next.positions[i]).length===1)wallStops++;s=next;}return{turns,wallStops,choices,pours};}
function openProgramDistance(d:any,target:any){const p={id:'programbot',data:{...d,walls:[],budget:100}},q=[{state:d.initial,depth:0}],seen=new Set([key([d.initial.pos,d.initial.dir])]);for(let i=0;i<q.length;i++){const{state,depth}=q[i];if(state.pos===target.pos&&state.dir===target.dir)return depth;for(const command of d.allowed){const next=trialStep(p,state,command);if(next===null)continue;const k=key([next.pos,next.dir]);if(!seen.has(k)){seen.add(k);q.push({state:next,depth:depth+1});}}}return Infinity;}
function trafficDifficulty(p:any){let previous=new Map<number,number>(),reversals=0;for(const a of p.solution){if(previous.has(a.car)&&previous.get(a.car)!==a.delta)reversals++;previous.set(a.car,a.delta);}return p.minimum+2*p.blockerCount+new Set(p.solution.filter((a:any)=>a.car!==0).map((a:any)=>a.car)).size+2*reversals;}
function trainDifficulty(p:any){let blocks=0;for(const stack of p.initial.sidings)for(let i=0;i<stack.length;i++)for(let j=i+1;j<stack.length;j++)if(stack[i]<stack[j])blocks++;const transfers=p.solution.filter((a:any)=>Number.isInteger(a.from)&&Number.isInteger(a.to)).length;return 3*p.minimumExtraMoves+1.5*transfers+.5*blocks;}
const codePoolCache=new Map<string,number[][]>();
function codePool(length:number,alphabet:number,repeats:boolean){const k=key([length,alphabet,repeats]);let pool=codePoolCache.get(k);if(pool)return pool;pool=[];const append=(part:number[])=>{if(part.length===length){pool!.push(part);return;}for(let i=0;i<alphabet;i++)if(repeats||!part.includes(i))append([...part,i]);};append([]);codePoolCache.set(k,pool);return pool;}

const bitCounts=range(128).map(v=>{let n=0;while(v){n+=v&1;v>>>=1;}return n;});
const equationCache=new Map<string,number[][]>();
function equationTargets(groups:number[],total:number){const k=key([groups,total]);let found=equationCache.get(k);if(found)return found;found=[];const[wa,wb,wc]=groups;for(let a=wa===1?0:10**(wa-1);a<10**wa;a++)for(let b=wb===1?0:10**(wb-1);b<10**wb;b++){const sum=a+b;if(String(sum).length!==wc)continue;const masks=[...String(a),...String(b),...String(sum)].map(v=>SEGMENTS[Number(v)]);if(masks.reduce((s,m)=>s+bitCounts[m],0)===total)found.push(masks);}equationCache.set(k,found);return found;}
function minimumEquationMoves(groups:number[],masks:number[]){const targets=equationTargets(groups,masks.reduce((s,m)=>s+bitCounts[m],0));return Math.min(...targets.map(t=>t.reduce((s,m,i)=>s+bitCounts[m^masks[i]],0)/2));}
const trafficSchedules=new Map<number,typeof TRAFFIC_BANK>();
function trafficSchedule(band:number){let schedule=trafficSchedules.get(band);if(schedule)return schedule;const groups=new Map<string,typeof TRAFFIC_BANK>(),c=context('traffic-order',band,4107);for(const p of TRAFFIC_BANK.filter(p=>p.band===band)){const k=JSON.stringify(p.cars);if(!groups.has(k))groups.set(k,[]);groups.get(k)!.push(p);}const rows=c.shuffle([...groups.values()]).map(g=>c.shuffle(g));schedule=[];for(let i=0;rows.some(g=>g[i]);i++)for(const row of rows)if(row[i])schedule.push(row[i]);trafficSchedules.set(band,schedule);return schedule;}
const trafficLevelBanks=new Map<number,typeof TRAFFIC_BANK>();
const trainLevelBanks=new Map<number,typeof TRAIN_BANK>();
function rankedTrafficBank(level:number){let bank=trafficLevelBanks.get(level);if(bank)return bank;const band=Math.floor((level-1)/4)+1,ordered=trafficSchedule(band).map(entry=>({entry,score:trafficDifficulty(entry)})).sort((a,b)=>a.score-b.score).map(v=>v.entry);for(let part=0;part<4;part++)trafficLevelBanks.set((band-1)*4+part+1,ordered.slice(Math.floor(part*ordered.length/4),Math.floor((part+1)*ordered.length/4)));return trafficLevelBanks.get(level)!;}
function rankedTrainBank(level:number){let bank=trainLevelBanks.get(level);if(bank)return bank;const band=Math.floor((level-1)/4)+1,ordered=TRAIN_BANK.filter(p=>p.band===band).map(entry=>({entry,score:trainDifficulty(entry)})).sort((a,b)=>a.score-b.score).map(v=>v.entry);for(let part=0;part<4;part++)trainLevelBanks.set((band-1)*4+part+1,ordered.slice(Math.floor(part*ordered.length/4),Math.floor((part+1)*ordered.length/4)));return trainLevelBanks.get(level)!;}
const pancakeCandidates=new Map<string,{initial:number[];solution:number[];minimum:number}[]>();
function pancakeBank(n:number,floor:number){const k=`${n}:${floor}`;let entries=pancakeCandidates.get(k);if(entries)return entries;entries=[floor,floor+1].flatMap(depth=>(PANCAKE_BANK[n][depth]??'').split(' ').filter(Boolean).map(word=>{const [initial,solution]=word.split(':');return{initial:initial.split('').map(Number),solution:solution.split('').map(Number),minimum:depth};}));if(!entries.length)throw Error('pancake distance bank empty');pancakeCandidates.set(k,entries);return entries;}

export function generateTrial(id:string,level:number,seed:number):Puzzle|undefined{
 if(!TRIAL_META.some(m=>m[0]===id))return;const c=context(id,level,seed),{L,int,pick,shuffle,base}=c;
 const finish=(d:any,solution:any[],hint:string)=>base('trial',d,solution,hint);
 const neighbors=(p:any,actions:(s:any)=>any[])=>(s:any)=>actions(s).flatMap(action=>{const state=trialStep(p,s,action);return state===null?[]:[{state,action}];});
 if(id==='sokoban'){
  const n=L<9?5:L<17?6:7,k=L<5?1:L<12?2:3,lower=2+Math.floor((L-1)*.45);
  for(let attempt=0;attempt<700;attempt++){
   const goals=shuffle(range((n-2)**2).map(i=>(Math.floor(i/(n-2))+1)*n+i%(n-2)+1)).slice(0,k),walls=shuffle(range(n*n).filter(i=>!goals.includes(i))).slice(0,1+Math.floor((L-1)/3)),pos=pick(range(n*n).filter(i=>!walls.includes(i)&&!goals.includes(i)));let state={pos,boxes:sort(goals)},candidate:any=null;
   for(let step=0;step<70+L*5;step++){const moves:any[]=[];for(let dir=0;dir<4;dir++){const next=directed(state.pos,dir,n);if(next<0||walls.includes(next)||state.boxes.includes(next))continue;const behind=directed(state.pos,(dir+2)%4,n);moves.push({state:{pos:next,boxes:state.boxes},pull:false});if(state.boxes.includes(behind))moves.push({state:{pos:next,boxes:sort([...state.boxes.filter(v=>v!==behind),state.pos])},pull:true});}if(!moves.length)break;state=pick(int(0,3)<3&&moves.some(a=>a.pull)?moves.filter(a=>a.pull):moves).state;if(pushLowerBound(state.boxes,goals,n)>=lower&&state.boxes.every(v=>!goals.includes(v)))candidate=clone(state);}
   if(!candidate)continue;const d={n,walls,goals,initial:candidate},plan=sokobanPlan(d);if(!plan||plan.minimumPushes<lower)continue;return finish({...d,minimumPushes:plan.minimumPushes,assignmentLowerBound:pushLowerBound(candidate.boxes,goals,n)},plan.solution,'はこを おす まえに、じぶんが まわりこむ みちも のこそう。');
  }throw Error('sokoban measured challenge');
 }
 if(id==='pancake'){
  const floor=[2,2,3,3,3,4,4,4,5,5,5,5,6,6,6,7,7,7,8,8][L-1],n=L<4?4:L<8?5:L<12?6:L<17?7:8,entry=pick(pancakeBank(n,floor));return finish({n,goalPeg:2,initial:[...entry.initial],minimum:entry.minimum},[...entry.solution],'そろった まとまりを こわさず、いちばん おおきいものを したへ。');
 }
 if(id==='hanoi'){
  const floor=[2,3,4,5,6,7,9,11,13,15,17,19,21,24,27,31,34,38,42,46][L-1],n=Math.ceil(Math.log2(floor+1)),goalPeg=int(0,2),cacheKey=id+n+':'+goalPeg,solved=range(n).map(()=>goalPeg),d={n,goalPeg},p={id,data:d};
  let entries=graphCache.get(cacheKey);if(!entries){const actions=()=>range(3).flatMap(from=>range(3).filter(to=>to!==from).map(to=>({from,to})));entries=explore(solved,neighbors(p,actions),1000).entries;graphCache.set(cacheKey,entries);}
  const at=pick(range(entries.length).filter(i=>entries![i].depth>=floor&&entries![i].depth<=floor+3)),solution=path(entries,at).reverse().map(a=>({from:a.to,to:a.from}));return finish({...d,initial:entries[at].state,minimum:entries[at].depth},solution,'おおきい リングを うごかす ために、ちいさい やまを どこへ よける？');
 }
 if(id==='river'){for(let attempt=0;attempt<500;attempt++){
  const n=L<5?3:L<9?4:L<15?5:6,capacity=n===3?1:2,cover=shuffle(range(n)).slice(0,capacity),possible=range(n).flatMap(a=>range(n-a-1).map(i=>[a,a+i+1])).filter(([a,b])=>cover.includes(a)||cover.includes(b)),conflicts=shuffle(possible).slice(0,int(Math.max(1,n-2),possible.length)).sort((a,b)=>a[0]-b[0]||a[1]-b[1]),d={n,capacity,conflicts},p={id,data:d};
  const actions=(s:any)=>{const same=range(n).filter(i=>s.banks[i]===s.boat);return range(2**same.length).map(mask=>({riders:same.filter((_,i)=>mask&(1<<i))})).filter(a=>a.riders.length<=capacity);};
  const entries=explore({banks:range(n).map(()=>1),boat:1},neighbors(p,actions),2000).entries,max=Math.max(...entries.map(e=>e.depth)),minimum=2+Math.floor((L-1)*.33),depth=Math.min(max,minimum+2),candidates=range(entries.length).filter(i=>entries[i].depth>=minimum&&entries[i].depth<=depth);if(!candidates.length)continue;const at=pick(candidates);
  return finish({...d,initial:entries[at].state,minimum:entries[at].depth},path(entries,at).reverse(),'ふねが いなくなる きしに、けんかする ペアを のこさないように。');
 }throw Error('river challenge generation');}
 if(id==='jugs'){
  for(let attempt=0;attempt<300;attempt++){
   const caps=shuffle(range(L<8?7:12).map(i=>i+2)).slice(0,L<8?2:3).sort((a,b)=>a-b),initial=caps.map(()=>0),p={id,data:{caps}},actions=()=>caps.flatMap((_,from)=>[{type:'fill',from},{type:'empty',from},...range(caps.length).filter(to=>to!==from).map(to=>({type:'pour',from,to}))]),entries=explore(initial,neighbors(p,actions),12000).entries,minimum=2+Math.floor((L-1)*.4),candidates=range(entries.length).filter(i=>entries[i].depth>=minimum&&entries[i].depth<=minimum+2&&entries[i].state.filter((v:number,j:number)=>v>0&&v<caps[j]).length>=(L<12?1:2)&&path(entries,i).filter(a=>a.type==='pour').length>=1+Math.floor((L-1)/6));if(!candidates.length)continue;const at=pick(candidates);return finish({caps,initial,target:entries[at].state,minimum:entries[at].depth},path(entries,at),'ちがう おおきさの はこを つかうと、のこりの りょうを つくれるよ。');
  }throw Error('jug challenge generation');
 }
 if(id==='pegs'){
  const n=5,steps=2+Math.floor((L-1)*.65);for(let attempt=0;attempt<300;attempt++){let state=[12],back:any[]=[];for(let k=0;k<steps;k++){const moves:any[]=[];for(const to of state)for(let d=0;d<4;d++){const mid=directed(to,d,n),from=mid<0?-1:directed(mid,d,n);if(mid>=0&&from>=0&&!state.includes(mid)&&!state.includes(from))moves.push({from,to,mid});}if(!moves.length)break;const move=pick(moves);state=sort([...state.filter(v=>v!==move.to),move.from,move.mid]);back.push({from:move.from,to:move.to});}if(back.length!==steps)continue;const solution=back.reverse(),d={n,initial:state},features=traceFeatures({id,data:d},solution);if(features.choices<Math.floor((L-1)/4))continue;return finish({...d,minimum:steps,decisionPoints:features.choices},solution,'とびこせる ところが ふたつ あったら、のこる まるも かんがえよう。');}throw Error('peg decision challenge');
 }
 if(id==='frogs'){
  const maxTeam=Math.min(5,1+Math.floor((L+2)/4)),a=Math.max(1,maxTeam-int(0,L<6?0:1)),b=maxTeam,target=[...range(b).map(()=>-1),0,...range(a).map(()=>1)],p={id,data:{target}},cacheKey='frogs'+a+':'+b;
  let entries=graphCache.get(cacheKey);if(!entries){entries=explore(target,(s:number[])=>range(s.length).flatMap(i=>{const reverse=trialStep(p,s.map(v=>-v),i);return reverse?[{state:reverse.map((v:number)=>-v),action:s.indexOf(0)}]:[];}),20000).entries;graphCache.set(cacheKey,entries);}
  const max=Math.max(...entries.map(e=>e.depth)),depth=Math.min(max,2+Math.floor((L-1)*1.2)),at=pick(range(entries.length).filter(i=>entries![i].depth>=Math.max(2,depth-1)&&entries![i].depth<=Math.min(max,depth+2)));
  return finish({k:Math.max(a,b),initial:entries[at].state,target,minimum:entries[at].depth},path(entries,at).reverse(),'あいてを とびこせる ばしょを つくろう。');
 }
 if(id==='traffic'){const bank=rankedTrafficBank(L),entry=bank[((Math.floor(seed)%bank.length)+bank.length)%bank.length],{n,cars,initial,solution,minimum,blockerCount}=clone(entry);return finish({n,cars,initial,minimum,blockerCount},solution,'ふさぐ くるまを どける ために、どの くるまから うごかす？');}
 if(id==='colorsort'){
  const colors=L<6?3:L<13?4:5,capacity=L<5?2:L<11?3:4,minimum=3+Math.floor((L-1)*.55);
  for(let attempt=0;attempt<400;attempt++){let state=[...range(colors).map(i=>range(capacity).map(()=>i)),[],[]],best:any=null;for(let step=0;step<35+L*5;step++){const choices:any[]=[];for(let from=0;from<state.length;from++){if(!state[from].length)continue;const color=state[from].at(-1)!;if(state[from].length>1&&state[from].at(-2)!==color)continue;for(let to=0;to<state.length;to++)if(to!==from&&state[to].length<capacity)choices.push({from,to});}if(!choices.length)break;const action=pick(choices),next=clone(state);next[action.to].push(next[action.from].pop()!);state=next;if(colorLowerBound(state,colors)>=minimum-1)best=clone(state);}if(!best)continue;const plan=colorPlan(best,capacity,colors);if(!plan||plan.minimum<minimum)continue;return finish({capacity,colors,initial:best,minimum:plan.minimum,displacedBalls:colorLowerBound(best,colors)},plan.solution,'いま あいている ボトルを、つぎに どの しるしへ つかう？');}throw Error('color sorting depth');
 }
 if(id==='trainyard'){const bank=rankedTrainBank(L),entry=clone(bank[((Math.floor(seed)%bank.length)+bank.length)%bank.length]),{solution,...d}=entry;return finish(d,solution,'おくの れっしゃを だす ための、あき ばしょを のこそう。');}
 if(id==='programbot'){
  const n=L<8?4:5,depth=2+Math.floor((L-1)*.45),allowed=L<9?['F','L','R']:L<13?['F','L','R','F2']:['F','L','R','F2','F3'];
  for(let attempt=0;attempt<700;attempt++){const pos=int(0,n*n-1),walls=shuffle(range(n*n).filter(i=>i!==pos)).slice(0,1+Math.floor(L/3)),initial={pos,dir:int(0,3),used:0},d={n,walls,initial,budget:64,allowed},p={id,data:d},entries=explore(initial,neighbors(p,()=>allowed),5000,s=>key([s.pos,s.dir])).entries,candidates=shuffle(range(entries.length).filter(i=>entries[i].depth===depth&&entries[i].state.pos!==pos));for(const at of candidates){const solution=path(entries,at),target={pos:entries[at].state.pos,dir:entries[at].state.dir},features=traceFeatures(p,solution),detour=depth-openProgramDistance(d,target);if(features.turns<(L<3?0:L<7?1:2)||detour<(L<8?0:L<13?1:2))continue;return finish({...d,target,budget:depth+(L<4?1:0),minimum:depth,obstacleDetour:detour,turns:features.turns},solution,'まえへ すすむ まえに、むきを かくにん。かべを よける じゅんを くもう。');}}throw Error('robot planning challenge');
 }
 if(id==='keydoors'){
  const n=L<6?5:L<16?7:9,w=(n+1)/2,k=L<6?1:L<12?2:3;
  for(let attempt=0;attempt<2000;attempt++){
   const start=int(0,w*w-1),toCell=(at:number)=>Math.floor(at/w)*2*n+at%w*2,floor=new Set([toCell(start)]),visited=new Set([start]),edges:number[][]=[];
   const add=(at:number)=>adjacent(at,w).filter(j=>!visited.has(j)).forEach(j=>edges.push([at,j]));add(start);
   while(edges.length){const i=int(0,edges.length-1),[a,b]=edges.splice(i,1)[0];if(visited.has(b))continue;visited.add(b);floor.add(toCell(b));floor.add((toCell(a)+toCell(b))/2);add(b);}
   const walls=range(n*n).filter(i=>!floor.has(i)),initial={pos:toCell(start),keys:0},plain={id:'sokoban',data:{n,walls}},entries=explore({pos:initial.pos,boxes:[]},neighbors(plain,()=>range(4)),n*n).entries,far=Math.max(...entries.map(e=>e.depth)),at=pick(range(entries.length).filter(i=>entries[i].depth>=far-2)),route=path(entries,at),cells=[initial.pos];for(const d of route)cells.push(directed(cells.at(-1)!,d,n));
   const slots=shuffle(range(cells.length-2).map(i=>i+1)).slice(0,k).sort((a,b)=>a-b);if(slots.length<k)continue;const doors=slots.map(i=>cells[i]),keys:number[]=[];
   for(let i=0;i<k;i++){
    const blocked=new Set([...walls,...doors.slice(i)]),reachable=[initial.pos],seen=new Set(reachable);for(let j=0;j<reachable.length;j++)for(const q of adjacent(reachable[j],n))if(!blocked.has(q)&&!seen.has(q)){seen.add(q);reachable.push(q);}
    let beforePrevious=new Set<number>();if(i>0){const q=[initial.pos],seen=new Set(q),blockedPrevious=new Set([...walls,doors[i-1]]);for(let j=0;j<q.length;j++)for(const next of adjacent(q[j],n))if(!blockedPrevious.has(next)&&!seen.has(next)){seen.add(next);q.push(next);}beforePrevious=seen;}
    const branchDistance=(v:number)=>Math.min(...cells.map(at=>Math.abs(v%n-at%n)+Math.abs(Math.floor(v/n)-Math.floor(at/n))));
    const options=reachable.filter(v=>!cells.includes(v)&&!keys.includes(v)&&(i===0||!beforePrevious.has(v))&&branchDistance(v)>=(L<8?1:L<16?2:3));if(!options.length)break;keys.push(pick(options));
   }if(keys.length!==k)continue;const d={n,walls,keys,doors,goal:cells.at(-1),initial},p={id,data:d},res=explore(initial,neighbors(p,()=>range(4)),n*n*2**k,s=>key([s.pos,s.keys]),s=>s.pos===d.goal);if(res.found<0||res.entries[res.found].depth<6+L)continue;
   return finish({...d,minimum:res.entries[res.found].depth,dependencyDepth:k},path(res.entries,res.found),'ドアへ いく まえに、わきみちの カギを さがそう。');
  }throw Error('key-door dependencies');
 }
 if(id==='twobots'){
  const n=L<9?4:5,depth=3+Math.floor((L-1)*.6);for(let attempt=0;attempt<700;attempt++){
   const walls=shuffle(range(n*n)).slice(0,2+Math.floor(L/4)),positions=shuffle(range(n*n).filter(i=>!walls.includes(i))).slice(0,2),initial={positions},d={n,walls,initial},p={id,data:d},entries=explore(initial,neighbors(p,()=>range(4)),2000).entries,candidates=range(entries.length).filter(i=>entries[i].depth===depth&&entries[i].state.positions.every((v:number,j:number)=>v!==positions[j]));if(!candidates.length)continue;const ranked=shuffle(candidates).map(at=>({at,solution:path(entries,at)})).filter(v=>traceFeatures(p,v.solution).wallStops>=Math.floor((L+2)/5));if(!ranked.length)continue;const {at,solution}=ranked[0];return finish({...d,target:entries[at].state.positions,minimum:depth,wallStops:traceFeatures(p,solution).wallStops},solution,'かべで ひとりだけ とめると、ふたりの きょりを かえられるよ。');
  }throw Error('two robot challenge generation');
 }
 if(id==='matchsticks'){
  for(let attempt=0;attempt<200;attempt++){
   const a=L<5?int(0,8):L<9?int(5,9):L<15?int(10,59):int(10,59),b=L<5?int(1,9-a):L<9?int(10-a,9):L<15?int(1,9):int(10,39),sum=a+b,groups=[String(a).length,String(b).length,String(sum).length],truth=[...String(a),...String(b),...String(sum)].map(v=>SEGMENTS[Number(v)]),steps=L<7?1:L<14?2:3,d:any={groups,maxMoves:steps,initial:{masks:truth,used:0}};let masks=[...truth],back:any[]=[],last:any=null;
   for(let k=0;k<steps;k++){
    const options:any[]=[];for(let from=0;from<masks.length*7;from++)for(let to=0;to<masks.length*7;to++){
     if(!(masks[Math.floor(from/7)]&(1<<(6-from%7)))||(masks[Math.floor(to/7)]&(1<<(6-to%7))))continue;
     const next=[...masks];next[Math.floor(from/7)]^=1<<(6-from%7);next[Math.floor(to/7)]^=1<<(6-to%7);if(next.some(v=>!SEGMENTS.includes(v)))continue;
     const starts=[0,groups[0],groups[0]+groups[1]];if(starts.some((start,i)=>groups[i]>1&&next[start]===SEGMENTS[0]))continue;
     if(last&&last.from===from&&last.to===to)continue;options.push({masks:next,action:{from:to,to:from}});
    }if(!options.length)break;const move=pick(options);masks=move.masks;back.unshift(move.action);last=move.action;
   }d.initial={masks,used:0};if(back.length!==steps||minimumEquationMoves(groups,masks)!==steps)continue;d.minimum=steps;return finish(d,back,'しきも ただしく なるように、マッチを うつそう。');
  }throw Error('readable matchstick equation');
 }
 if(id==='bridge'){const n=L<5?3:L<11?4:L<16?5:6;let times:number[]=[];for(let attempt=0;attempt<500;attempt++){times=shuffle(range(8+L).map(i=>i+1)).slice(0,n).sort((a,b)=>a-b);const margins=range(Math.floor((n-2)/2)).map(i=>times[0]+times[n-2-i*2]-2*times[1]);if(L<17||margins.some(v=>v<0)&&margins.some(v=>v>0))break;}const initial={banks:range(n).map(()=>0),boat:0,time:0},d:any={n,times,initial,budget:999},p={id,data:d},entries:any[]=[{state:initial,parent:-1,action:null,cost:0}],best=new Map([[key([initial.banks,0]),0]]),pending=[0];let found=-1;while(pending.length){pending.sort((a,b)=>entries[a].cost-entries[b].cost);const at=pending.shift()!,s=entries[at].state;if(entries[at].cost!==best.get(key([s.banks,s.boat])))continue;if(s.banks.every((v:number)=>v===1)){found=at;break;}const same=range(n).filter(i=>s.banks[i]===s.boat),actions=[...same.map(i=>({riders:[i]})),...same.flatMap((a,i)=>same.slice(i+1).map(b=>({riders:[a,b]})))];for(const action of actions){const next=trialStep(p,s,action),k=key([next.banks,next.boat]),cost=next.time;if(cost<(best.get(k)??Infinity)){best.set(k,cost);entries.push({state:next,parent:at,action,cost});pending.push(entries.length-1);}}}if(found<0)throw Error('bridge');d.budget=entries[found].cost+(L<5?1:0);d.minimum=entries[found].cost;return finish(d,path(entries,found),'はやい ひとに、あかりを もって もどってもらおう。');}
 if(id==='ballweigh'){
  const n=2+L,evidence=L<5?0:L<10?1:L<15?2:3,minimumCandidates=2+Math.floor((L-1)/5);
  for(let attempt=0;attempt<500;attempt++){const culprit=int(0,n-1),initial:any={candidates:range(n),observations:[],guess:null},d:any={n,budget:20,culprit,initial},p={id,data:d};let state=initial;
   for(let i=0;i<evidence;i++){let accepted:any=null;for(let trial=0;trial<150;trial++){const order=shuffle(range(n)),count=int(1,Math.floor(n/2)),action={left:order.slice(0,count),right:order.slice(count,count*2)},next=trialStep(p,state,action);if(next.candidates.length<minimumCandidates||next.candidates.length>=state.candidates.length)continue;accepted=next;break;}if(!accepted)break;state=accepted;}
   if(state.observations.length!==evidence||state.candidates.length<2)continue;d.initial=state;d.budget=evidence+Math.ceil(Math.log(state.candidates.length)/Math.log(3)-1e-8);d.initialCandidateCount=state.candidates.length;const solution:any[]=[];let solved=state;
   while(solved.candidates.length>1){const count=Math.max(1,Math.round(solved.candidates.length/3)),action={left:solved.candidates.slice(0,count),right:solved.candidates.slice(count,count*2)};solution.push(action);solved=trialStep(p,solved,action);if(!solved)throw Error('weighing witness');}solution.push({guess:solved.candidates[0]});return finish(d,solution,evidence?'これまでの はかりを よんで、まだ かるいかもしれない たまを さがそう。':'のせない たまも ひとつの グループ。3つに わけて しらべよう。');
  }throw Error('weighing evidence generation');
 }
 if(id==='codebreak'){
  const length=L<5?3:L<14?4:5,alphabet=L<4?4:L<10?5:6,repeats=L>=7,pool=codePool(length,alphabet,repeats),clues=L<5?1:L<11?2:3,minimum=3+Math.floor((L-1)*2),maximum=minimum*3+8;
  for(let attempt=0;attempt<200;attempt++){const secret=pick(pool),history:any[]=[],used=new Set<string>();let candidates=pool;
   for(let i=0;i<clues;i++){let chosen:any=null;for(let tries=0;tries<120;tries++){const guess=pick(pool),k=key(guess);if(equal(guess,secret)||used.has(k))continue;const feedback=codeFeedback(secret,guess),next=candidates.filter(s=>equal(codeFeedback(s,guess),feedback));if(next.length<minimum||next.length>=candidates.length||i===clues-1&&next.length>maximum)continue;chosen={guess,feedback,next};break;}if(!chosen)break;used.add(key(chosen.guess));history.push({guess:chosen.guess,...chosen.feedback});candidates=chosen.next;}
   if(history.length!==clues)continue;return finish({length,alphabet,repeats,secret,initial:{history},candidateCount:candidates.length,totalPossibilities:pool.length},[secret],'ヒントの 2ぎょうを くらべて、ばしょと しるしを しぼろう。');
  }throw Error('code evidence generation');
 }
 if(id==='flood'){for(let attempt=0;attempt<500;attempt++){const n=L<6?3:L<13?4:5,k=Math.min(n*n,5+Math.floor(L*.7)),seeds=shuffle(range(n*n)).slice(0,k),regions=range(n*n).map(i=>seeds.indexOf(i)),q=[...seeds];for(let i=0;i<q.length;i++)for(const at of adjacent(q[i],n))if(regions[at]<0){regions[at]=regions[q[i]];q.push(at);}const palette=L<6?3:L<13?4:5,colors=range(k).map(()=>int(0,palette-1));colors[0]=0;colors[1]=1;const edges:number[][]=[];range(n*n).forEach(i=>adjacent(i,n).forEach(j=>{const e=sort([regions[i],regions[j]]);if(e[0]!==e[1]&&!edges.some(v=>equal(v,e)))edges.push(e);}));const d:any={n,k,regions,colors,edges,palette,budget:64},start=regions[0],initial={mask:floodGrow(d,1<<start,colors[start]),color:colors[start],used:0};d.initial=initial;const p={id,data:d},all=(1<<k)-1,res=explore(initial,neighbors(p,()=>range(palette)),16000,s=>key([s.mask,s.color]),s=>s.mask===all);if(res.found<0||res.entries[res.found].depth<Math.max(2+Math.floor(L/4),2+Math.floor((L-1)*.35)))continue;const solution=path(res.entries,res.found);d.budget=solution.length+(L<5?1:0);d.minimum=solution.length;return finish(d,solution,'とおくの しまへ つながる いろを さがそう。');}throw Error('flood challenge generation');}
}
