'use client';
import React,{useState,useEffect,useMemo,useRef,useCallback} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Box,Brain,Check,ChevronDown,ChevronRight,Clock,Search,Flag,Gamepad2,Grid2X2,Hash,Heart,Home,Infinity as InfinityIcon,Lightbulb,Pause,Play,RotateCcw,Route,Settings,Shapes,ShieldCheck,Sparkles,Star,Trophy,Volume2,VolumeX,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Progress as ProgressBar} from '@/components/ui/progress';
import {GAMES,CATEGORIES,LEVEL_NAMES,QUESTIONS} from '@/lib/catalog';
import {generate,check,hash} from '@/lib/puzzles';
import {generateStage,stageInfo,stageCount,coursePhases} from '@/lib/stages';
import {Progress,emptyProgress,SessionResult,earnedStars} from '@/lib/progress';
import {PuzzleView} from '@/components/puzzle-view';
import {Glyph} from '@/components/puzzle-art';
import {createSaveQueue,SaveStatus} from '@/lib/save-queue';
import {Tutorial} from '@/components/tutorial';
import {GamePreview} from '@/components/game-preview';
import {localRecords, exportBackup, importBackup} from '@/lib/local-records';
import {recommendations,japanDay,INTRO_GAMES,MILESTONES} from '@/lib/curriculum';
import {sessionId} from '@/lib/session-id';

type Game=typeof GAMES[number];type Mode='stage'|'timed'|'free';
const icons={space:Box,plane:Shapes,trial:Route,logic:Brain,number:Hash};
const MODE_LABEL={stage:'ステージ',timed:'3ぷん',free:'じっくり'};
const PRESETS=['stroke','cubes','rails','mirror','count','order'];
const MASCOT=`${import.meta.env.BASE_URL}mascot.png`;
// Read once before effects so React StrictMode cannot overwrite the selected profile.
function initialProfile(){try{const p=Number(localStorage.getItem('hirameki-profile'));return Number.isInteger(p)&&p>=1&&p<=6?p:1;}catch{return 1;}}
const PROFILE_NAMES=['ぼうけんか 1','ぼうけんか 2','ぼうけんか 3','ぼうけんか 4','ぼうけんか 5','おうちのひと'];
let audioCtx:AudioContext|null=null;
function sound(correct:boolean,enabled:boolean){if(!enabled)return;try{const Ctx=window.AudioContext||(window as any).webkitAudioContext;audioCtx??=new Ctx();if(audioCtx!.state==='suspended')void audioCtx!.resume();const now=audioCtx!.currentTime;for(let i=0;i<(correct?3:1);i++){const o=audioCtx!.createOscillator(),g=audioCtx!.createGain();o.type='sine';o.frequency.value=correct?[523,659,784][i]:240;g.gain.setValueAtTime(.0001,now+i*.075);g.gain.exponentialRampToValueAtTime(.075,now+i*.075+.01);g.gain.exponentialRampToValueAtTime(.0001,now+i*.075+.2);o.connect(g);g.connect(audioCtx!.destination);o.start(now+i*.075);o.stop(now+i*.075+.21);}}catch{}}
function speak(text:string){try{if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.85;window.speechSynthesis.speak(u);}catch{}}
function Logo(){return <span className="wordmark"><span className="logo-mark"><i/><i/><i/><i/></span><span>ひらめき<span>ラボ</span><small>HIRAMEKI LAB</small></span></span>}

function Session({game,mode,stage,startLevel,profile,soundOn,onFinish,onHome}:{game:Game;mode:Mode;stage:number;startLevel:number;profile:number;soundOn:boolean;onFinish:(s:SessionResult)=>void;onHome:()=>void}){
 const [index,setIndex]=useState(0),[level,setLevel]=useState(startLevel),[score,setScore]=useState(0),[time,setTime]=useState(180),[paused,setPaused]=useState(false),[help,setHelp]=useState(false),[hint,setHint]=useState(false),[feedback,setFeedback]=useState(''),[quitting,setQuitting]=useState(false);
 const seed=useRef(Math.floor(Math.random()*1e8)),busy=useRef(false),finished=useRef(false),failed=useRef(false),hinted=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),nextRef=useRef<()=>void>(()=>{}),elapsed=useRef(0),streak=useRef(0),metrics=useRef({correct:0,attempted:0,firstCorrect:0,hints:0,level:startLevel});
 const p=useMemo(()=>mode==='stage'?generateStage(game.id,stage,index):generate(game.id,level,seed.current+index),[game.id,mode,stage,index,level]);
 const lesson=mode==='stage'?stageInfo(game.id,stage):null,prompt=p.data.prompt||game.prompt;
 const cat=CATEGORIES.find(c=>c.id===game.category)!;
 const finish=useCallback(()=>{if(finished.current)return;finished.current=true;busy.current=true;if(timer.current)clearTimeout(timer.current);try{window.speechSynthesis?.cancel();}catch{}onFinish({id:sessionId(),profile,game:game.id as SessionResult['game'],mode,stage,...metrics.current,seconds:Math.max(1,Math.floor(elapsed.current))});},[onFinish,profile,game.id,mode,stage]);
 useEffect(()=>{if(paused||help||quitting)return;let last=performance.now();const t=setInterval(()=>{const now=performance.now();if(!finished.current){elapsed.current+=(now-last)/1000;if(mode==='timed'){const left=Math.max(0,180-elapsed.current);setTime(left);if(left<=0)finish();}}last=now;},100);return()=>clearInterval(t);},[paused,help,quitting,mode,finish]);
 useEffect(()=>{const hide=()=>{if(document.hidden)setPaused(true);};document.addEventListener('visibilitychange',hide);return()=>{document.removeEventListener('visibilitychange',hide);if(timer.current)clearTimeout(timer.current);try{window.speechSynthesis?.cancel();}catch{}};},[]);
 function next(){if(finished.current)return;const hadError=failed.current;if(mode==='stage'&&metrics.current.attempted>=QUESTIONS){finish();return;}failed.current=false;hinted.current=false;setHint(false);setFeedback('');busy.current=false;if(mode==='timed'&&hadError)setLevel(x=>Math.max(1,x-1));if(mode==='timed'&&streak.current>=3){setLevel(x=>Math.min(20,x+1));streak.current=0;}setIndex(i=>i+1);}
 nextRef.current=next;
 useEffect(()=>{if(feedback!=='できた！'||paused||help||quitting)return;timer.current=setTimeout(()=>nextRef.current(),p.kind==='trial'?1300:950);return()=>{if(timer.current)clearTimeout(timer.current);};},[feedback,paused,help,quitting,p.kind]);
 function answer(a:any){if(busy.current||finished.current||paused||help||quitting)return;if(check(p,a)){busy.current=true;metrics.current.correct++;metrics.current.attempted++;metrics.current.level=Math.max(metrics.current.level,p.level);if(!failed.current&&!hinted.current){metrics.current.firstCorrect++;streak.current++;}else streak.current=0;setScore(metrics.current.correct);setFeedback('できた！');sound(true,soundOn);}else{failed.current=true;streak.current=0;setFeedback('もういちど！');sound(false,soundOn);}}
 function skip(){if(busy.current)return;metrics.current.attempted++;streak.current=0;failed.current=true;next();}
 function showHint(){if(!hinted.current){metrics.current.hints++;hinted.current=true;}setHint(!hint);}
 return <main className="play-page" style={{'--game-color':cat.color,'--game-pale':cat.pale} as React.CSSProperties}>
  <header className="play-header"><button className="icon-button" aria-label="ゲームをおわる" onClick={()=>setQuitting(true)}><ArrowLeft/></button><div><span className="eyebrow">{MODE_LABEL[mode]} {mode==='stage'?String(stage).padStart(2,'0'):`LEVEL ${p.level}`}</span><h1>{game.name}</h1></div><button className="icon-button" onClick={()=>setPaused(true)} aria-label="いちじていし"><Pause/></button></header>
  <div className="game-status"><span><Star size={18} fill="#ffcf54"/> {score}<small>できた</small></span>{mode==='timed'?<span className={time<30?'time-low':''}><Clock size={18}/>{Math.floor(time/60)}:{String(Math.floor(time%60)).padStart(2,'0')}</span>:mode==='stage'?<span>{Math.min(index+1,10)} <small>/ 10もん</small></span>:<span><InfinityIcon size={20}/><small>じかん むせいげん</small></span>}</div>
  <ProgressBar value={mode==='timed'?time/180*100:mode==='stage'?index/10*100:100} className="session-progress"/>
  <>{lesson&&<div className="lesson-strip"><span>テーマ {lesson.theme} ・ {lesson.mission}</span><strong>{lesson.goal}</strong></div>}</><div className="question-heading"><h2>{prompt}</h2><button className="voice-button" onClick={()=>speak(prompt)} aria-label="もんだいをよむ"><Volume2 size={20}/></button></div>
  <section className={`play-board ${feedback==='できた！'?'correct-board':''}`}><PuzzleView key={`${game.id}-${index}`} p={p} onAnswer={answer} locked={busy.current||paused||help||quitting} hint={hint}/>{feedback==='できた！'&&<div className="correct-pop" role="status"><span><Check size={42}/></span><strong>できた！</strong>{[0,1,2,3,4,5].map(i=><i key={i} style={{'--i':i} as React.CSSProperties}/>)}</div>}</section>
  <div className="feedback-line" aria-live="polite">{feedback!=='できた！'&&feedback}</div>
  {hint&&<div className="hint-message"><Lightbulb size={20}/><span>{p.hint}</span></div>}
  <footer className="play-tools"><button onClick={()=>setHelp(true)}><BookOpen size={20}/>あそびかた</button><button onClick={showHint} disabled={busy.current} className={hint?'active':''}><Lightbulb size={20}/>ヒント</button><button onClick={skip} disabled={busy.current}>つぎの もんだい<ChevronRight size={20}/></button></footer>
  {mode==='free'&&<button className="finish-free" onClick={finish}>ここまでで おわる <Flag size={16}/></button>}
  <Dialog open={paused||help||quitting} onOpenChange={v=>{if(!v){setPaused(false);setHelp(false);setQuitting(false);}}}><DialogContent className="game-dialog"><DialogTitle>{help?'あそびかた':quitting?'ここで おわる？':'ひとやすみ'}</DialogTitle><DialogDescription>{help?(p.data.help||game.help):quitting?'ここまでの「できた！」は、きろくに のこるよ。':'じかんも とまっているよ。'}</DialogDescription>{help?<><p className="current-rule">{p.hint}</p><small>きほんの あそびかた</small><Tutorial id={game.id}/><button className="secondary-button" onClick={()=>speak(p.data.help||game.help)}><Volume2 size={18}/>よみあげる</button></>:<img src={MASCOT} alt="" className="dialog-mascot"/>}<button className="primary-button" onClick={()=>{setPaused(false);setHelp(false);setQuitting(false);}}><Play size={18} fill="currentColor"/>つづける</button>{!help&&<button className="text-button" onClick={()=>metrics.current.correct>0?finish():onHome()}>おわって もどる</button>}</DialogContent></Dialog>
 </main>;
}

export default function HomePage(){
 const [profile,setProfile]=useState(initialProfile),[soundOn,setSoundOn]=useState(true),[progress,setProgress]=useState<Progress>(emptyProgress),[loadError,setLoadError]=useState(false),[loading,setLoading]=useState(true),[tab,setTab]=useState('play'),[filter,setFilter]=useState('recommend'),[mode,setMode]=useState<Mode>('stage'),[selected,setSelected]=useState<Game|null>(null),[stage,setStage]=useState(1),[level,setLevel]=useState(1),[session,setSession]=useState<{game:Game;mode:Mode;stage:number;level:number}|null>(null),[result,setResult]=useState<SessionResult|null>(null),[saveStates,setSaveStates]=useState<Record<string,SaveStatus>>({}),[settings,setSettings]=useState(false),[profiles,setProfiles]=useState(false),[stagePicker,setStagePicker]=useState(false),[tutorialOpen,setTutorialOpen]=useState(false),[query,setQuery]=useState(''),[favorites,setFavorites]=useState<string[]>([]),[backupMessage,setBackupMessage]=useState(''),[backupBusy,setBackupBusy]=useState(false),[day,setDay]=useState('');
 const records=useMemo(()=>localRecords(),[]);
 const importInput=useRef<HTMLInputElement>(null);
 const [pending,setPending]=useState<SessionResult[]>([]),profileRef=useRef(profile),queueRef=useRef(pending),loadSequence=useRef(0);profileRef.current=profile;queueRef.current=pending;
 useEffect(()=>{try{setSoundOn(localStorage.getItem('hirameki-sound')!=='off');const saved=JSON.parse(localStorage.getItem('hirameki-favorites')||'[]');if(Array.isArray(saved))setFavorites(saved.filter(id=>GAMES.some(g=>g.id===id)));setDay(japanDay());}catch{}},[]);
 const load=useCallback(async(p=profileRef.current)=>{if(p!==profileRef.current)return;const request=++loadSequence.current;setLoading(true);try{const data=await records.progress(p);if(profileRef.current===p&&request===loadSequence.current){setProgress(data);setLoadError(false);}}catch{if(profileRef.current===p&&request===loadSequence.current)setLoadError(true);}finally{if(profileRef.current===p&&request===loadSequence.current)setLoading(false);}},[records]);
 useEffect(()=>{setProgress(emptyProgress);void load(profile);try{localStorage.setItem('hirameki-profile',String(profile));}catch{}},[profile,load]);
 const save=useMemo(()=>createSaveQueue<SessionResult>(s=>records.save(s),(id,status,s)=>{setSaveStates(states=>({...states,[id]:status}));if(status==='saved'){setPending(q=>q.filter(x=>x.id!==id));void load(s.profile);}else setPending(q=>q.some(x=>x.id===id)?q:[...q,s]);}),[load,records]);
 useEffect(()=>{const refresh=()=>void load();const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('hirameki-records'):null;if(channel)channel.onmessage=refresh;return()=>channel?.close();},[load]);
 useEffect(()=>{if(!pending.length)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[pending.length]);
 /** Download all six profiles; pending saves are included so retries do not lose play. */
 async function downloadBackup(){setBackupBusy(true);setBackupMessage('');try{const {text,partial}=await exportBackup(records,queueRef.current);const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`hirameki-lab-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setBackupMessage(partial?'未保存のきろくだけを救出しました。過去の保存済み記録は含まれていません。':'6人分のきろくを書き出しました。ファイルを大切に保管してください。');}catch{setBackupMessage('書き出せませんでした。保存領域を使えるブラウザで再試行してください。');}finally{setBackupBusy(false);}}
 /** Validate the complete file before atomically combining it with existing records. */
 async function restoreBackup(file:File){setBackupBusy(true);setBackupMessage('');try{const added=await importBackup(records,file);await load();setBackupMessage(`${added}件のきろくを追加しました。同じきろくは重ねて数えません。`);}catch(e){setBackupMessage(e instanceof Error?e.message:'読み込めませんでした。きろくは変更していません。');}finally{setBackupBusy(false);if(importInput.current)importInput.current.value='';}}
 const saveState=result?saveStates[result.id]||'saving':'saving';
 const finish=useCallback((s:SessionResult)=>{setSession(null);setResult(s);void save(s);},[save]);
 function select(g:Game){setTutorialOpen(false);setSelected(g);const gp=progress.games[g.id],next=Array.from({length:stageCount(g.id)},(_,i)=>i+1).find(s=>!gp?.stages?.[s])||stageCount(g.id);setStage(next);setLevel(Math.max(1,Math.min(20,gp?.level||1)));}
 function start(g:Game,m:Mode,s:number,l:number){setSelected(null);setResult(null);setSession({game:g,mode:m,stage:s,level:l});sound(true,soundOn);window.scrollTo(0,0);}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();const register=(tool:any)=>{try{Promise.resolve(ctx.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};register({name:'list_thinking_games',description:'Read the 120 thinking puzzle games and the selected profile progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({games:GAMES,progress,profile})});register({name:'open_game_setup',description:'Open a game selection dialog. Does not play or change scores.',inputSchema:{type:'object',properties:{game:{type:'string',enum:GAMES.map(g=>g.id)}},required:['game'],additionalProperties:false},execute:(input:any)=>{const g=GAMES.find(g=>g.id===input?.game);if(!g||session)throw Error('Game not available');select(g);return{opened:g.id};}});return()=>life.abort();},[progress,profile,session]);
 function favorite(id:string){setFavorites(old=>{const next=old.includes(id)?old.filter(v=>v!==id):[...old,id];try{localStorage.setItem('hirameki-favorites',JSON.stringify(next));}catch{}return next;});}

 const solvedGames=GAMES.filter(g=>(progress.games[g.id]?.correct||0)>0).length;
 const nextMilestone=MILESTONES.find(n=>n>progress.correct)||Math.ceil((progress.correct+1)/1000)*1000;
 if(session)return <Session key={`${session.game.id}-${session.mode}-${session.stage}`} game={session.game} mode={session.mode} stage={session.stage} startLevel={session.level} profile={profile} soundOn={soundOn} onFinish={finish} onHome={()=>setSession(null)}/>;
 const baseGames=filter==='recommend'?recommendations(progress,day):filter==='intro'?GAMES.filter(g=>INTRO_GAMES.includes(g.id)):filter==='favorites'?GAMES.filter(g=>favorites.includes(g.id)):GAMES.filter(g=>filter==='all'||g.category===filter);const displayed=(query?GAMES:baseGames).filter(g=>!query||`${g.name}${g.help}${g.prompt}`.replaceAll(' ','').includes(query.replaceAll(' ','')));
 return <div className="app-shell">
  <header className="site-header"><button className="brand-button" onClick={()=>{setTab('play');setFilter('recommend');}} aria-label="ひらめきラボ ホーム"><Logo/></button><div className="header-right"><button className="profile-button" onClick={()=>setProfiles(true)}><span className="profile-avatar"><Glyph value={profile-1} size={28}/></span><span>{PROFILE_NAMES[profile-1]}</span><ChevronDown size={16}/></button><button className="icon-button" onClick={()=>setSettings(true)} aria-label="せってい"><Settings size={22}/></button></div></header>
  <main className="main-content">
   {pending.length>0&&<div className="save-warning" role="alert">保存を待っている きろくが {pending.length}件あります。<button onClick={async()=>{for(const s of queueRef.current)await save(s);}}>もういちど 保存</button><small>端末内に保存できませんでした。再試行が済むまで、このページを閉じないでください。</small><button disabled={backupBusy} onClick={()=>void downloadBackup()}>バックアップを 書き出す</button><small role="status">{backupMessage}</small></div>}
   {loadError&&<div className="load-warning">きろくを読み込めませんでした。ゲームは遊べます。<button onClick={()=>void load()}>再読み込み</button></div>}
   {tab==='play'?<>
    <section className="welcome"><div className="welcome-copy"><div className="mini-label"><Sparkles size={15}/>きょうは なにを はっけんする？</div><h1>どれで <span>あそぶ？</span></h1><p>すきな ゲームを えらんでね。</p><div className="welcome-stats"><span><Star size={17} fill="#ffcf54"/>{progress.stars} <small>スター</small></span><span><Check size={17}/>{progress.correct} <small>できた！</small></span></div></div><div className="welcome-visual"><span className="hello-note">いっしょに<br/>かんがえよう！</span><img src={MASCOT} alt="ひらめきラボの案内ロボット"/></div><div className="welcome-side"><ShieldCheck size={18}/>なんどでも あそべる</div></section>
    <div className="play-heading"><div><span className="eyebrow">LET'S PLAY</span><h2>ひらめきの あそびば <span>{GAMES.length}</span></h2></div><Tabs value={mode} onValueChange={v=>setMode(v as Mode)}><TabsList className="mode-tabs"><TabsTrigger value="stage"><Flag size={16}/><span>ステージ</span></TabsTrigger><TabsTrigger value="timed"><Clock size={16}/><span>3ぷん</span></TabsTrigger><TabsTrigger value="free"><InfinityIcon size={16}/><span>じっくり</span></TabsTrigger></TabsList></Tabs></div>
    <nav className="category-nav" aria-label="ゲームのしゅるい"><button className={filter==='recommend'?'active':''} onClick={()=>setFilter('recommend')}><Sparkles size={18}/>おすすめ</button>{CATEGORIES.map(c=>{const Icon=icons[c.id];return <button key={c.id} className={filter===c.id?'active':''} style={{'--category-color':c.color} as React.CSSProperties} onClick={()=>setFilter(c.id)}><Icon size={18}/>{c.name}<small>24</small></button>;})}<button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>ぜんぶ</button></nav><div className="discovery-bar"><div><button className={filter==='intro'?'active':''} onClick={()=>setFilter('intro')}><Sparkles size={15}/>はじめて</button><button className={filter==='favorites'?'active':''} onClick={()=>setFilter('favorites')}><Heart size={15}/>おきにいり</button></div><label className="game-search"><Search size={17}/><input aria-label="ゲームを さがす" placeholder="ゲームを さがす" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" aria-label="けんさくを けす" onClick={()=>setQuery('')}><X size={15}/></button>}</label></div>{!displayed.length&&<p className="empty-games">{filter==='favorites'&&!query?'カードの ♡で、おきにいりに いれられるよ。':'みつからなかったよ。べつの ことばで さがしてみよう。'}</p>}
    <div className="game-grid">{displayed.map((g,i)=>{const c=CATEGORIES.find(c=>c.id===g.category)!,Icon=icons[g.category],gp=progress.games[g.id];return <article role="button" tabIndex={0} aria-label={g.name} className="game-card" key={g.id} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(g);}}} onClick={()=>select(g)} style={{'--card-color':c.color,'--card-pale':c.pale,'--delay':`${Math.min(i,12)*.025}s`} as React.CSSProperties}><div className="game-preview" aria-hidden="true"><span className="category-pill"><Icon size={14}/>{c.name}</span><GamePreview id={g.id}/>{gp?.correct>0&&<span className="played-mark"><Check size={15}/></span>}</div><div className="game-card-info"><div><h3>{g.name}</h3><p>{gp?.correct?`Lv.${gp.level} · ${gp.correct}もん できた！`:`${stageCount(g.id)}ステージ · はじめての はっけん`}</p></div><div className="card-end"><button type="button" className={`favorite-button ${favorites.includes(g.id)?'is-favorite':''}`} aria-label={`${g.name}を ${favorites.includes(g.id)?'おきにいりから はずす':'おきにいりに する'}`} onClick={e=>{e.stopPropagation();favorite(g.id);}} onKeyDown={e=>e.stopPropagation()}><Heart size={19} fill={favorites.includes(g.id)?'currentColor':'none'}/></button><span className="card-play"><Play size={18} fill="currentColor"/></span></div></div></article>;})}</div>
    <p className="bottom-note"><Heart size={15}/>あわてなくて だいじょうぶ。じぶんの ペースで。</p>
   </>:<section className="records"><div className="section-title"><span className="eyebrow">MY DISCOVERIES</span><h1>はっけんの きろく</h1><p>{PROFILE_NAMES[profile-1]}の「できた！」が あつまるよ。</p></div><div className="record-stats"><div><Star/><b>{progress.stars}</b><span>スター</span></div><div><Check/><b>{progress.correct}</b><span>できた！</span></div><div><Gamepad2/><b>{solvedGames}<small>/{GAMES.length}</small></b><span>あそんだ ゲーム</span></div></div><div className="category-progress">{CATEGORIES.map(c=>{const count=GAMES.filter(g=>g.category===c.id&&(progress.games[g.id]?.correct||0)>0).length,Icon=icons[c.id];return <div key={c.id} style={{'--category-color':c.color} as React.CSSProperties}><Icon/><strong>{c.name}</strong><ProgressBar value={count/GAMES.filter(g=>g.category===c.id).length*100}/><span>{count}/{GAMES.filter(g=>g.category===c.id).length}</span></div>;})}</div><div className="milestone-card"><span><Trophy size={24}/>つぎの はっけん メダル</span><strong>{progress.correct}<small> / {nextMilestone}もん</small></strong><ProgressBar value={progress.correct/nextMilestone*100}/><div>{MILESTONES.map(n=><span key={n} className={progress.correct>=n?'earned':''}><Star size={21} fill={progress.correct>=n?'currentColor':'none'}/><small>{n}</small></span>)}</div></div><h2 className="stamp-title">はっけん スタンプ <small>{solvedGames}/{GAMES.length}</small></h2><div className="stamp-grid">{GAMES.map(g=>{const got=(progress.games[g.id]?.correct||0)>0,c=CATEGORIES.find(c=>c.id===g.category)!,Icon=icons[g.category];return <button key={g.id} className={`stamp ${got?'earned':''}`} onClick={()=>select(g)} style={{'--card-color':c.color,'--card-pale':c.pale} as React.CSSProperties}><span>{got?<Star fill={c.color}/>:<Icon/>}</span><b>{g.name}</b><small>{got?`${progress.games[g.id].correct}もん`:'あそんで みよう'}</small></button>;})}</div></section>}
  </main>
  <nav className="bottom-nav" aria-label="メインメニュー"><button className={tab==='play'?'active':''} onClick={()=>setTab('play')}><Gamepad2 size={23}/><span>あそぶ</span></button><button className={tab==='records'?'active':''} onClick={()=>setTab('records')}><Trophy size={23}/><span>きろく</span></button><span className="nav-divider"/><button onClick={()=>{setSoundOn(!soundOn);try{localStorage.setItem('hirameki-sound',soundOn?'off':'on');}catch{}}}>{soundOn?<Volume2 size={22}/>:<VolumeX size={22}/>}<span>おと {soundOn?'ON':'OFF'}</span></button></nav>
  <Dialog open={!!selected} onOpenChange={v=>{if(!v){setSelected(null);setStagePicker(false);}}}><DialogContent className={`game-dialog setup-dialog ${stagePicker?'stage-dialog':''}`}><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.help}</DialogDescription>{selected&&<>{tutorialOpen?<><Tutorial id={selected.id}/><button className="secondary-button" onClick={()=>setTutorialOpen(false)}>もどる</button></>:stagePicker?<><button className="text-button back-stages" onClick={()=>setStagePicker(false)}><ArrowLeft size={16}/>もどる</button><div className="course-stage-list">{coursePhases(selected.id).map(phase=><section key={phase.theme} className="course-chapter"><h3><span>{phase.theme}</span>{phase.goal}</h3><div className="stage-grid">{Array.from({length:phase.end-phase.start+1},(_,j)=>{const i=phase.start-1+j,info=stageInfo(selected.id,i+1);return <button key={i} onClick={()=>{setStage(i+1);setStagePicker(false);}} title={`テーマ ${info.theme} ${info.mission}`} aria-label={`ステージ ${i+1} ${info.mission}`} className={stage===i+1?'active':''}><b>{i+1}</b><span>{progress.games[selected.id]?.stages?.[i+1]?'★'.repeat(progress.games[selected.id].stages[i+1]):'· · ·'}</span></button>;})}</div></section>)}</div></>:<><div className="setup-preview"><PuzzleView p={mode==='stage'?generateStage(selected.id,stage,0):generate(selected.id,level,14)} demo/></div><Tabs value={mode} onValueChange={v=>setMode(v as Mode)}><TabsList className="mode-tabs setup-modes"><TabsTrigger value="stage"><Flag size={16}/>ステージ</TabsTrigger><TabsTrigger value="timed"><Clock size={16}/>3ぷん</TabsTrigger><TabsTrigger value="free"><InfinityIcon size={16}/>じっくり</TabsTrigger></TabsList></Tabs>{mode==='stage'?<button className="stage-selector" onClick={()=>setStagePicker(true)}><span>ステージ <b>{stage}</b> <small>/ {stageCount(selected.id)}</small></span><span>{LEVEL_NAMES[stageInfo(selected.id,stage).theme-1]}<Grid2X2 size={19}/></span></button>:<label className="level-selector">むずかしさ <select value={level} onChange={e=>setLevel(Number(e.target.value))}>{Array.from({length:20},(_,i)=><option key={i} value={i+1}>Lv.{i+1} {LEVEL_NAMES[Math.floor(i/4)]}</option>)}</select></label>}<>{mode==='stage'&&<div className="lesson-card"><span>テーマ {stageInfo(selected.id,stage).theme} ・ {stageInfo(selected.id,stage).mission}</span><strong>{stageInfo(selected.id,stage).goal}</strong></div>}</><p className="mode-explanation">{mode==='stage'?'10もんで クリア。じかんは むせいげん。':mode==='timed'?'3ぷんで いくつ できるかな？できたら レベルアップ。':'じかんを きにせず、なんもんでも。'}</p><button className="primary-button" onClick={()=>start(selected,mode,stage,mode==='stage'?stageInfo(selected.id,stage).level:level)}><Play size={19} fill="currentColor"/>あそぶ</button><button className="secondary-button tutorial-open" onClick={()=>setTutorialOpen(true)}><Play size={17}/>うごく おてほん</button><button className="read-help" onClick={()=>speak(selected.help)}><Volume2 size={17}/>あそびかたを きく</button></>}</>}</DialogContent></Dialog>
  <Dialog open={!!result} onOpenChange={v=>{if(!v)setResult(null);}}><DialogContent className="game-dialog result-dialog"><DialogTitle>{result&&result.correct>0?'よく かんがえたね！':'また チャレンジしよう！'}</DialogTitle><DialogDescription>{result?GAMES.find(g=>g.id===result.game)?.name:''}</DialogDescription><img className="result-mascot" src={MASCOT} alt=""/>{result&&<>{result.mode==='stage'&&<div className="result-stars">{[1,2,3].map(i=><Star key={i} fill={i<=earnedStars(result)?'#ffc84a':'#e5eaed'} stroke={i<=earnedStars(result)?'#e3a829':'#d8e0e6'}/>)}</div>}<div className="result-score"><b>{result.correct}</b><span>もん できた！</span></div><p className="result-message">{result.mode==='stage'&&result.correct===10?'ステージ クリア！':result.mode==='stage'?'ここまで よく かんがえたね。':'じぶんで かんがえるって、おもしろいね。'}</p><p className={`save-state ${saveState}`} aria-live="polite">{saveState==='saved'?<><Check size={15}/>きろくを ほぞんしたよ</>:saveState==='saving'?'きろくを ほぞんちゅう…':<button onClick={()=>void save(result)}>保存できませんでした。もういちど 保存</button>}</p><button className="primary-button" onClick={()=>{const g=GAMES.find(g=>g.id===result.game)!;const next=result.mode==='stage'&&result.correct===10?Math.min(stageCount(g.id),result.stage+1):result.stage;start(g,result.mode,next,result.mode==='stage'?stageInfo(g.id,next).level:result.level);}}><Play size={18} fill="currentColor"/>{result.mode==='stage'&&result.correct===10&&result.stage<stageCount(result.game)?'つぎの ステージ':'もういちど あそぶ'}</button><button className="text-button" onClick={()=>setResult(null)}><Home size={17}/>ゲームを えらぶ</button></>}</DialogContent></Dialog>
  <Dialog open={profiles} onOpenChange={setProfiles}><DialogContent className="game-dialog"><DialogTitle>だれが あそぶ？</DialogTitle><DialogDescription>きろくは それぞれに のこるよ。</DialogDescription><div className="profile-grid">{PROFILE_NAMES.map((name,i)=><button key={i} className={profile===i+1?'selected':''} onClick={()=>{setProfile(i+1);setProfiles(false);}}><Glyph value={i} size={48}/><span>{name}</span>{profile===i+1&&<Check size={18}/>}</button>)}</div></DialogContent></Dialog>
  <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="game-dialog settings-dialog"><DialogTitle>おうちのかたへ</DialogTitle><DialogDescription>遊び方とアプリについて</DialogDescription><div className="setting-row"><label htmlFor="sound">効果音</label><Switch id="sound" checked={soundOn} onCheckedChange={v=>{setSoundOn(v);try{localStorage.setItem('hirameki-sound',v?'on':'off');}catch{}}}/></div><p>5分野・120種類。各ゲームの5つのテーマを順に進めます。1ステージ10問で、内容の異なる問題を最大80ステージまで用意しました。問題の種類が限られるゲームは、同じ問題で数を埋めず、ステージ数を調整しています。条件や必要な操作をもとに出題順を組み、新しい考え方は基本から始めます。</p><p>広告・課金・1日の回数制限はありません。「じっくり」は時間無制限、「3ぷん」は成績に合わせてレベルが変わります。ヒントを使ってもクリアできます。</p><p>家族6人分の記録を、このブラウザ・この端末に保存します。ブラウザのデータ削除で記録が消えるため、定期的にバックアップを書き出してください。別の端末ではバックアップを読み込むと続きから遊べます。Sites版の記録は自動では引き継がれません。</p><div className="backup-tools"><button className="secondary-button" disabled={backupBusy} onClick={()=>void downloadBackup()}>6人分のきろくを 書き出す</button><button className="secondary-button" disabled={backupBusy||pending.length>0} onClick={()=>importInput.current?.click()}>バックアップを 読み込む</button><input type="file" accept=".json,application/json" hidden ref={importInput} onChange={e=>{const file=e.target.files?.[0];if(file)void restoreBackup(file);}}/><p>読み込んだ記録を追加します。今ある記録は残り、同じ記録は重複しません。音・お気に入りの設定はこの端末で選び直してください。</p><p role="status">{backupMessage}</p></div><details><summary>iPhone・iPadで使う</summary><p>Safariで開き、「共有」から「ホーム画面に追加」で起動しやすくできます。縦画面・横画面のどちらでも遊べます。読み上げ音声は端末の対応状況によります。</p></details><button className="secondary-button" onClick={()=>{void load();setSettings(false);}}><RotateCcw size={17}/>きろくを 再読み込み</button></DialogContent></Dialog>
 </div>;
}
