'use client';
import React,{useEffect,useState,useRef}from'react';
import{Undo2,RotateCcw,Check,RotateCw}from'lucide-react';
import{type Puzzle,range,rotate,key,equal,adjacent}from'@/lib/engine/shared';
import{checkExtended,initialExtended}from'@/lib/engine/extended';
import{trialStep,replayTrial,trialGoal}from'@/lib/engine/trial';
import{beamTrace,tileEdges}from'@/lib/engine/plane';
import{canExtract}from'@/lib/engine/space';
import{SceneView,SymbolCard,MiniGrid}from'./scene';
import{TrialBoard}from'./trial-board';
import{Shape}from'./puzzle-art';
const COLORS=['#2ba994','#e6ac38','#8d76d5','#e67968','#629bd3','#d479b0'];
export function TouchBoard({n,rows=n,values,classes=[],onCell,drag=false,overlay}:{n:number;rows?:number;values:React.ReactNode[];classes?:string[];onCell:(i:number)=>void;drag?:boolean;overlay?:React.ReactNode}){const ref=useRef<HTMLDivElement>(null),active=useRef(false),last=useRef(-1);function pointer(e:React.PointerEvent){if(!active.current||!ref.current)return;const box=ref.current.getBoundingClientRect(),x=Math.floor((e.clientX-box.left)/box.width*n),y=Math.floor((e.clientY-box.top)/box.height*rows),at=y*n+x;if(x>=0&&x<n&&y>=0&&y<rows&&at!==last.current){last.current=at;onCell(at);}}return <div className={`touch-board ${drag?'drag-board':''}`} ref={ref} style={{gridTemplateColumns:`repeat(${n},minmax(0,1fr))`}} onPointerDown={drag?e=>{active.current=true;last.current=-1;e.currentTarget.setPointerCapture(e.pointerId);pointer(e);}:undefined} onPointerMove={drag?pointer:undefined} onPointerUp={()=>active.current=false} onPointerCancel={()=>active.current=false}>{overlay}{values.map((v,i)=><button type="button" key={i} onClick={()=>{if(!drag||last.current!==i)onCell(i);}} className={`board-cell ${classes[i]||''}`} aria-label={`${Math.floor(i/n)+1}ぎょう ${i%n+1}れつ`}>{v}</button>)}</div>;}
export function ConnectorTile({edges,label}:{edges:number[];label?:string}){return <span className="connector-tile"><b>{label}</b>{edges.map((v,i)=><small className={`connector-side side-${i}`} key={i}>{v>0?'+':''}{v}</small>)}</span>;}
function VoxelPieces({pieces,removed}:{pieces:any[];removed:number[]}){const cells:{v:number[];id:number}[]=pieces.flatMap((p,i)=>removed.includes(i)?[]:p.cells.map((v:number[])=>({v,id:i}))),iso=([x,y,z]:number[])=>[(x-y)*24,(x+y)*12-z*28],corners=cells.flatMap(({v:[x,y,z]})=>[[x,y,z],[x+1,y+1,z],[x,y,z+1]]).map(iso);if(!cells.length)return <div className="empty-pieces">✓ ぜんぶ ぬけた！</div>;const minX=Math.min(...corners.map(v=>v[0]))-32,minY=Math.min(...corners.map(v=>v[1]))-20,maxX=Math.max(...corners.map(v=>v[0]))+32,maxY=Math.max(...corners.map(v=>v[1]))+25,pts=(a:number[][])=>a.map(v=>iso(v).join(',')).join(' ');return <svg viewBox={`${minX} ${minY} ${maxX-minX} ${maxY-minY}`} className="voxel-pieces" aria-hidden="true">{cells.sort((a,b)=>a.v.reduce((s,v)=>s+v,0)-b.v.reduce((s,v)=>s+v,0)).map(({v:[x,y,z],id},i)=><g key={i} stroke="#385264" strokeWidth=".7"><polygon points={pts([[x+1,y,z],[x+1,y+1,z],[x+1,y+1,z+1],[x+1,y,z+1]])} fill={COLORS[id%6]}/><polygon points={pts([[x,y+1,z],[x+1,y+1,z],[x+1,y+1,z+1],[x,y+1,z+1]])} fill={COLORS[id%6]}/><polygon points={pts([[x,y,z+1],[x+1,y,z+1],[x+1,y+1,z+1],[x,y+1,z+1]])} fill={COLORS[id%6]}/><text x={iso([x+.5,y+.5,z+1])[0]} y={iso([x+.5,y+.5,z+1])[1]+4} textAnchor="middle" stroke="none" fontWeight="900" fontSize="12" fill="white">{id+1}</text></g>)}</svg>;}
export function scaleDisplayScenes(options:any[]):any[]{
 const shapes=options.filter(o=>o?.type==='shape');
 const extent=Math.max(1,...shapes.flatMap(o=>[o.extent||0,...o.cells.flatMap(([x,y]:number[])=>[x+1,y+1])]));
 return options.map(o=>o?.type==='shape'?{...o,extent}:o);
}
export function ExtendedPuzzleView({p,onAnswer,locked=false,hint=false,demo=false,playbackAnswer}:{p:Puzzle;onAnswer?:(a:any)=>void;locked?:boolean;hint?:boolean;demo?:boolean;playbackAnswer?:any}){
 const[answer,setAnswer]=useState<any>(()=>playbackAnswer??initialExtended(p)),[history,setHistory]=useState<any[]>([]),[selected,setSelected]=useState<number|null>(null),[color,setColor]=useState(0),[q,setQ]=useState(0),[notice,setNotice]=useState(''),[marks,setMarks]=useState<number[]>([]),[markMode,setMarkMode]=useState(false),[tileFlips,setTileFlips]=useState<boolean[]>([]),[layers,setLayers]=useState(false);
 const ref=useRef(answer),submitted=useRef(false),{data:d,kind,id}=p;
 useEffect(()=>{const a=playbackAnswer??initialExtended(p);setAnswer(a);ref.current=a;setHistory([]);setSelected(null);setColor(0);setQ(0);setNotice('');setMarks([]);setMarkMode(false);setTileFlips([]);setLayers(false);submitted.current=false;},[p]);
 useEffect(()=>{if(playbackAnswer!==undefined){setAnswer(playbackAnswer);ref.current=playbackAnswer;}},[playbackAnswer]);
 function update(a:any,auto=true){if(locked||demo||submitted.current)return;setHistory(h=>[...h.slice(-150),ref.current]);ref.current=a;setAnswer(a);setNotice('');if(auto&&checkExtended(p,a)){submitted.current=true;onAnswer?.(a);}}
 function submit(a=ref.current){if(locked||demo||submitted.current)return;if(checkExtended(p,a))submitted.current=true;onAnswer?.(a);}
 function reset(){if(locked||demo)return;const a=initialExtended(p);ref.current=a;setAnswer(a);setHistory([]);setSelected(null);setNotice('');setMarks([]);submitted.current=false;}
 function undo(){if(locked||demo||!history.length)return;const a=history.at(-1);ref.current=a;setAnswer(a);setHistory(history.slice(0,-1));setSelected(null);setNotice('');submitted.current=false;}
 function toggle(i:number,limit?:number){const a=ref.current.includes(i)?ref.current.filter((v:number)=>v!==i):[...ref.current,i];if(limit&&a.length>limit)return;update(a,false);}
 function invalid(message='そこには うごかせないよ。べつの てを ためそう。'){if(!demo&&!locked)setNotice(message);}
 function trialMove(action:any){const state=replayTrial(p,ref.current),next=trialStep(p,state,action);if(next===null){const messages:Record<string,string>={hanoi:'ちいさい リングの うえに、おおきい リングは おけないよ。',river:'けんかする ふたりが のこるか、ふねが いっぱいだよ。',colorsort:'からの ボトルか、おなじ しるしの うえへ。',trainyard:'せんとうか いちばん うえから。でぐちは つぎの ばんごうだけ。',ballweigh:action?.guess!==undefined?'まだ ほかの こうほが あるよ。はかって ひとつに しぼろう。':'ひだりと みぎを おなじ かずに。のこりの かいすうも たしかめよう。',codebreak:'おなじ しるしは 1かいだけ つかおう。',matchsticks:'てすうを こえたら「もどす」で やりなおせるよ。',flood:'てすうを こえたら「もどす」で かんがえなおそう。'};invalid(messages[id]);return;}update([...ref.current,action]);}
 const sequence=(a:number[],values:any[])=> <div className="arranged-slots">{range(values.length).map(i=><button type="button" key={i} disabled={a[i]===undefined} onClick={()=>update(a.filter((_,j)=>j!==i),false)}>{a[i]===undefined?'·':values[a[i]]}</button>)}</div>;
 let board:React.ReactNode=null;
 if(kind==='visual-choice'){
  const displayOptions=id==='scale'?scaleDisplayScenes(p.options!):p.options!;
  board=<><SceneView s={d.scene} questionText={d.prompt}/>{p.options!.some(o=>o?.type==='cubes')&&<button type="button" className="text-action" onClick={()=>setLayers(v=>!v)}>{layers?'だんの ずを とじる':'ピースを だんべつに みる'}</button>}<div className="extended-options">{displayOptions.map((opt,i)=>{
   const identifier=typeof opt==='string'&&/^[A-Z]$/.test(opt)?opt:undefined;
   return <button key={i} type="button" className={`extended-option ${answer===i?'chosen':''} ${playbackAnswer===i?'demo-focus':''}`} onClick={()=>{setAnswer(i);submit(i);}} aria-label={`こたえ ${identifier??i+1}`}><SceneView s={opt?.type==='cubes'?{...opt,showLayers:layers}:opt} compact/>{!identifier&&<span className="option-letter">{String.fromCharCode(65+i)}</span>}</button>;
  })}</div></>;
 }
 else if(kind==='trial'){const state=replayTrial(p,Array.isArray(answer)?answer:[])??d.initial;board=<TrialBoard p={p} state={state} actions={answer} playback={playbackAnswer!==undefined} hint={hint} demo={demo} onMove={trialMove} onProgram={actions=>{const s=replayTrial(p,actions);if(s===null){invalid('かべに あたるか、めいれいが おおすぎるよ。');return;}update(actions,false);submit(actions);}}/>;}
 else if(kind==='coins')board=<><SceneView s={d.scene}/><div className="coin-selector">{d.denoms.map((v:number,i:number)=><div key={i}><button type="button" className="coin" onClick={()=>{const a=[...ref.current];a[i]++;update(a,false);}}>{v}</button><div><button type="button" aria-label={`${v}えんを へらす`} disabled={!answer[i]} onClick={()=>{const a=[...ref.current];a[i]--;update(a,false);}}>−</button><b>{answer[i]}</b></div></div>)}</div><div className="scene-tag">{answer.reduce((s:number,v:number,i:number)=>s+v*d.denoms[i],0)}えん / {answer.reduce((s:number,v:number)=>s+v,0)}まい</div></>;
 else if(kind==='pairselect'||kind==='multiselect'||kind==='arrange'){board=<><SceneView s={d.scene}/>{kind==='arrange'&&sequence(answer,d.values)}<div className="number-cards">{d.values.map((v:any,i:number)=><button type="button" key={i} className={answer.includes(i)?'selected':''} onClick={()=>{if(kind==='arrange'){if(answer.includes(i))update(answer.filter((j:number)=>j!==i),false);else update([...answer,i]);}else toggle(i,kind==='pairselect'?2:undefined);}}>{v}</button>)}</div></>;}
 else if(kind==='operators')board=<><SceneView s={d.scene}/><div className="operator-equation"><span>{'('.repeat(d.values.length-2)}</span>{d.values.map((v:number,i:number)=><React.Fragment key={i}><strong>{v}</strong>{i>0&&i<d.values.length-1&&<span>)</span>}{i<d.values.length-1&&<button type="button" onClick={()=>{const a=[...answer];a[i]=d.available[(d.available.indexOf(a[i])+1)%d.available.length];update(a,false);}}>{answer[i]}</button>}</React.Fragment>)}</div><small>かっこの なかから、ひだりじゅんに</small></>;
 else if(kind==='binary-grid'){const clue=(v:any)=>Array.isArray(v)?v.join(' '):v,hasClues=d.rows&&d.cols;board=<><SceneView s={d.scene}/>{id==='binary'&&<small>○と●は はんぶんずつ。3つ れんぞくは ダメ。</small>}{id==='islands'&&<small>ぬった マス＝うみ。しまは すうじと おなじ ひろさ。</small>}{id==='minestars'&&<small>すうじ＝まわりの 8ますに ある ★の かず</small>}<div className={`clue-board-wrap ${hasClues?'has-clues':''}`} style={hasClues?{gridTemplateColumns:`42px 1fr`}:undefined}>{hasClues&&<><span/><div className="col-clues" style={{gridTemplateColumns:`repeat(${d.n},1fr)`}}>{d.cols.map((v:any,i:number)=><b key={i}>{Array.isArray(v)?v.map((x:number,j:number)=><span key={j}>{x}</span>):v}</b>)}</div><div className="row-clues" style={{gridTemplateRows:`repeat(${d.n},1fr)`}}>{d.rows.map((v:any,i:number)=><b key={i}>{clue(v)}</b>)}</div></>}<TouchBoard n={d.n} values={answer.map((v:number,i:number)=>id==='minestars'?(d.given[i]===0?<span className={`mine-number mine-${d.counts[i]}`}>{d.counts[i]}</span>:v?'★':marks.includes(i)?'×':''):id==='tents'?(d.trees.includes(i)?'♣':v?'△':marks.includes(i)?'×':''):id==='islands'?(d.clues[i]|| (v?'≈':marks.includes(i)?'×':'')):id==='binary'?(v<0?'·':v?'●':'○'):(v?'●':marks.includes(i)?'×':''))} classes={answer.map((v:number,i:number)=>`${d.given[i]>=0?'given-cell':''} ${v===1?'filled-cell':''}`)} onCell={i=>{if(d.given[i]>=0)return;if(markMode){setMarks(a=>a.includes(i)?a.filter(v=>v!==i):[...a,i]);return;}const a=[...ref.current];a[i]=id==='binary'?(a[i]+2)%3-1:1-a[i];update(a);}}/></div>{id!=='binary'&&<div className="control-row"><button type="button" className={!markMode?'selected':''} onClick={()=>setMarkMode(false)}>ぬる</button><button type="button" className={markMode?'selected':''} onClick={()=>setMarkMode(true)}>× メモ</button></div>}</>;}
 else if(kind==='edge-grid'){const maxX=Math.max(...d.nodes.map((v:number[])=>v[0])),maxY=Math.max(...d.nodes.map((v:number[])=>v[1])),w=320,h=Math.max(220,300*maxY/Math.max(1,maxX)),xy=(at:number)=>[25+d.nodes[at][0]/Math.max(1,maxX)*(w-50),25+d.nodes[at][1]/Math.max(1,maxY)*(h-50)];board=<><svg className="edge-board" viewBox={`0 0 ${w} ${h}`} role="group" aria-label="せんを えらぶ ばんめん">{d.clues&&range(d.n*d.n).map(i=><text key={i} x={25+(i%d.n+.5)/d.n*(w-50)} y={30+(Math.floor(i/d.n)+.5)/d.n*(h-50)} textAnchor="middle" fontSize="20">{d.clues[i]}</text>)}{d.edges.map(([u,v]:number[],i:number)=>{const a=xy(u),b=xy(v),count=answer[i],mx=(a[0]+b[0])/2,my=(a[1]+b[1])/2;return <g key={i}><path d={`M${a}L${b}`} fill="none" stroke={count?'#258e91':'#d5e0e8'} strokeWidth={count?8:3} strokeLinecap="round"/>{count===2&&<path d={`M${a}L${b}`} stroke="white" strokeWidth="2"/>}{d.weights&&<g><rect x={mx-13} y={my-12} width="26" height="24" rx="8" fill={count?'#218f89':'#fff'}/><text x={mx} y={my+5} textAnchor="middle" fontSize="14" fill={count?'white':'#51697a'}>{d.weights[i]}</text></g>}<path d={`M${a}L${b}`} stroke="transparent" strokeWidth="25" role="button" tabIndex={0} aria-label={`${u+1}と${v+1}の せん ${count}ほん`} onClick={()=>{const a=[...answer];a[i]=(a[i]+1)%(d.max+1);update(a);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();const a=[...answer];a[i]=(a[i]+1)%(d.max+1);update(a);}}}/></g>;})}{d.nodes.map((_:any,i:number)=>{const[x,y]=xy(i);return <g key={i} pointerEvents="none"><circle cx={x} cy={y} r={d.degrees?19:d.weights?13:5} fill={d.degrees||d.weights?'#fff':'#638699'} stroke="#7195a8" strokeWidth="2"/>{(d.degrees||d.weights)&&<text x={x} y={y+6} textAnchor="middle" fontSize={d.degrees?20:12}>{d.degrees?d.degrees[i]:i+1}</text>}</g>;})}</svg>{d.weights&&<div className="scene-tag">ながさ {answer.reduce((s:number,v:number,i:number)=>s+v*d.weights[i],0)} / おだい {d.minimum}</div>}<small>{id==='loopclues'?'ひとつの わっかに しよう':id==='bridges'?'しまの すうじと おなじ ほんすう。ぜんぶの しまを つなごう':'いちばん みじかく、ぜんぶを つなごう'}</small></>;}
 else if(kind==='assignment')board=<><SceneView s={d.scene}/><div className="assignment-rows">{d.allowed.map((allowed:number[],i:number)=><div key={i}><b>{String.fromCharCode(65+i)}</b>{range(d.n).map(v=><button type="button" key={v} disabled={!allowed.includes(v)} className={answer[i]===v?'selected':''} onClick={()=>{const a=[...answer];a[i]=a[i]===v?-1:v;update(a);}}>{v+1}</button>)}</div>)}</div></>;
 else if(kind==='card-select')board=<><SceneView s={d.scene}/><div className={`symbol-options ${id==='parallel'?'parallel-options':''}`}>{d.cards.map((s:any,i:number)=><button type="button" key={i} className={answer.includes(i)?'selected':''} onClick={()=>toggle(i,id==='settriple'?3:undefined)} aria-label={`カード ${i+1}`}><SceneView s={s} compact/><small>{i+1}</small></button>)}</div></>;
 else if(kind==='switches')board=<><SceneView s={d.scene}/><div className="scene-tag">ONは {d.required}こ</div><div className="switch-inputs">{answer.map((v:number,i:number)=><button type="button" key={i} className={v?'selected':''} onClick={()=>{const a=[...answer];a[i]=1-a[i];update(a);}}><b>{String.fromCharCode(65+i)}</b><span>{v?'ON':'OFF'}</span></button>)}</div></>;
 else if(kind==='domino-chain'){const val=answer.order?answer:{order:[],flips:[]};board=<><SceneView s={d.scene}/><div className="domino-chain"><b>{d.start} →</b>{val.order.map((at:number,j:number)=><button type="button" key={j} onClick={()=>update({order:val.order.slice(0,j),flips:val.flips.slice(0,j)},false)}>{(val.flips[j]?[...d.tiles[at]].reverse():d.tiles[at]).join('│')}</button>)}<b>→ {d.end}</b></div><div className="domino-bank">{d.tiles.map((tile:number[],i:number)=><div key={i}><button type="button" disabled={val.order.includes(i)} onClick={()=>update({order:[...val.order,i],flips:[...val.flips,!!tileFlips[i]]})}>{(tileFlips[i]?[...tile].reverse():tile).join('│')}</button><button type="button" disabled={val.order.includes(i)} onClick={()=>setTileFlips(a=>range(d.tiles.length).map(j=>i===j?!a[j]:!!a[j]))} aria-label={`${i+1}ばんの ドミノを まわす`}>↶</button></div>)}</div></>;}
 else if(kind==='extract'){const removed=Array.isArray(answer)?answer:[],all=d.pieces.flatMap((piece:any)=>piece.cells),n=Math.max(...all.flatMap((v:number[])=>v.slice(0,2)))+1,h=Math.max(...all.map((v:number[])=>v[2]))+1;board=<><VoxelPieces pieces={d.pieces} removed={removed}/><div className="extract-controls">{d.pieces.map((piece:any,i:number)=>{const axis=piece.dir.findIndex((v:number)=>v!==0);return <button type="button" key={i} disabled={removed.includes(i)} style={{borderColor:COLORS[i%6]}} onClick={()=>{if(canExtract(d.pieces,removed,i))update([...removed,i]);else invalid('その むきには べつの ピースが あるよ。');}}><b style={{background:COLORS[i%6]}}>{removed.includes(i)?'✓':i+1}</b>{['よこ','おく','うえ'][axis]} {piece.dir[axis]>0?'＋':'−'}</button>;})}</div><button type="button" className="text-action" onClick={()=>setLayers(v=>!v)}>{layers?'だんの ずを とじる':'だんべつに みる'}</button>{layers&&<div className="layer-panels">{range(h).map(z=><div key={z}><small>{z+1}だんめ</small><MiniGrid n={n} values={range(n*n).map(at=>{const piece=d.pieces.findIndex((p:any,i:number)=>!removed.includes(i)&&p.cells.some(([x,y,zz]:number[])=>zz===z&&y*n+x===at));return piece<0?'':<span style={{color:COLORS[piece%6]}}>{piece+1}</span>;})}/></div>)}</div>}<small>よこ＋＝X →　おく＋＝Y ↙　うえ＋＝Z ↑</small></>;}
 else if(kind==='tiling'){const occupied=new Map<number,number>();answer.forEach((v:any)=>rotate(d.pieces[v.piece],v.q).forEach(([x,y])=>occupied.set((y+v.y)*d.n+x+v.x,v.piece)));board=<><TouchBoard n={d.n} rows={d.rows} values={range(d.n*d.rows).map(i=>occupied.has(i)?<span className="tile-fill" style={{background:COLORS[occupied.get(i)!%6]}}>{occupied.get(i)!+1}</span>:null)} onCell={at=>{if(selected===null){if(occupied.has(at)){setSelected(occupied.get(at)!);setQ(answer.find((v:any)=>v.piece===occupied.get(at))?.q||0);}return;}const placement={piece:selected,x:at%d.n,y:Math.floor(at/d.n),q},cells=rotate(d.pieces[selected],q);if(cells.some(([x,y])=>x+placement.x>=d.n||y+placement.y>=d.rows||occupied.has((y+placement.y)*d.n+x+placement.x)&&occupied.get((y+placement.y)*d.n+x+placement.x)!==selected)){invalid('はみだすか、ほかの ピースと かさなるよ。');return;}update([...answer.filter((v:any)=>v.piece!==selected),placement]);setSelected(null);}}/><div className="piece-bank">{d.pieces.map((cells:number[][],i:number)=><button type="button" key={i} className={selected===i?'selected':''} onClick={()=>{setSelected(selected===i?null:i);setQ(answer.find((v:any)=>v.piece===i)?.q||0);}}><Shape cells={rotate(cells,selected===i?q:0)} color={COLORS[i%6]}/><small>{i+1}{answer.some((v:any)=>v.piece===i)?' ✓':''}</small></button>)}</div><div className="control-row"><button type="button" disabled={selected===null} onClick={()=>setQ(v=>(v+1)%4)}><RotateCw size={18}/> まわす</button><button type="button" disabled={selected===null} onClick={()=>update(answer.filter((v:any)=>v.piece!==selected),false)}>はずす</button></div><small>ピースの ひだりうえを、タッチした マスに あわせるよ。</small></>;}
 else if(kind==='district'||kind==='region-color'){const n=d.n,rows=d.rows||n,regions=kind==='district'?range(n*rows):d.regions,k=kind==='district'?d.k:(d.colors??4);board=<><div className="paint-palette">{range(k).map(i=><button type="button" key={i} className={color===i?'selected':''} style={{background:COLORS[i]}} onClick={()=>setColor(i)}>{i+1}</button>)}</div><TouchBoard n={n} rows={rows} values={regions.map((r:number,at:number)=>{const v=answer[r],home=kind==='district'?d.homes.indexOf(at):-1;return <span className="region-fill" style={{background:v>=0?COLORS[v]+'c5':'#edf2f5',borderTop:at<n||regions[at-n]!==r?'2px solid #53667d':'none',borderLeft:at%n===0||regions[at-1]!==r?'2px solid #53667d':'none'}}>{home>=0?<b>⌂{home+1}</b>:kind==='region-color'?<small>{r+1}</small>:v>=0?v+1:''}</span>;})} onCell={at=>{const r=regions[at];if(kind==='district'&&d.homes.includes(at)||kind==='region-color'&&d.initial[r]>=0)return;const a=[...answer];a[r]=color;update(a);}}/>{kind==='district'&&<div className="district-counts">{range(k).map(i=><span key={i}>⌂{i+1}：{answer.filter((v:number)=>v===i).length}/{d.n*d.rows/k}</span>)}</div>}</>;}
 else if(kind==='fold-grid')board=<><SceneView s={d.scene}/><TouchBoard n={d.n} values={answer.map((v:number)=>v?'●':'')} classes={answer.map((v:number)=>v?'filled-cell':'')} onCell={i=>{const a=[...answer];a[i]=1-a[i];update(a);}}/></>;
 else if(kind==='pairpaths'){const vals=range(d.n*d.n).map(at=>{const pair=d.pairs.findIndex((ends:number[])=>ends.includes(at)),path=answer.findIndex((a:number[])=>a.includes(at));return pair>=0?<span className="pair-end" style={{background:COLORS[pair]}}>{pair+1}</span>:path>=0?<span className="path-dot" style={{background:COLORS[path]}}/>:null;}),overlay=<svg className="board-overlay" viewBox={`0 0 ${d.n*100} ${d.n*100}`} aria-hidden="true">{answer.map((path:number[],i:number)=><polyline key={i} points={path.map(at=>`${at%d.n*100+50},${Math.floor(at/d.n)*100+50}`).join(' ')} fill="none" stroke={COLORS[i]} strokeWidth="17" strokeLinejoin="round" strokeLinecap="round"/>)}</svg>;board=<><div className="paint-palette">{d.pairs.map((_:any,i:number)=><button type="button" key={i} className={color===i?'selected':''} style={{background:COLORS[i]}} onClick={()=>setColor(i)}>{i+1}</button>)}</div><TouchBoard n={d.n} values={vals} overlay={overlay} drag onCell={at=>{const a=ref.current.map((v:number[])=>[...v]),path=a[color],last=path.at(-1);if(path.length>1&&at===path.at(-2)){a[color].pop();update(a,false);return;}if(!adjacent(last,d.n).includes(at)||a.some((v:number[])=>v.includes(at))||d.pairs.some((ends:number[],i:number)=>i!==color&&ends.includes(at)))return;a[color].push(at);update(a);}}/><small>ペアを えらんで みちを なぞろう</small></>;}
 else if(kind==='chords'){const xy=(i:number)=>d.nodes[i].map((v:number)=>v*45+25),click=(i:number)=>{if(selected===null){setSelected(i);return;}if(selected===i){setSelected(null);return;}const e=[selected,i].sort((a,b)=>a-b);if(e[1]-e[0]===1||e[0]===0&&e[1]===d.n-1||d.banned.some((v:number[])=>equal(v,e))){invalid('その せんは ひけないよ。');setSelected(null);return;}update(answer.some((v:number[])=>equal(v,e))?answer.filter((v:number[])=>!equal(v,e)):[...answer,e]);setSelected(null);};board=<><svg className="geometry-art" viewBox="0 0 320 320"><polygon points={range(d.n).map(i=>xy(i).join(',')).join(' ')} fill="#f1ebf9" stroke="#a089bc" strokeWidth="3"/>{d.banned.map(([a,b]:number[],i:number)=><path key={'b'+i} d={`M${xy(a)}L${xy(b)}`} stroke="#e4b1af" strokeWidth="2" strokeDasharray="5 8"/>)}{answer.map(([a,b]:number[],i:number)=><path key={i} d={`M${xy(a)}L${xy(b)}`} stroke="#38a895" strokeWidth="4"/>)}{range(d.n).map(i=>{const[x,y]=xy(i);return <g key={i} role="button" tabIndex={0} aria-label={`${i+1}ばんの かど`} onClick={()=>click(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')click(i);}}><circle cx={x} cy={y} r="20" fill={selected===i?'#ffd778':'white'} stroke="#8095a8" strokeWidth="2"/><text x={x} y={y+6} fontSize="17" textAnchor="middle">{i+1}</text></g>;})}</svg><small>あと {Math.max(0,d.n-3-answer.length)}ほん</small></>;}
 else if(kind==='jigsaw'){const val=answer.slots?answer:d.initial;board=<><TouchBoard n={d.n} values={val.slots.map((i:number)=>i<0?'？':<ConnectorTile edges={tileEdges(d.tiles[i],val.turns[i])} label={String(i+1)}/>)} onCell={at=>{if(selected===null){if(val.slots[at]>=0)setSelected(val.slots[at]);return;}const slots=val.slots.map((v:number)=>v===selected?-1:v);slots[at]=selected;update({...val,slots});setSelected(null);}}/><div className="jigsaw-bank">{d.tiles.map((edges:number[],i:number)=><button type="button" key={i} className={selected===i?'selected':''} onClick={()=>setSelected(selected===i?null:i)}><ConnectorTile edges={tileEdges(edges,val.turns[i])} label={`${i+1}${val.slots.includes(i)?'✓':''}`}/></button>)}</div><button type="button" className="text-action" disabled={selected===null} onClick={()=>{const turns=[...val.turns];turns[selected!]=(turns[selected!]+1)%4;update({...val,turns});}}>↻ えらんだ ピースを まわす</button></>;}
 else if(kind==='mirrors'){const trace=beamTrace(d.n,d.mirrors,answer,d.row),points=[[-.5,d.row],...trace.cells.map(at=>[at%d.n,Math.floor(at/d.n)])];if(trace.exit){const e=trace.exit;points.push(e.side===0?[e.index,-.5]:e.side===1?[d.n-.5,e.index]:e.side===2?[e.index,d.n-.5]:[-.5,e.index]);}const marker={top:d.target.side===0?'−12px':d.target.side===2?'calc(100% - 12px)':`calc(${(d.target.index+.5)/d.n*100}% - 12px)`,left:d.target.side===3?'−12px':d.target.side===1?'calc(100% - 12px)':`calc(${(d.target.index+.5)/d.n*100}% - 12px)`};board=<><div className="mirror-board"><span className="beam-source" style={{top:`${(d.row+.5)/d.n*100}%`}}>→</span><span className="beam-goal" style={{...marker,top:marker.top.replace('−','-'),left:marker.left.replace('−','-')}}>★</span><TouchBoard n={d.n} values={range(d.n*d.n).map(at=>{const i=d.mirrors.indexOf(at);return i<0?null:<span className="mirror-piece">{answer[i]?'╲':'╱'}</span>;})} overlay={<svg className="board-overlay" viewBox={`0 0 ${d.n*100} ${d.n*100}`}><polyline points={points.map(([x,y])=>`${(x+.5)*100},${(y+.5)*100}`).join(' ')} fill="none" stroke="#eebc36" strokeWidth="8" strokeLinejoin="round"/></svg>} onCell={at=>{const i=d.mirrors.indexOf(at);if(i<0)return;const a=[...answer];a[i]=1-a[i];update(a);}}/></div>{trace.loop&&<small>ひかりが ぐるぐる しているよ</small>}</>;}
 else if(kind==='point-select'||kind==='separator'||kind==='parking'){const n=d.n||9,points=kind==='separator'?d.anchors:d.points,scale=260/n,xy=(p:number[])=>[30+p[0]*scale,30+p[1]*scale],selectedPoints=Array.isArray(answer)?answer:[],sampleRadius=kind==='parking'?d.radius*scale:0,sampleHeight=kind==='parking'?2*sampleRadius+50:0;let polygon:number[][]=kind==='point-select'&&id==='hull'&&answer.length>2?answer.map((i:number)=>d.points[i]):[];if(polygon.length){const cx=polygon.reduce((a,b)=>a+b[0],0)/polygon.length,cy=polygon.reduce((a,b)=>a+b[1],0)/polygon.length;polygon.sort((a,b)=>Math.atan2(a[1]-cy,a[0]-cx)-Math.atan2(b[1]-cy,b[0]-cx));}board=<>{kind==='parking'&&<div className="scene-tag">{answer.length} / {d.k}こ</div>}<svg className="geometry-art" viewBox={`0 0 320 ${320+sampleHeight}`} role={kind==='parking'?'group':undefined} aria-label={kind==='parking'?'円の大きさと配置する点':undefined}><rect x="30" y="30" width="260" height="260" rx="3" fill="#f6f9fb" stroke="#c5d7e1"/>{d.poly&&<polygon points={d.poly.map((v:number[])=>xy(v).join(',')).join(' ')} fill="#e8dcf7" stroke="#9674bc" strokeWidth="3"/>}{polygon.length>0&&<polygon points={polygon.map(v=>xy(v).join(',')).join(' ')} fill="#3bbaa125" stroke="#329b8b" strokeWidth="4"/>}{kind==='separator'&&d.points.map((p:number[],i:number)=>{const[x,y]=xy(p);return <text key={i} x={x} y={y+6} textAnchor="middle" fontSize="23" fill={d.groups[i]?'#d9a12a':'#5998cf'}>{d.groups[i]?'★':'●'}</text>;})}{kind==='separator'&&answer.length===2&&<path d={`M${xy(points[answer[0]])}L${xy(points[answer[1]])}`} stroke="#4c9f92" strokeWidth="4"/>}{kind==='parking'&&answer.map((i:number)=><circle key={i} cx={xy(points[i])[0]} cy={xy(points[i])[1]} r={d.radius*scale} fill="#44baa64a" stroke="#2f9f8d" strokeWidth="2"/>)}{kind==='parking'&&<g className="parking-size-key" aria-label="この大きさの円を枠の中へ。円どうしは接してもよく、重ならないように置こう"><circle className="parking-size-sample" cx="160" cy={332+sampleRadius} r={sampleRadius} fill="#44baa64a" stroke="#2f9f8d" strokeWidth="2"/><text x="160" y={320+sampleHeight-8} fontSize="12" textAnchor="middle" fill="#32566b">この おおきさ。わくの なかへ。</text></g>}{points.map((v:number[],i:number)=>{const[x,y]=xy(v),chosen=selectedPoints.includes(i);return <g key={i} role="button" tabIndex={0} aria-label={`${i+1}ばんの てん`} onClick={()=>toggle(i,kind==='separator'?2:kind==='parking'?d.k:undefined)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')toggle(i,kind==='separator'?2:undefined);}}><circle cx={x} cy={y} r="20" fill="transparent"/><circle cx={x} cy={y} r={kind==='separator'?13:9} fill={chosen?'#1a9f8b':'#fff'} stroke="#5c8b9f" strokeWidth="2"/><text x={x} y={y+4} fontSize="11" fontWeight="800" textAnchor="middle" fill={chosen?'#fff':'#32566b'}>{i+1}</text></g>;})}</svg><div className="point-buttons">{points.map((_:any,i:number)=><button type="button" key={i} className={answer.includes(i)?'selected':''} onClick={()=>toggle(i,kind==='separator'?2:kind==='parking'?d.k:undefined)}>{i+1}</button>)}</div></>;}
 return <div className={`extended-puzzle ${demo?'is-preview':''} game-${id}`}><fieldset disabled={locked||demo}>{board}</fieldset>{!demo&&kind!=='visual-choice'&&<div className="extended-actions"><button type="button" onClick={undo} disabled={!history.length||locked}><Undo2 size={17}/> もどす</button><button type="button" onClick={reset} disabled={locked}><RotateCcw size={17}/> やりなおす</button>{!['trial','extract','pairpaths','mirrors','tiling','fold-grid','district','region-color','switches','assignment'].includes(kind)&&<button type="button" className="done-action" onClick={()=>submit()} disabled={locked}><Check size={17}/> できた</button>}</div>}<div className="puzzle-notice" role="status" aria-live="polite">{notice}</div></div>;
}
