import React from 'react';
export const PALETTE=['#ffbd3e','#29b9a8','#5b9cef','#ed7865','#ae81db','#e88dc0'];
export function Glyph({value=0,size=44}:{value?:number;size?:number}){const v=((value%6)+6)%6;return <svg width={size} height={size} viewBox="0 0 50 50" aria-hidden="true"><g fill={PALETTE[v]} stroke="#25394c" strokeWidth="1.5" strokeLinejoin="round">{v===0?<circle cx="25" cy="25" r="16"/>:v===1?<path d="M25 6L45 42H5Z"/>:v===2?<rect x="9" y="9" width="32" height="32" rx="5"/>:v===3?<path d="M25 4L46 25L25 46L4 25Z"/>:v===4?<path d="M25 3L31 17L46 18L35 29L39 45L25 37L11 45L15 29L4 18L19 17Z"/>:<path d="M15 6H35L46 25L35 44H15L4 25Z"/>}</g></svg>}
export function Shape({cells,color='#aa7ad7',extent,grid=false}:{cells:number[][];color?:string;extent?:number;grid?:boolean}){if(!cells?.length)return null;const maxX=Math.max(...cells.map(p=>p[0]))+1,maxY=Math.max(...cells.map(p=>p[1]))+1,w=extent||maxX,h=extent||maxY;return <svg viewBox={`-0.2 -0.2 ${w+.4} ${h+.4}`} className="shape-art" aria-hidden="true">{grid&&Array.from({length:w*h},(_,i)=><rect key={i} x={i%w} y={Math.floor(i/w)} width="1" height="1" fill="none" stroke="#cbd5df" strokeWidth=".025"/>)}{cells.map(([x,y],i)=><rect key={i} x={x+.045} y={y+.045} width=".91" height=".91" rx=".12" fill={color} stroke="rgba(0,0,0,.14)" strokeWidth=".04"/> )}</svg>}
const iso=([x,y,z]:number[])=>[(x-y)*24,(x+y)*12-z*28];
const pts=(a:number[][])=>a.map(p=>iso(p).join(',')).join(' ');
export function Cubes({cells,rotation=0,front=false}:{cells:number[][];rotation?:number;front?:boolean}){let c=cells;for(let i=0;i<rotation%4;i++)c=c.map(([x,y,z])=>[-y,x,z]);const corners=c.flatMap(([x,y,z])=>[[x,y,z],[x+1,y,z],[x,y+1,z],[x+1,y+1,z],[x,y,z+1],[x+1,y,z+1],[x,y+1,z+1],[x+1,y+1,z+1]]).map(iso);const minX=Math.min(...corners.map(p=>p[0])),minY=Math.min(...corners.map(p=>p[1])),maxX=Math.max(...corners.map(p=>p[0])),maxY=Math.max(...corners.map(p=>p[1]));return <svg className="cube-art" viewBox={`${minX-20} ${minY-16} ${maxX-minX+40} ${maxY-minY+(front?50:32)}`} aria-hidden="true"><ellipse cx={(minX+maxX)/2} cy={maxY+3} rx={(maxX-minX)*.46} ry="9" fill="#263e5520"/>{[...c].sort((a,b)=>(a[0]+a[1]+a[2])-(b[0]+b[1]+b[2])).map(([x,y,z],i)=><g key={i} stroke="#167e78" strokeWidth=".85" strokeLinejoin="round"><polygon points={pts([[x+1,y,z],[x+1,y+1,z],[x+1,y+1,z+1],[x+1,y,z+1]])} fill="#169b90"/><polygon points={pts([[x,y+1,z],[x+1,y+1,z],[x+1,y+1,z+1],[x,y+1,z+1]])} fill="#3cc8b6"/><polygon points={pts([[x,y,z+1],[x+1,y,z+1],[x+1,y+1,z+1],[x,y+1,z+1]])} fill="#95ecda"/></g>)}{front&&<g transform={`translate(${minX+5} ${maxY+22})`}><path d="M0 5L18 -5M9 -5H18V4" fill="none" stroke="#258ed5" strokeWidth="4" strokeLinecap="round"/><text x="26" y="5" fontSize="10" fill="#2177b0">こちらから</text></g>}</svg>}
export function Polygon({n=3}:{n?:number}){const points=Array.from({length:n},(_,i)=>{const t=-Math.PI/2+i*2*Math.PI/n;return`${50+35*Math.cos(t)},${50+35*Math.sin(t)}`;}).join(' ');return <svg viewBox="0 0 100 100" className="polygon-art" aria-hidden="true"><polygon points={points} fill="#58c4a8" stroke="#1c857c" strokeWidth="3" strokeLinejoin="round"/></svg>}
export function SliceArt({poly,cutPoints,planeQuad,mode='outline',reveal=false}:{poly:number[][];cutPoints?:number[][];planeQuad?:number[][];mode?:string;reveal?:boolean}){
 const corners=Array.from({length:8},(_,i)=>[i&1,(i>>1)&1,(i>>2)&1]),full=reveal||mode==='outline',marks=full?poly:(cutPoints||poly.slice(0,3)),visibleEdge=(a:number[],b:number[])=>[0,1,2].some(i=>Math.abs(a[i]-1)<1e-6&&Math.abs(b[i]-1)<1e-6);
 return <svg className="slice-art" viewBox="-48 -48 96 100" aria-hidden="true"><polygon points={pts([[0,0,0],[1,0,0],[1,1,0],[0,1,0]])} fill="#d8e9f1"/>{mode==='plane'&&!full&&planeQuad&&<polygon points={pts(planeQuad)} fill="#35b99725" stroke="#079077" strokeWidth=".8" strokeDasharray="2 2"/>}{corners.flatMap((a,i)=>corners.map((b,j)=>j>i&&[1,2,4].includes(i^j)?<line key={`${i}-${j}`} x1={iso(a)[0]} y1={iso(a)[1]} x2={iso(b)[0]} y2={iso(b)[1]} stroke="#6b94b0" strokeWidth="1.1" strokeDasharray={i===0?'2 2':undefined}/>:null))}{full?<polygon points={pts(poly)} fill={reveal?'#35b997':'#35b99760'} stroke="#079077" strokeWidth="1.5"/>:mode==='partial'?poly.map((a,i)=>{const b=poly[(i+1)%poly.length];return visibleEdge(a,b)?<line key={i} x1={iso(a)[0]} y1={iso(a)[1]} x2={iso(b)[0]} y2={iso(b)[1]} stroke="#079077" strokeWidth="1.7"/>:null;}):null}{marks.map((v,i)=><g key={i}><circle cx={iso(v)[0]} cy={iso(v)[1]} r={full?'1.4':'2.1'} fill="#087464" stroke={full?'none':'white'} strokeWidth=".7"/>{!full&&<text x={iso(v)[0]+3} y={iso(v)[1]-2} fontSize="5" fill="#07644f">{i+1}</text>}</g>)}</svg>;
}
export function DotGroup({count,positions,small=false}:{count:number;positions?:number[];small?:boolean}){const cols=small?5:6,rows=Math.max(1,Math.ceil((positions?Math.max(...positions)+1:count)/cols));return <svg className="dot-art" viewBox={`0 0 ${cols*22} ${rows*22}`} aria-hidden="true">{Array.from({length:count},(_,i)=>{const at=positions?.[i]??i;return <circle key={i} cx={(at%cols)*22+11} cy={Math.floor(at/cols)*22+11} r={small?7:8} fill={PALETTE[Math.floor(i/5)%3]} stroke="#263e5520" strokeWidth="1.2"/>;})}</svg>}
