'use client';
import React,{useId}from'react';
import{Shape,Cubes,PALETTE}from'./puzzle-art';
import{range,normalize,type Scene}from'@/lib/engine/shared';
import{FRAMES}from'@/lib/engine/space';
const colors=['#27a991','#edac31','#8b70d9','#e97769','#579ade','#d77cb2'];
export const ARROWS=['↑','→','↓','←'];
export function SymbolCard({s}:{s:any}){const id=useId().replaceAll(':','');return <span className="symbol-card" role="img" aria-label={`${['まる','さんかく','しかく'][s.shape]}、色${s.color+1}、${s.count}こ`}><svg viewBox={`0 0 ${Math.max(1,s.count)*42} 48`}><defs><pattern id={id} width="6" height="6" patternUnits="userSpaceOnUse"><rect width="6" height="6" fill={colors[s.color]}/>{s.color===1?<path d="M0 2H6" stroke="#ffffff85" strokeWidth="2"/>:s.color===2?<circle cx="3" cy="3" r="1.3" fill="#ffffffad"/>:null}</pattern></defs>{range(s.count||1).map(i=><g key={i} transform={`translate(${i*42} 0)`} fill={`url(#${id})`} stroke="#365165" strokeWidth="1.5">{s.shape===0?<circle cx="21" cy="24" r="15"/>:s.shape===1?<path d="M21 7L38 39H4Z"/>:<rect x="6" y="9" width="30" height="30" rx="3"/>}</g>)}</svg></span>;}
export function MiniGrid({n,values,blocked=[],selected=[],onCell,rows,labels=false,className=''}:{n:number;values:any[];blocked?:number[];selected?:number[];onCell?:(i:number)=>void;rows?:number;labels?:boolean;className?:string}){return <div className={`diagram-grid ${className}`} style={{gridTemplateColumns:`repeat(${n},minmax(0,1fr))`}}>{values.map((v,i)=>{const props={className:`diagram-cell ${blocked.includes(i)?'wall':''} ${selected.includes(i)?'active':''}`,'aria-label':`${Math.floor(i/n)+1}ぎょう ${i%n+1}れつ${typeof v==='string'||typeof v==='number'?` ${v}`:''}`};return onCell?<button type="button" key={i} {...props} disabled={blocked.includes(i)} onClick={()=>onCell(i)}>{v==='●'?<span className="diagram-dot" role="img" aria-label="まる"/>:v}</button>:<span key={i} {...props}>{v==='●'?<span className="diagram-dot" role="img" aria-label="まる"/>:v}</span>;})}{labels&&<small style={{gridColumn:`span ${n}`}}>よこ →　おく ↓</small>}</div>;}
export function CubeLayers({cells}:{cells:number[][]}){const normalized=normalize(cells),n=Math.max(...normalized.flatMap(v=>v.slice(0,2)))+1,h=Math.max(...normalized.map(v=>v[2]))+1;return <div className="layer-panels cube-layer-details">{range(h).map(z=><div key={z}><small>{z+1}だんめ</small><MiniGrid n={n} values={range(n*n).map(i=>normalized.some(([x,y,zz])=>x===i%n&&y===Math.floor(i/n)&&zz===z)?'■':'')}/></div>)}</div>;}
export function Wire3D({points,branches=false,labels=true}:{points:number[][];branches?:boolean;labels?:boolean}){
 const iso=([x,y,z]:number[])=>[(x-y)*24,(x+y)*12-z*29],ps=points.map(iso),minX=Math.min(...ps.map(p=>p[0]))-25,minY=Math.min(...ps.map(p=>p[1]))-25,w=Math.max(...ps.map(p=>p[0]))-minX+25,h=Math.max(...ps.map(p=>p[1]))-minY+25;
 return <svg className="wire-art" viewBox={`${minX} ${minY} ${w} ${h}`} aria-hidden="true">
  {ps.slice(1).map((p,i)=>{const prev=ps[branches?0:i];return <line key={i} x1={prev[0]} y1={prev[1]} x2={p[0]} y2={p[1]} stroke={colors[i%colors.length]} strokeWidth="9" strokeLinecap="round"/>;})}
  {ps.slice(1).map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r="8" fill="white" stroke={colors[i%colors.length]} strokeWidth="3"/>)}
  {labels&&ps.slice(1).map((p,i)=><text key={i} x={p[0]} y={p[1]+3} textAnchor="middle" fontSize="10" fontWeight="800">{i+1}</text>)}
  <circle cx={ps[0][0]} cy={ps[0][1]} r="5" fill="#304a5d"/>
 </svg>;
}
function ruleWords(r:any):React.ReactNode{if(r.op==='not')return <span>「{ruleWords(r.child)}」ではない</span>;if(r.op==='and'||r.op==='or')return <span>（{ruleWords(r.left)} <strong>{r.op==='and'?'かつ':'または'}</strong> {ruleWords(r.right)}）</span>;return r.attr==='shape'?['○ まる','△ さんかく','□ しかく'][r.value]:r.attr==='color'?<span style={{color:colors[r.value]}}>色{r.value+1} {['みどり','きいろ','むらさき'][r.value]}</span>:`${r.value}こ`;}
function GridPoints({s}:{s:any}){const n=s.n||8;return <svg className="geometry-art" viewBox={`-1 -1 ${n+2} ${n+2}`} aria-hidden="true">{range(n+1).map(i=><g key={i} stroke="#dbe6ee" strokeWidth=".025"><path d={`M${i} 0V${n}M0 ${i}H${n}`}/></g>)}{s.poly&&<polygon points={s.poly.map((p:number[])=>p.join(',')).join(' ')} fill="#e8dcf7" stroke="#9566c4" strokeWidth=".1"/>}{s.points.map((p:number[],i:number)=><g key={i}><circle cx={p[0]} cy={p[1]} r=".13" fill={s.type==='circlecenter'?'#e56858':'#245168'}/>{s.type!=='circlecenter'&&<text x={p[0]+.18} y={p[1]-.16} fontSize=".38" fill="#29485a">{i+1}</text>}</g>)}{s.candidates?.map(([x,y]:number[],i:number)=><g key={i}><circle cx={x} cy={y} r=".3" fill="#fff" stroke="#14998b" strokeWidth=".04"/><text x={x} y={y+.13} fontSize=".4" textAnchor="middle" fill="#087d73">{String.fromCharCode(65+i)}</text></g>)}</svg>;}
function Circuit({tree}:{tree:any}){if(typeof tree==='number')return <span className="circuit-input">{String.fromCharCode(65+tree)}</span>;return <div className="circuit-branch"><div><Circuit tree={tree.left}/><Circuit tree={tree.right}/></div><span className="circuit-wire">→</span><span className="circuit-gate">{tree.op==='AND'?'両方':tree.op==='OR'?'どちらか':'片方だけ'}<small>{tree.op}</small></span></div>;}
export function sceneRowLayout(s:Scene):'prose'|'sequence'|'panels'|'mixed'|'groups'{
 if(s.layout==='groups')return 'groups';
 const items:Scene[]=s.items||[];
 if(!items.length)return 'mixed';
 if(items.every(v=>v.type==='text'&&v.text!=='？'||v.type==='assignment'))return 'prose';
 if(items.every(v=>v.type==='symbol'||v.type==='text'&&v.text==='？'))return 'sequence';
 if(items.every(v=>v.type==='row'))return 'panels';
 return 'mixed';
}
export function SceneView({s,compact=false,questionText}:{s:Scene|number|string|undefined;compact?:boolean;questionText?:string}){if(s===undefined||s===null)return null;if(typeof s==='number'||typeof s==='string')return <span className="scene-answer">{s}</span>;
if(s.type==='text'&&questionText&&s.text===questionText&&!s.sub)return null;
const wrap=(node:React.ReactNode)=> <div className={`scene scene-${s.type} ${s.type==='row'?`scene-row-${sceneRowLayout(s)}`:''} ${s.layout?`scene-layout-${s.layout}`:''} ${compact?'compact':''}`}>{node}</div>;
if(s.type==='text')return wrap(<><strong className="scene-title">{s.text}</strong>{s.sub&&<small>{s.sub}</small>}</>);
if(s.type==='row')return wrap(s.items.map((item:Scene,i:number)=>sceneRowLayout(s)==='sequence'?<div className="sequence-item" style={{width:Math.max(84,(item.count||1)*36)}} key={i}><SceneView s={item} compact={compact}/></div>:<SceneView key={i} s={item} compact={compact} questionText={questionText}/>));
if(s.type==='shape')return wrap(<Shape cells={s.cells} extent={s.extent} grid={s.grid}/>);
if(s.type==='cubes')return wrap(<><Cubes cells={s.cells}/>{s.showLayers&&<CubeLayers cells={s.cells}/>}</>);
if(s.type==='symbol')return wrap(<SymbolCard s={s}/>);
if(s.type==='grid'||s.type==='heightmap')return wrap(<><MiniGrid n={s.n} values={s.values} blocked={s.blocked}/>{s.type==='heightmap'&&<small>うえから みた たかさ</small>}{s.footer&&<small>{s.footer}</small>}</>);
if(s.type==='cards')return wrap(<div className="scene-cards">{s.values.map((v:any,i:number)=><span key={i}>{v}</span>)}</div>);
if(s.type==='abacus')return wrap(<div className="place-columns">{s.digits.map((v:number,i:number)=>{const unit=10**(s.digits.length-1-i);return <div key={i}><strong>{unit}</strong><div>{range(v).map(j=><span key={j} className={`bundle unit-${unit}`}><i/>{unit===1?'':unit}</span>)}</div></div>;})}</div>);
if(s.type==='numberline')return wrap(<svg viewBox="0 0 340 110" aria-hidden="true"><path d="M25 65H315" stroke="#486071" strokeWidth="3"/>{range(s.steps+1).map(i=><path key={i} d={`M${25+290*i/s.steps} 56v18`} stroke="#486071" strokeWidth="2"/>)}<text x="25" y="96" textAnchor="middle" fontSize="19">{s.min}</text><text x="315" y="96" textAnchor="middle" fontSize="19">{s.max}</text><text x={25+290*s.at/s.steps} y="38" textAnchor="middle" fontSize="24" fontWeight="800" fill="#d28d15">{s.label}</text><path d={`M${25+290*s.at/s.steps} 43v13`} stroke="#d28d15" strokeWidth="3"/></svg>);
if(s.type==='share')return wrap(<><div className="dot-cloud">{range(s.total).map(i=><span key={i} className="snack-dot"/>)}</div><div className="share-people">{range(s.groups).map(i=><span key={i}>☺<small>{i+1}</small></span>)}</div></>);
if(s.type==='clock'){const hand=(angle:number,len:number)=>[100+Math.sin(angle)*len,100-Math.cos(angle)*len];const h=hand((s.hour%12+s.minute/60)*Math.PI/6,43),m=hand(s.minute*Math.PI/30,68);return wrap(<svg viewBox="0 0 200 200" aria-label="とけい"><circle cx="100" cy="100" r="94" fill="#fff" stroke="#91cbd9" strokeWidth="8"/>{range(60).map(i=>{const p=hand(i*Math.PI/30,i%5?86:82),q=hand(i*Math.PI/30,90);return <path key={i} d={`M${p}L${q}`} stroke="#587181" strokeWidth={i%5?1:2}/>;})}{range(12).map(i=>{const p=hand((i+1)*Math.PI/6,71);return <text key={i} x={p[0]} y={p[1]+5} textAnchor="middle" fontSize="15" fill="#344e60">{i+1}</text>;})}<path d={`M100 100L${h}`} stroke="#35556b" strokeWidth="9" strokeLinecap="round"/><path d={`M100 100L${m}`} stroke="#edaf2f" strokeWidth="5" strokeLinecap="round"/><circle cx="100" cy="100" r="6" fill="#35556b"/></svg>);}
if(s.type==='coins'||s.type==='expression')return wrap(<><small>おだい</small><strong className="scene-title">{s.target}{s.type==='coins'?'えん':''}</strong></>);
if(s.type==='fraction'){const angle=s.a/s.b*2*Math.PI,x=50+42*Math.sin(angle),y=50-42*Math.cos(angle);return wrap(<><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="42" fill="#f7eee1" stroke="#cbb893" strokeWidth="1.5"/><path d={`M50 50L50 8A42 42 0 ${angle>Math.PI?1:0} 1 ${x} ${y}Z`} fill="#ecb239"/>{range(s.b).map(i=><path key={i} d={`M50 50L${50+42*Math.sin(i*2*Math.PI/s.b)} ${50-42*Math.cos(i*2*Math.PI/s.b)}`} stroke="#896b2e" strokeWidth="1"/>)}</svg><small>{s.a}/{s.b}</small></>);}
if(s.type==='ribbons'){const max=Math.max(...s.values);return wrap(s.values.map((v:number,i:number)=><div className="ribbon-row" key={i}><span style={{width:`${v/max*85}%`,background:colors[i]}}>{v}</span></div>));}
if(s.type==='cycles')return wrap(<>{s.values.map((v:number,i:number)=><div key={i} className="cycle-row"><span className="cycle-lamp" style={{background:colors[i]}}>✦</span><strong>{v}びょう ごと</strong><span>● → ○ → ●</span></div>)}<small>いま いっしょに ついたよ</small></>);
if(s.type==='bars'){const max=Math.max(...s.values);return wrap(<svg viewBox={`0 0 ${s.values.length*45+12} ${max*13+30}`} aria-hidden="true">{s.values.map((v:number,i:number)=><g key={i}>{range(v).map(j=><rect key={j} x={i*45+8} y={(max-j-1)*13+4} width="32" height="11" rx="2" fill={colors[i]}/>)}<text x={i*45+24} y={max*13+23} fontSize="14" textAnchor="middle">{v}</text></g>)}</svg>);}
if(s.type==='balls')return wrap(<div className="chance-cards">{range(s.b).map(i=><SymbolCard key={i} s={{shape:i<s.a?1:0,color:i<s.a?0:1,count:1}}/>)}</div>);
if(s.type==='cryptarithm')return wrap(<div className="cryptarithm"><div>□△ ＋ △□ ＝ {s.total}</div><div>□ − △ ＝ {s.difference}</div><strong>□△ ＝ ？</strong></div>);
if(s.type==='statements')return wrap(<><div className="scene-tag">ほんとうは {s.trueCount}こ</div><div className="statement-list">{s.statements.map((v:any,i:number)=><div key={i}><span>{i+1}</span>あたりは <strong>{s.people[v.person]}</strong> {v.is?'だよ':'ではないよ'}</div>)}</div></>);
if(s.type==='assignment')return wrap(<small>ひとりに ひとつ。おなじ カードは つかえないよ。</small>);
if(s.type==='rule')return wrap(<div className="rule-box">{ruleWords(s.rule)}</div>);
if(s.type==='circuit')return wrap(<><Circuit tree={s.tree}/><small>「両方」＝2つともON　「どちらか」＝1つ以上ON<br/>「片方だけ」＝ちょうど1つON</small></>);
if(s.type==='machine')return wrap(<>{(s.keys||[{name:'',examples:s.examples}]).map((key:any,j:number)=><div key={j}>{key.name&&<small>はこ {key.name}</small>}<div className="machine-examples">{key.examples.map(([a,b]:any[],i:number)=><div key={i}><SymbolCard s={a}/><span>→</span><SymbolCard s={b}/></div>)}</div></div>)}{s.prompt&&<small>{s.prompt}</small>}<div className="machine-question">{s.reverse?<><strong>？</strong><span>→</span><SymbolCard s={s.target}/></>:<><SymbolCard s={s.target}/><span>→</span><strong>？</strong></>}</div><small>○ → △ → □ → ○<br/>色1 → 色2 → 色3 → 色1　1こ → 2こ → 3こ → 1こ</small></>);
if(s.type==='precedence')return wrap(<div className="precedence-clues">{s.clues.map(([a,b]:number[],i:number)=><span key={i}>{String.fromCharCode(65+a)} <b>→</b> {String.fromCharCode(65+b)}</span>)}<small>やじるしの ひだりが さき。となりでなくても いいよ。</small></div>);
if(s.type==='family'){
 const children:number[][]=s.parents.map(()=>[]);s.parents.forEach((p:number,i:number)=>{if(p>=0)children[p].push(i);});const positions:number[][]=s.parents.map(()=>[0,0]);let leaf=0,maxDepth=0;
 function place(i:number,depth:number):number{maxDepth=Math.max(maxDepth,depth);const xs=children[i].map(c=>place(c,depth+1)),x=xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:leaf++;positions[i]=[x,depth];return x;}place(0,0);const width=Math.max(320,leaf*44);positions.forEach(p=>{p[0]=(p[0]+.5)/leaf*width;p[1]=p[1]*62+22;});
 return wrap(<>{!s.hideQuery&&<div className="scene-tag">{s.queryText||`${s.labels[s.target]} の ${s.steps}だい まえは？`}</div>}<svg viewBox={`0 0 ${width} ${maxDepth*62+46}`} aria-hidden="true">{s.parents.map((parent:number,i:number)=>parent<0?null:<path key={i} d={`M${positions[parent]}L${positions[i]}`} stroke="#acbac9" strokeWidth="2.5"/>)}{positions.map(([x,y]:number[],i:number)=><g key={i}><circle cx={x} cy={y} r="17" fill={i===s.target||i===s.otherTarget?'#f4c14c':'#e4f4ef'} stroke="#6fa393"/><text x={x} y={y+5} textAnchor="middle" fontSize="15" fontWeight="700">{s.labels[i]}</text></g>)}</svg></>);
}
if(s.type==='cipher')return wrap(<>{(s.maps||[s.map,s.map2].filter(Boolean)).map((m:number[],j:number)=><div className="cipher-key" key={j}><small>カギ {j+1}</small>{m.map((v,i)=><span key={i}>{i+1} → <b>{v+1}</b></span>)}</div>)}{s.prompt&&<small>{s.prompt}</small>}<div className="cipher-message">{s.message.map((v:number,i:number)=><b key={i}>{v+1}</b>)} <span>→ ？</span></div></>);
if(s.type==='rollcube'){const coords=[[1,1],[1,3],[1,0],[1,2],[2,1],[0,1]];return wrap(<><svg viewBox="0 0 170 205" aria-hidden="true">{coords.map(([x,y],i)=><g key={i}><rect x={x*48+12} y={y*48+4} width="45" height="45" rx="8" fill={i===0?'#ffe09a':'#e6f6f1'} stroke="#7aaa9e"/><text x={x*48+34} y={y*48+34} textAnchor="middle" fontSize="24" fontWeight="700">{s.faces[i]}</text></g>)}</svg><small>きいろの めんが はじめの うえ</small><div className="move-sequence">{s.moves.map((d:number,i:number)=><span key={i}>{ARROWS[d]}</span>)}</div></>);}
if(s.type==='views')return wrap(<div className="view-panels">{s.views.map((v:number[][],i:number)=><div key={i}><small>{['まえ','みぎ','うえ'][i]}{s.holes?'の あな':''}</small><Shape cells={i<2?normalize(v.map(([x,z])=>[x,-z])):v} color={s.holes?'#42586c':colors[i]}/></div>)}</div>);
if(s.type==='layers')return wrap(<>{s.ray&&<div className="scene-tag">{['よこ →','おく ↓','たかさ ↑'][s.ray.axis]} {s.ray.sign<0?'の はんたいから':''}　{['奥・段','横・段','横・奥'][s.ray.axis]}：{s.ray.fixed.filter((_:number,i:number)=>i!==s.ray.axis).map((v:number)=>v+1).join('・')}</div>}<div className="layer-panels">{range(s.h).map(z=><div key={z}><small>{z+1}だんめ</small><MiniGrid n={s.n} values={s.values.slice(z*s.n*s.n,(z+1)*s.n*s.n).map((v:any)=>typeof v==='string'?v:v===2?<span className="voxel red">★</span>:v===1?<span className="voxel"/>:null)} selected={s.path?.filter((p:number[])=>p[2]===z).map(([x,y]:number[])=>y*s.n+x)} labels/></div>)}</div><small>{s.holes?'しろ＝あな　いろ＝つみき':s.coordinates?'ばんちは よこ・おく・たかさ。ひだりうえから1。':'あかい つみきは ★'}</small></>);
if(s.type==='drop3d')return wrap(<><div className="view-panels"><div><small>おとす ピース</small><Cubes cells={s.piece}/><small>ピースの たかさ（0は あな）</small><MiniGrid n={s.n} values={range(s.n*s.n).map(i=>{const column=s.piece.filter(([x,y]:number[])=>i===y*s.n+x);return column.length?Math.max(...column.map((v:number[])=>v[2]))+1:0;})}/></div><div><small>したの つみきの たかさ</small><MiniGrid n={s.n} values={s.heights}/><small>おなじ マスの うえへ ↓</small></div></div></>);
if(s.type==='braid'){const width=320,dx=width/(s.n+1),dy=210/s.swaps.length;let positions=range(s.n),paths=range(s.n).map(i=>`M${(i+1)*dx} 25`);for(let row=0;row<s.swaps.length;row++){const swap=s.swaps[row];range(s.n).forEach(i=>{const old=positions[i],next=old===swap?old+1:old===swap+1?old-1:old;paths[i]+=` C${(old+1)*dx} ${25+row*dy+dy*.55} ${(next+1)*dx} ${25+row*dy+dy*.45} ${(next+1)*dx} ${25+(row+1)*dy}`;positions[i]=next;});}return wrap(<svg viewBox="0 0 320 270" aria-hidden="true">{paths.map((d,i)=><g key={i}><path d={d} stroke="white" strokeWidth="9" fill="none"/><path d={d} stroke="#479c99" strokeWidth="4" fill="none"/></g>)}{range(s.n).map(i=><g key={i}><circle cx={(i+1)*dx} cy="20" r="14" fill={i===s.start?'#fac85b':'#fff'}/><text x={(i+1)*dx} y="25" fontSize="15" textAnchor="middle">{i===s.start?'★':i+1}</text><text x={(i+1)*dx} y="260" fontSize="20" textAnchor="middle" fill="#34536a">{i+1}</text></g>)}</svg>);}
if(s.type==='spatialmap'||s.type==='viewpoint'){const values=range(s.n*s.n).map(i=>{const at=s.positions.findIndex(([x,y]:number[])=>y*s.n+x===i);return at<0?null:<span className="map-object" style={{background:colors[at%colors.length]}}>{String.fromCharCode(65+at)}{s.heights&&<small>{s.heights[at]}だん</small>}</span>;});return wrap(<><div className="camera-board"><div className="camera north">{s.type==='viewpoint'?'A ↓':s.dir===0?'↓':''}</div><div className="camera west">{s.type==='viewpoint'?'D →':s.dir===3?'→':''}</div><MiniGrid n={s.n} values={values}/><div className="camera east">{s.type==='viewpoint'?'← B':s.dir===1?'←':''}</div><div className="camera south">{s.type==='viewpoint'?'↑ C':s.dir===2?'↑':''}</div></div>{s.photo&&<div className="photo-towers">{s.photo.map((v:any,i:number)=><div key={i} style={{height:s.silhouette?(v.height?v.height*24+1:1):v.height*24+25,background:s.silhouette?(v.height?'#496b83':'transparent'):colors[v.label.charCodeAt(0)-65]}}>{s.silhouette?'':v.label}</div>)}</div>}{s.silhouette&&<small>おなじ れつは かさなる。たかい とうの かげが のこるよ。</small>}</>);}
if(s.type==='surfacewalk'){const positions=[[1,0,0],[1,2,0],[1,1,0],[3,1,0],[2,1,0],[0,1,0]];return wrap(<><div className="surface-net">{positions.map(([x,y,q],face)=><div key={face} className={`surface-face ${s.start.face===face?'start-face':''}`} style={{gridColumn:x+1,gridRow:y+1}}><small>{face+1}</small><div style={{gridTemplateColumns:`repeat(${s.n},1fr)`}}>{range(s.n*s.n).map(i=>{const sx=q===2?s.n-1-i%s.n:i%s.n,sy=q===2?s.n-1-Math.floor(i/s.n):Math.floor(i/s.n);return <span key={i}>{face===s.start.face&&sx===s.start.x&&sy===s.start.y?ARROWS[(s.start.heading+q)%4]:'·'}</span>;})}</div></div>)}</div><div className="move-sequence">{s.commands.map((cmd:string,i:number)=><span key={i}>{cmd==='F'?'↑':cmd==='L'?'↶':'↷'}</span>)}</div><small>くみたてた サイコロの うえを さんぽ</small></>);}
if(s.type==='balancefoot'){const h=Math.max(...s.heights,1),size=Math.min(30,140/h);return wrap(<><svg viewBox="0 0 320 220" aria-label="同じ重さのつみきと床の4つの範囲"><rect x="20" y="166" width="280" height="10" rx="3" fill="#527d90"/>{s.heights.map((height:number,i:number)=><g key={i}>{range(height).map(z=><rect key={z} x={40+i*70} y={163-(z+1)*size} width="30" height={size-1} fill="#5cbfb1" stroke="#2f8279" strokeWidth="1"/>)}<text x={55+i*70} y={151-height*size} fontSize="15" textAnchor="middle" fill="#33556a">{height}</text><rect x={20+i*70} y="180" width="70" height="16" fill={i%2?'#daeaf0':'#ecf5f7'} stroke="#7895a3" strokeWidth="1.5"/><text x={55+i*70} y="214" fontSize="17" textAnchor="middle" fill="#33556a">{i+1}</text></g>)}</svg><small>ばんごうは はばの ある はんい。いたの おもさは かぞえないよ。</small></>);}

if(s.type==='wire3d'||s.type==='branches')return wrap(<><Wire3D points={s.points} branches={s.type==='branches'}/>{s.showAxes&&<small>X＝みぎした ↘　Y＝ひだりした ↙　Z＝うえ ↑</small>}</>);
if(s.type==='hinge')return wrap(<><Wire3D points={s.points}/><div className="hinge-instructions">{s.turns.map((v:any,i:number)=><span key={i}>{i+1}. {v.pivot}から さき　{['X','Y','Z'][v.axis]}軸 {v.q===1?'＋90°':'−90°'}</span>)}</div><small>X＝よこ　Y＝おく　Z＝うえ。＋は軸の先から見て反時計回り。</small></>);
if(s.type==='gears')return wrap(<div className="gear-chain">{range(s.count).map(i=><React.Fragment key={i}><div className="gear-circle">{i===0?(s.unknown==='start'?'？':s.start?'↻':'↺'):i===s.count-1?(s.unknown==='start'||s.missingLink!==undefined?s.end?'↻':'↺':'？'):i+1}</div>{i<s.count-1&&<span className={`gear-link ${s.missingLink===i?'unknown':s.links[i]}`}>{s.missingLink===i?'？':s.links[i]==='gear'?'⚙':s.links[i]==='crossed'?'⋈':'＝'}<small>{s.missingLink===i?'つなぎかた':s.links[i]==='gear'?'かみあう':s.links[i]==='crossed'?'クロス':'ベルト'}</small></span>}</React.Fragment>)}</div>);
if(s.type==='tilt')return wrap(<><MiniGrid n={s.n} blocked={s.walls} values={range(s.n*s.n).map(i=>s.balls.includes(i)?'●':'')}/><div className="move-sequence">{s.moves.map((d:number,i:number)=><span key={i}>{ARROWS[d]}</span>)}</div></>);
if(s.type==='pieces3d')return wrap(<div className="view-panels">{s.pieces.map((p:any,i:number)=><div key={i}><small>{i+1}ばん</small><Cubes cells={p.cells}/><small>{p.dir.map((v:number,j:number)=>v?`${['X','Y','Z'][j]}${v>0?'+':'−'}`:'').join('')}</small></div>)}</div>);
if(s.type==='translation')return wrap(<><Shape cells={s.cells} extent={s.n} grid/><div className="move-sequence">{s.moves.map((d:number,i:number)=><span key={i}>{ARROWS[d]}</span>)}</div></>);
if(s.type==='folds')return wrap(<><div className="fold-sequence">{s.folds.map((axis:string,i:number)=><span key={i}>{i+1}. {axis==='x'?'みぎを ひだりへ ←':'したを うえへ ↑'}</span>)}</div><div className="folded-paper"><MiniGrid n={s.w} values={range(s.w*s.h).map(i=>s.holes.includes(i)?'●':'')}/></div><small>おった かみの ●に あな</small></>);
if(s.type==='angles'){let angle=-Math.PI;return wrap(<><svg viewBox="0 0 260 230" aria-hidden="true">{s.parts.map((v:number,i:number)=>{const start=angle;angle+=v*Math.PI/180;const x=130+93*Math.cos(angle),y=120+93*Math.sin(angle),sx=130+93*Math.cos(start),sy=120+93*Math.sin(start),mid=(start+angle)/2;return <g key={i}><path d={`M130 120L${sx} ${sy}A93 93 0 ${v>180?1:0} 1 ${x} ${y}Z`} fill={colors[i]+'55'} stroke={colors[i]} strokeWidth="2"/><text x={130+65*Math.cos(mid)} y={125+65*Math.sin(mid)} fontSize="19" textAnchor="middle" fill="#314e61">{i===s.missing?'？':v+'°'}</text></g>;})}</svg><small>{s.label??(s.total===90?'ちょっかく':s.total===180?'はんかいてん':'1しゅう')}＝{s.total}°</small></>);}
if(s.type==='circlecenter'||s.type==='points')return wrap(<GridPoints s={s}/>);
if(s.type==='scale')return wrap(<><Shape cells={s.cells} extent={s.n} grid/><div className="scene-tag">たて・よこ {s.factor}ばい</div></>);
if(s.type==='segment'){const[x,y]=s.vector,max=Math.max(Math.abs(x),Math.abs(y)),dx=x/max*(s.length??34),dy=y/max*(s.length??34),ox=s.offset?.[0]??0,oy=s.offset?.[1]??0;return wrap(<>{s.label&&<small>{s.label}</small>}<svg viewBox="0 0 100 100" aria-hidden="true">{range(9).map(i=><path key={i} d={`M${i*10+10} 10V90M10 ${i*10+10}H90`} stroke="#e0e9ef" strokeWidth=".5"/>)}<path d={`M${50+ox-dx} ${50+oy+dy}L${50+ox+dx} ${50+oy-dy}`} stroke="#8970ce" strokeWidth="5" strokeLinecap="round"/></svg></>);}
return wrap(<small>ずを よみこんでいます</small>);
}
