'use client';
import React from 'react';
import {SceneView} from './scene';
import {Glyph} from './puzzle-art';
import {FRAMES} from '@/lib/engine/space';

type Point=number[];
const palette=['#269e8d','#e1a532','#8568c0','#d87261','#4989bc'];
const same=(a:Point,b:Point)=>a.length===b.length&&a.every((v,i)=>v===b[i]);
/** Render calculation frames as exact static diagrams; motion never carries information. */
export function TeachingScene({scene:s}:{scene:any}){
 if(s.type==='glyph')return <Glyph value={s.value} size={80}/>;
 if(s.type==='teaching-plane')return <PlaneDiagram s={s}/>;
 if(s.type==='paper-state')return <PaperDiagram s={s}/>;
 if(s.type==='cube-pose')return <CubePose s={s}/>;
 if(s.type==='skewer-state')return <SkewerDiagram s={s}/>;
 if(s.type==='surface-state')return <SurfaceDiagram s={s}/>;
 if(s.type==='hinge-state')return <HingeDiagram s={s}/>;
 if(s.type==='tilt-state')return <GridDiagram n={s.n} walls={s.walls} balls={s.balls} label={s.dir===undefined?'はじめの球':('傾ける方向 '+['↑','→','↓','←'][s.dir])}/>;
 if(s.type==='drop-state')return <DropDiagram s={s}/>;
 if(s.type==='net-state')return <NetDiagram s={s}/>;
 return <SceneView s={s}/>;
}
/** All panels share signed coordinates; axes and counted edges cannot drift. */
function PlaneDiagram({s}:{s:any}){
 if(s.mode==='angles'){const a=s.angles,r=75,c=100;let start=-90;return <div className="teaching-exact"><svg viewBox="0 0 200 200" role="img" aria-label="既知の角と未知の角"><circle cx={c} cy={c} r={r} fill="#f4f8fa" stroke="#8aa3b3"/>{a.parts.map((v:number,i:number)=>{const end=start+v,rad=(d:number)=>d*Math.PI/180,point=(d:number)=>[c+r*Math.cos(rad(d)),c+r*Math.sin(rad(d))],from=point(start),to=point(end),mid=point((start+end)/2),path=`M100 100L${from}A75 75 0 ${v>180?1:0} 1 ${to}Z`;start=end;return <g key={i}><path d={path} fill={a.knownIndices.includes(i)?'#a5dcd0':i===a.missing?'#ffe4a3':'#ecf1f5'} stroke="#3e6076"/><text x={100+(mid[0]-100)*.63} y={104+(mid[1]-100)*.63} textAnchor="middle" fontSize="14">{i===a.missing&&!a.revealMissing?'？':v+'°'}</text></g>;})}</svg><p>{a.total}° 全体</p>{s.formula&&<strong>{s.formula}</strong>}</div>;}
 const b=s.bounds,w=b.maxX-b.minX||1,h=b.maxY-b.minY||1,view=`${b.minX-.6} ${b.minY-.6} ${w+1.2} ${h+1.2}`;
 return <div className="teaching-panels teaching-plane-panels" data-panel-count={s.panels.length}>{s.panels.map((p:any,i:number)=><figure key={i}><figcaption>{p.label}</figcaption><svg viewBox={view} role="img" aria-label={p.label}>{s.mode==='cells'&&Array.from({length:Math.ceil(w)+1},(_,x)=><line key={'x'+x} x1={b.minX+x} x2={b.minX+x} y1={b.minY} y2={b.maxY} stroke="#dde8ec" strokeWidth=".025"/>)}{(p.cells||[]).map((c:Point,j:number)=><rect key={j} x={c[0]} y={c[1]} width="1" height="1" fill={(p.markedCells||[]).some((v:Point)=>same(v,c))?'#f6cb62':'#a6d9ce'} stroke="#365b70" strokeWidth=".04"/>)}{s.axis&&<line x1={s.axis.x} x2={s.axis.x} y1={b.minY-.3} y2={b.maxY+.3} stroke="#b2772c" strokeDasharray=".13 .09" strokeWidth=".05"/>}{s.pivot&&<circle cx={s.pivot[0]} cy={s.pivot[1]} r=".1" fill="#243e58"/>}{(p.edges||[]).map((e:any,j:number)=><line key={j} x1={e.from[0]} y1={e.from[1]} x2={e.to[0]} y2={e.to[1]} stroke="#ce642c" strokeWidth={s.mode==='distances'?'.045':'.1'}/>)}{(p.points||[]).map((c:Point,j:number)=><g key={j}><circle cx={c[0]} cy={c[1]} r=".14" fill="#c66050"/><text x={c[0]+.22} y={c[1]-.12} fontSize=".38">{j+1}</text></g>)}{p.candidate&&<g><circle cx={p.candidate[0]} cy={p.candidate[1]} r=".19" fill="#259a8b"/><text x={p.candidate[0]+.3} y={p.candidate[1]} fontSize=".4">中心</text></g>}</svg>{p.distances&&<p>距離²: {p.distances.join(' ・ ')}</p>}</figure>)}{s.formula&&<p className="teaching-formula">{s.formula}</p>}</div>;
}
/** Paper dimensions, unit creases and reflected hole centres come directly from foldTrace. */
function PaperDiagram({s}:{s:any}){const {width:w,height:h}=s.size;return <div className="teaching-exact"><svg viewBox={`-.5 -.5 ${w+1} ${h+1}`} role="img" aria-label={`紙 よこ${w}たて${h}、穴${s.holes.length}こ`}><rect x="0" y="0" width={w} height={h} fill="#fff0c7" stroke="#816335" strokeWidth=".07"/>{Array.from({length:w-1},(_,i)=><line key={'x'+i} x1={i+1} x2={i+1} y1="0" y2={h} stroke="#dabd80" strokeWidth=".025"/>)}{Array.from({length:h-1},(_,i)=><line key={'y'+i} x1="0" x2={w} y1={i+1} y2={i+1} stroke="#dabd80" strokeWidth=".025"/>)}{s.creases.map((c:any,i:number)=><line key={i} x1={c.from[0]} y1={c.from[1]} x2={c.to[0]} y2={c.to[1]} stroke="#284c65" strokeWidth=".07" strokeDasharray=".17 .12"/>)}{s.holes.map((c:Point,i:number)=><circle key={i} cx={c[0]+.5} cy={c[1]+.5} r=".23" fill="#253e55"/>)}</svg><p>{s.fold?(s.fold.axis==='x'?'右半分 → 左半分':'下半分 ↑ 上半分'):('穴 '+s.holes.length+'こ')} ・ 破線＝折り目</p></div>;}
/** A fixed labelled net preserves all six face identities in every roll state. */
function CubePose({s}:{s:any}){const p=s.pose;const faces=[['north','おく',1,0],['west','ひだり',0,1],['top','うえ',1,1],['east','みぎ',2,1],['south','てまえ',1,2],['bottom','した',1,3]] as const;return <div className="teaching-exact"><svg viewBox="-.1 -.1 3.2 4.2" role="img" aria-label={`6面 うえ${p.top}した${p.bottom}おく${p.north}てまえ${p.south}みぎ${p.east}ひだり${p.west}`}>{faces.map(([key,label,x,y])=><g key={key}><rect x={x} y={y} width="1" height="1" fill={palette[(Number(p[key])-1)%palette.length]+'44'} stroke="#36596e" strokeWidth=".03"/><text x={x+.5} y={y+.25} textAnchor="middle" fontSize=".16">{label}</text><text x={x+.5} y={y+.72} textAnchor="middle" fontSize=".42">{p[key]}</text></g>)}</svg><p>上 {p.top} ／ 手前 {p.south} ／ 右 {p.east}</p></div>;}
/** Layer grids show the exact entry axis, current voxel and cumulative reading order. */
function SkewerDiagram({s}:{s:any}){return <div className="teaching-exact teaching-skewer" data-layers={s.h}><p>{['よこ x','おく y','たかさ z'][s.axis]}方向 ・ {s.axis===0?(s.sign===1?'ひだりから →':'みぎから ←'):s.axis===1?(s.sign===1?'上の行から ↓':'下の行から ↑'):(s.sign===1?'1だんめから 上の段へ':'高い段から 下の段へ')}</p><p>入口のマス: ({s.entry.displayCoordinate.join(',')}) ／ 緑の列を通る</p><div className="teaching-layers">{Array.from({length:s.h},(_,z)=><figure key={z}><figcaption>{z+1}だんめ</figcaption><div className="teaching-grid" style={{gridTemplateColumns:`repeat(${s.n},1fr)`}}>{Array.from({length:s.n*s.n},(_,i)=>{const c=[i%s.n,Math.floor(i/s.n),z],idx=z*s.n*s.n+i,onRay=c.every((v,j)=>j===s.axis||v===s.fixed[j]),current=s.current?.index===idx;return <span key={i} className={current?'active':onRay?'ray':''}>{s.values[idx]||'空'}{current&&<small>今</small>}</span>;})}</div></figure>)}</div><strong>順番: {s.tokens.join(' → ')||'まだなし'}</strong></div>;}
/** Six net faces keep the local cell and world heading tied to the same FRAMES convention. */
function SurfaceDiagram({s}:{s:any}){const state=s.state,n=s.n,layout=[[0,0],[1,0],[2,0],[0,1],[1,1],[2,1]],f=FRAMES[state.face];return <div className="teaching-exact"><svg viewBox="-.1 -.1 3.2 2.2" role="img" aria-label={`面${state.face+1}、セル${state.x+1},${state.y+1}、向き${state.heading}`}>{layout.map(([x,y],i)=><g key={i}><rect x={x} y={y} width="1" height="1" fill={state.face===i?'#c4e7df':'#f2f6f8'} stroke="#6b8798" strokeWidth=".025"/><text x={x+.08} y={y+.16} fontSize=".09">面{i+1}（別々の面）</text>{state.face===i&&<><rect x={x+state.x/n} y={y+state.y/n} width={1/n} height={1/n} fill="#e2b241"/><text x={x+(state.x+.5)/n} y={y+(state.y+.7)/n} fontSize={.7/n} textAnchor="middle">{['↑','→','↓','←'][state.heading]}</text></>}</g>)}</svg><p>面{state.face+1} ・ よこ{state.x+1} おく{state.y+1} ・ {s.crossed?'となりの面へ':'面の中'}</p><small>世界の向き ({s.worldHeading?.join(',')}) ／ 面の法線 ({f?.n?.join(',')})</small></div>;}
/** Segments are drawn first and endpoint labels last, preserving the fixed pivot. */
function HingeDiagram({s}:{s:any}){const iso=([x,y,z]:Point)=>[(x-y)*28,(x+y)*14-z*30],ps=s.points.map(iso),xs=ps.map((p:Point)=>p[0]),ys=ps.map((p:Point)=>p[1]);return <div className="teaching-exact"><svg viewBox={`${Math.min(...xs)-25} ${Math.min(...ys)-25} ${Math.max(...xs)-Math.min(...xs)+50} ${Math.max(...ys)-Math.min(...ys)+50}`} role="img" aria-label="固定する点と回す先端">{ps.slice(1).map((p:Point,i:number)=><line key={i} x1={ps[i][0]} y1={ps[i][1]} x2={p[0]} y2={p[1]} stroke={palette[i%5]} strokeWidth="5"/>)}{ps.map((p:Point,i:number)=><g key={i}><circle cx={p[0]} cy={p[1]} r="8" fill={s.fixed.includes(i)?'#e8b448':'white'} stroke="#304d66"/><text x={p[0]+11} y={p[1]+5} fontSize="14">{i===0?'根元':i}</text></g>)}</svg><p>固定: {s.fixed.map((i:number)=>i===0?'根元':i).join('・')} ／ 回転軸: {s.axis===undefined?'はじめ':['横 X','奥 Y','高さ Z'][s.axis]}</p></div>;}
function GridDiagram({n,walls=[],balls=[],label}:{n:number;walls?:number[];balls?:number[];label:string}){return <div className="teaching-exact"><p>{label}</p><div className="teaching-grid" style={{gridTemplateColumns:`repeat(${n},1fr)`}}>{Array.from({length:n*n},(_,i)=><span key={i} className={walls.includes(i)?'wall':balls.includes(i)?'active':''}>{walls.includes(i)?'壁':balls.includes(i)?'●':''}</span>)}</div></div>;}
/** Preserve whole-piece placement and empty space, rather than filling every column. */
function DropDiagram({s}:{s:any}){const floor=s.heights.flatMap((v:number,i:number)=>Array.from({length:v},(_,z)=>[i%s.n,Math.floor(i/s.n),z])),placed=s.placed??s.piece.map(([x,y,z]:Point)=>[x,y,z+s.offset]),cells=[...floor.map((c:Point)=>({c,piece:false})),...placed.map((c:Point)=>({c,piece:true}))],iso=([x,y,z]:Point)=>[(x-y)*25,(x+y)*13-z*25],corners=cells.flatMap(({c}:any)=>[iso(c),iso([c[0]+1,c[1]+1,c[2]+1])]),xs=corners.map((p:Point)=>p[0]),ys=corners.map((p:Point)=>p[1]);return <div className="teaching-exact teaching-drop"><p>落下位置 {s.offset} ／ {s.position==='above'?'上から':'支持柱に ふれる'}</p><svg viewBox={`${Math.min(...xs)-35} ${Math.min(...ys)-35} ${Math.max(...xs)-Math.min(...xs)+70} ${Math.max(...ys)-Math.min(...ys)+70}`} role="img" aria-label="柱とピース、空間は埋めない">{cells.sort((a:any,b:any)=>a.c[0]+a.c[1]-b.c[0]-b.c[1]||a.c[2]-b.c[2]).map(({c,piece}:any,i:number)=>{const [x,y,z]=c,pt=(dx:number,dy:number,dz:number)=>iso([x+dx,y+dy,z+dz]).join(',');return <g key={i} stroke="#37576b" strokeWidth=".8"><polygon points={[pt(0,0,1),pt(1,0,1),pt(1,1,1),pt(0,1,1)].join(' ')} fill={piece?'#f8d476':'#c6dedb'}/><polygon points={[pt(1,0,0),pt(1,1,0),pt(1,1,1),pt(1,0,1)].join(' ')} fill={piece?'#ddb653':'#8fb8b0'}/><polygon points={[pt(0,1,0),pt(1,1,0),pt(1,1,1),pt(0,1,1)].join(' ')} fill={piece?'#eac567':'#a6cac2'}/></g>;})}</svg><p>黄色＝落ちるピース ／ 緑＝柱</p><div className="teaching-grid" style={{gridTemplateColumns:`repeat(${s.n},1fr)`}}>{s.heights.map((v:number,i:number)=><span key={i} className={(s.supports||[]).includes(i)?'active':''}><small>{Math.floor(i/s.n)+1}行{i%s.n+1}列</small>{v} → {s.result?.[i]??v}</span>)}</div></div>;}
/** Mark folding order and face normals; use a six-face pose once an orientation is fixed. */
function NetDiagram({s}:{s:any}){const xs=s.cells.map((v:Point)=>v[0]),ys=s.cells.map((v:Point)=>v[1]),minX=Math.min(...xs),minY=Math.min(...ys);return <div className="teaching-panels teaching-net" data-posed={Boolean(s.faces)}><figure><figcaption>元の展開図</figcaption><svg viewBox={`${minX-.1} ${minY-.1} ${Math.max(...xs)-minX+1.2} ${Math.max(...ys)-minY+1.2}`} role="img" aria-label="展開図の面対応">{s.cells.map((v:Point,i:number)=><g key={i}><rect x={v[0]} y={v[1]} width="1" height="1" fill={(s.selected||s.visibleFaces||[]).includes(i)?'#c4e4db':'#f2f6f8'} stroke="#37586b" strokeWidth=".03"/><text x={v[0]+.5} y={v[1]+.55} textAnchor="middle" fontSize=".28">{s.labels[i]}</text><text x={v[0]+.5} y={v[1]+.8} textAnchor="middle" fontSize=".12">{s.normals[i].join(',')}</text></g>)}</svg></figure><p className="teaching-formula">{s.task==='opposite'?'反対の面':s.task==='side'?'となりの面':'ころがす面'}: {s.resolved??'面の向きを たしかめる'}</p>{s.faces&&<figure><figcaption>今の6面の位置</figcaption><CubePose s={{pose:{top:s.faces[0],bottom:s.faces[1],north:s.faces[2],south:s.faces[3],east:s.faces[4],west:s.faces[5]}}}/></figure>}</div>;}
