'use client';
import React,{useState,useEffect}from'react';
import{type Puzzle,range}from'@/lib/engine/shared';
import{directed,trialStep,SEGMENTS}from'@/lib/engine/trial';
import{MiniGrid,SymbolCard,ARROWS}from'./scene';
import type{Feedback}from'@/lib/feedback';
import{feedbackTargetProps,hasFeedbackTarget,FeedbackMarker}from'./feedback-notice';
const COLORS=['#2ba994','#e8ae37','#8d76d5','#e67968','#629bd3','#d479b0'];
export function DPad({onMove,horizontal=false,vertical=false}:{onMove:(d:number)=>void;horizontal?:boolean;vertical?:boolean}){return <div className="extended-dpad">{[0,3,2,1].map(d=><button type="button" key={d} onClick={()=>onMove(d)} disabled={horizontal&&d%2===0||vertical&&d%2===1} aria-label={['うえ','みぎ','した','ひだり'][d]} style={{gridArea:['1 / 2','2 / 3','2 / 2','2 / 1'][d]}}>{ARROWS[d]}</button>)}</div>;}
const segmentLines=['M20 10H80','M90 20V70','M90 90V140','M20 150H80','M10 90V140','M10 20V70','M20 80H80'];
export function Digit({mask,onSegment,selected=-1}:{mask:number;onSegment?:(i:number)=>void;selected?:number}){return <svg viewBox="-8 -8 116 176" className="match-digit" aria-hidden={!onSegment}>{segmentLines.map((path,i)=>{const on=!!(mask&(1<<(6-i)));return <g key={i}><path d={path} stroke={selected===i?'#478fd4':on?'#edaf37':'#e5eaf0'} strokeWidth="12" strokeLinecap="round"/>{onSegment&&<path d={path} stroke="transparent" strokeWidth="30" fill="none" role="button" tabIndex={0} aria-label={`${i+1}ばんの マッチ ${on?'あり':'なし'}`} onClick={()=>onSegment(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSegment(i);}}}/>}</g>;})}</svg>;}
export function TrialBoard({p,state:s,onMove,onProgram,onProgramEdit,feedback=null,noticeId='move-feedback',hint=false,demo=false,playback=false,actions=[]}:{p:Puzzle;state:any;onMove:(a:any)=>void;onProgram:(a:any[])=>void;onProgramEdit?:()=>void;feedback?:Feedback|null;noticeId?:string;hint?:boolean;demo?:boolean;playback?:boolean;actions?:any[]}){
 const d=p.data,id=p.id,[selected,setSelected]=useState<any>(null),[riders,setRiders]=useState<number[]>([]),[program,setProgram]=useState<string[]>([]),[pans,setPans]=useState<number[]>(()=>range(d.n||0).map(()=>0)),[guess,setGuess]=useState<number[]>(()=>range(d.length||0).map(()=>0)),[slot,setSlot]=useState(0),[guessMode,setGuessMode]=useState(false),[digit,setDigit]=useState(0);
 useEffect(()=>{setSelected(null);setRiders([]);setProgram([]);setPans(range(d.n||0).map(()=>0));setGuess(range(d.length||0).map(()=>0));setSlot(0);setGuessMode(false);setDigit(0);},[p]);
 const markCell=(node:React.ReactNode,index:number)=>hasFeedbackTarget(feedback,'cell',index)?<span {...feedbackTargetProps(feedback,'cell',index,noticeId)} style={{display:'grid',width:'100%',height:'100%',placeItems:'center',...feedbackTargetProps(feedback,'cell',index,noticeId).style}}><FeedbackMarker feedback={feedback} type="cell" index={index}/>{node}</span>:node;
 const shownProgram=playback?actions:program;
 const badge=(label:string)=> <div className="scene-tag" {...feedbackTargetProps(feedback,'constraint',0,noticeId)}>{label}</div>;
 const choose=(i:number)=>setRiders(a=>a.includes(i)?a.filter(v=>v!==i):[...a,i]);
 const move=(a:any)=>{onMove(a);setSelected(null);};
 if(['sokoban','keydoors','twobots','programbot'].includes(id)){const values=range(d.n*d.n).map(at=>{let node:React.ReactNode=null;if(id==='sokoban')node=s.boxes.includes(at)?<span className={`crate ${d.goals.includes(at)?'delivered':''}`}>▣</span>:s.pos===at?<span className="robot-token">●</span>:d.goals.includes(at)?<span className="goal-marker">★</span>:null;
 if(id==='keydoors'){const ki=d.keys.indexOf(at),di=d.doors.indexOf(at);node=s.pos===at?<span className="robot-token">●</span>:at===d.goal?<span className="goal-marker">★</span>:ki>=0&&!(s.keys&(1<<ki))?<span className="key-token">⚿<b>{ki+1}</b></span>:di>=0?<span className={`door-token ${s.keys&(1<<di)?'open':''}`}>{di+1}</span>:null;}
 if(id==='twobots'){const bot=s.positions.indexOf(at),goal=d.target.indexOf(at);node=<>{goal>=0&&<span className={`goal-marker bot-${goal}`}>☆<small>{goal+1}</small></span>}{bot>=0&&<span className={`robot-token bot-${bot}`}>{bot+1}</span>}</>;}
 if(id==='programbot')node=<>{at===d.target.pos&&<span className="goal-marker">☆<small>{ARROWS[d.target.dir]}</small></span>}{at===s.pos&&<span className="robot-token">{ARROWS[s.dir]}</span>}</>;
 return markCell(node,at);});return <div className="trial-board"><MiniGrid n={d.n} values={values} blocked={d.walls} onCell={id==='programbot'?undefined:(at)=>{const origin=id==='twobots'?s.positions[0]:s.pos;const dir=range(4).find(dir=>directed(origin,dir,d.n)===at);if(dir!==undefined)onMove(dir);}}/>{id==='keydoors'&&<div className="key-ring">{d.keys.map((_:any,i:number)=><span key={i} className={s.keys&(1<<i)?'collected':''}>⚿ {i+1}</span>)}</div>}{id==='programbot'?<><p className="program-goal">☆で <strong>{ARROWS[d.target.dir]}</strong> を むいて とまろう</p><div className="program-strip">{shownProgram.length?shownProgram.map((cmd,i)=><span key={i} {...feedbackTargetProps(feedback,'command',i,noticeId)}><FeedbackMarker feedback={feedback} type="command" index={i}/>{cmd==='L'?'↶':cmd==='R'?'↷':cmd==='F'?'↑':`↑×${cmd[1]}`}</span>):<small>ここに めいれいを ならべよう</small>}</div>{badge(`${shownProgram.length} / ${d.budget} めいれい`)}<div className="control-row">{d.allowed.map((cmd:string)=><button key={cmd} type="button" disabled={program.length>=d.budget} onClick={()=>{onProgramEdit?.();setProgram(a=>[...a,cmd]);}}>{cmd==='L'?'↶':cmd==='R'?'↷':cmd==='F'?'↑':`↑×${cmd[1]}`}</button>)}<button type="button" disabled={!program.length} onClick={()=>{onProgramEdit?.();setProgram(a=>a.slice(0,-1));}}>⌫</button></div><button type="button" className="primary-action" disabled={!program.length} onClick={()=>onProgram(program)}>▶ うごかす</button></>:<DPad onMove={onMove}/>}</div>;}
 if(id==='hanoi')return <><div className="hanoi-pegs">{range(3).map(peg=><button type="button" key={peg} className={selected===peg?'selected':''} onClick={()=>{if(selected===null)setSelected(peg);else if(selected===peg)setSelected(null);else move({from:selected,to:peg});}} aria-label={`${peg+1}ばんの ぼう`}><div className="peg-rings">{range(d.n).filter(i=>s[i]===peg).map(disk=><span key={disk} style={{width:`${35+disk*60/Math.max(1,d.n-1)}%`,background:COLORS[disk]}}>{disk+1}</span>)}</div><b>{peg===(d.goalPeg??2)?'★':peg+1}</b></button>)}</div><small>もとの ぼう → いきさきの ぼう</small></>;
 if(id==='river'||id==='bridge')return <>{id==='river'?<><div className="conflict-pairs">{d.conflicts.map(([a,b]:number[],i:number)=><span key={i} {...feedbackTargetProps(feedback,'constraint',i,noticeId)}>{String.fromCharCode(65+a)} ⚡ {String.fromCharCode(65+b)}</span>)}</div>{badge(`ふねは ${d.capacity}にんまで`)}</>:badge(`ごうけい ${s.time} / ${d.budget}ふん`)}<div className="river-banks">{[0,1].map(bank=><div className={`river-bank ${s.boat===bank?'has-boat':''}`} key={bank}><small>{bank?'むこうぎし':'こちらぎし'} {s.boat===bank?(id==='bridge'?'☀':'⛵'):''}</small>{range(d.n).filter(i=>s.banks[i]===bank).map(i=><button type="button" key={i} {...feedbackTargetProps(feedback,'piece',i,noticeId)} disabled={s.boat!==bank} className={riders.includes(i)?'selected':''} onClick={()=>choose(i)}><span style={{background:COLORS[i]}}>{String.fromCharCode(65+i)}</span>{id==='bridge'&&<b>{d.times[i]}ふん</b>}</button>)}</div>)}</div><button type="button" className="primary-action" onClick={()=>{onMove({riders});setRiders([]);}}>{s.boat?'← もどる':'わたる →'}</button></>;
 if(id==='jugs')return <><div className="jug-goals">おだい：{d.target.map((v:number,i:number)=><span key={i}>{String.fromCharCode(65+i)}＝{v}</span>)}</div><div className="jugs">{d.caps.map((cap:number,i:number)=><div key={i} {...feedbackTargetProps(feedback,'piece',i,noticeId)}><button type="button" className={`jug ${selected===i?'selected':''}`} onClick={()=>{if(selected===null)setSelected(i);else if(selected===i)setSelected(null);else move({type:'pour',from:selected,to:i});}} aria-label={`${String.fromCharCode(65+i)}の みず ${s[i]} / ${cap}`}><span className="water" style={{height:`${s[i]/cap*100}%`}}/><b>{s[i]}<small> / {cap}</small></b></button><strong>{String.fromCharCode(65+i)}</strong><button type="button" onClick={()=>move({type:'fill',from:i})}>みたす</button><button type="button" onClick={()=>move({type:'empty',from:i})}>からに</button></div>)}</div><small>{selected===null?'コップを ふたつ えらぶと そそぐよ':'つぎに そそぐ あいてを えらぼう'}</small></>;
 if(id==='pegs')return <><MiniGrid n={d.n} selected={selected===null?[]:[selected]} values={range(d.n*d.n).map(i=>markCell(s.includes(i)?<span className="peg-dot"/>:'·',i))} onCell={i=>{if(s.includes(i))setSelected(i===selected?null:i);else if(selected!==null)move({from:selected,to:i});}}/>{badge(`のこり ${s.length}こ`)}</>;
 if(id==='frogs')return <><div className="frog-row">{s.map((v:number,i:number)=><button key={i} type="button" {...feedbackTargetProps(feedback,'cell',i,noticeId)} onClick={()=>onMove(i)} disabled={!v} className={v===1?'frog-a':v===-1?'frog-b':'frog-gap'} aria-label={`${i+1}ばん ${v===1?'みぎへ':v===-1?'ひだりへ':'あき'}`}>{v===1?'→':v===-1?'←':'·'}</button>)}</div><small>ゴール：{d.target.map((v:number)=>v===1?'→':v===-1?'←':'・').join(' ')}</small></>;
 if(id==='pancake')return <div className="pancake-stack">{s.map((v:number,i:number)=><button key={i} type="button" disabled={i===0} onClick={()=>onMove(i+1)}><span style={{width:`${32+v/d.n*60}%`,background:COLORS[(v-1)%6]}}>{v}</span>{i>0&&<small>ここまで ↶</small>}</button>)}</div>;
 if(id==='traffic')return <><div className="traffic-board" style={{aspectRatio:'1'}}>{range(d.n*d.n).map(i=><i key={i} style={{left:`${i%d.n/d.n*100}%`,top:`${Math.floor(i/d.n)/d.n*100}%`,width:`${100/d.n}%`,height:`${100/d.n}%`}}/>)}{d.cars.map((car:any,i:number)=><button type="button" key={i} {...feedbackTargetProps(feedback,'piece',i,noticeId)} className={`car ${selected===i?'selected':''} ${i===0?'target-car':''}`} style={{left:`${(car.axis==='h'?s[i]:car.lane)/d.n*100}%`,top:`${(car.axis==='h'?car.lane:s[i])/d.n*100}%`,width:`${(car.axis==='h'?car.len:1)/d.n*100}%`,height:`${(car.axis==='v'?car.len:1)/d.n*100}%`,background:COLORS[i%6],...feedbackTargetProps(feedback,'piece',i,noticeId).style}} onClick={()=>setSelected(i)} aria-label={`${i+1}ばんの くるま`}>{i+1} <small>{car.axis==='h'?'↔':'↕'}</small></button>)}<span className="traffic-exit" style={{top:`${d.cars[0].lane/d.n*100}%`,height:`${100/d.n}%`}}>→</span></div>{selected!==null?<DPad horizontal={d.cars[selected].axis==='h'} vertical={d.cars[selected].axis==='v'} onMove={dir=>onMove({car:selected,delta:dir===0||dir===3?-1:1})}/>:<small>うごかす くるまを タッチ</small>}</>;
 if(id==='colorsort')return <><div className="bottle-rack">{s.map((b:number[],i:number)=><button key={i} type="button" className={`bottle ${selected===i?'selected':''}`} onClick={()=>{if(selected===null)setSelected(i);else if(selected===i)setSelected(null);else move({from:selected,to:i});}} aria-label={`${i+1}ばんの ボトル`}><div className="bottle-balls" style={{minHeight:d.capacity*32+10}}>{[...b].reverse().map((v,j)=><span key={j} style={{background:COLORS[v]}}>{v+1}</span>)}</div><small>{i+1}</small></button>)}</div><small>いちばん うえを ひとつ うつそう</small></>;
 if(id==='trainyard'){const source=(from:any)=>{setSelected(selected===from?null:from);};return <><div className="train-input"><small>いりぐち　せんとう ↓</small><button type="button" className={selected==='in'?'selected':''} disabled={!s.input.length} onClick={()=>source('in')}>{s.input.length?s.input.map((v:number,i:number)=><span key={i}>{v}</span>):'からっぽ'}</button></div><div className="train-sidings">{s.sidings.map((cars:number[],i:number)=><button type="button" key={i} className={selected===i?'selected':''} onClick={()=>{if(selected===null||selected===i)source(i);else move({from:selected,to:i});}}><small>たいひ {i+1}　{cars.length}/{d.capacity}</small><b>でぐち ↑</b>{[...cars].reverse().map((v,j)=><span key={j}>{v}</span>)}</button>)}</div><button type="button" className="train-output" disabled={selected===null} onClick={()=>move({from:selected,to:'out'})}><small>しゅっぱつ　つぎは {s.output.length+1<=d.n?s.output.length+1:'✓'}</small><div>{s.output.map((v:number,i:number)=><span key={i}>{v}</span>)}</div></button></>;}
 if(id==='matchsticks'){let count=0;const parts=d.groups.map((len:number,g:number)=>{const out=<React.Fragment key={g}>{range(len).map(i=>{const at=count+i;return <button type="button" key={at} className={digit===at?'selected':''} onClick={()=>setDigit(at)} aria-label={`${at+1}ばんの すうじ`}><Digit mask={s.masks[at]}/></button>;})}{g<2&&<b>{g===0?'＋':'＝'}</b>}</React.Fragment>;count+=len;return out;});return <>{badge(`${s.used} / ${d.maxMoves}て いない`)}<div className="match-equation">{parts}</div><div className="match-zoom"><small>{digit+1}ばんの すうじ</small><Digit mask={s.masks[digit]} selected={selected!==null&&Math.floor(selected/7)===digit?selected%7:-1} onSegment={segment=>{const at=digit*7+segment,lit=!!(s.masks[digit]&(1<<(6-segment)));if(lit)setSelected(selected===at?null:at);else if(selected!==null)move({from:selected,to:at});}}/></div><small>{selected===null?'うつす マッチを えらぼう':'あいている ばしょへ。べつの すうじも えらべるよ。'}</small></>;}
 if(id==='ballweigh')return <>{badge(`はかる：${s.observations.length} / ${d.budget}かい`)}<div className="weigh-pans"><div><small>ひだり</small>{pans.map((v,i)=>v===1?<span key={i}>{i+1}</span>:null)}</div><b>⚖</b><div><small>みぎ</small>{pans.map((v,i)=>v===2?<span key={i}>{i+1}</span>:null)}</div></div><div className="ball-rack">{range(d.n).map(i=><button type="button" key={i} className={`${pans[i]?'on-pan':''} ${hint&&s.candidates.includes(i)?'possible':''}`} {...feedbackTargetProps(feedback,'card',i,noticeId)} onClick={()=>{if(guessMode)onMove({guess:i});else setPans(a=>a.map((v,j)=>i===j?(v+1)%3:v));}}>{i+1}<small>{guessMode?'これ！':['のせない','ひだり','みぎ'][pans[i]]}</small></button>)}</div><div className="control-row"><button type="button" className="primary-action" onClick={()=>{onMove({left:range(d.n).filter(i=>pans[i]===1),right:range(d.n).filter(i=>pans[i]===2)});setPans(range(d.n).map(()=>0));setGuessMode(false);}}>はかる</button><button type="button" className={guessMode?'selected':''} onClick={()=>setGuessMode(v=>!v)}>こたえを えらぶ</button></div><div className="weigh-history">{s.observations.map((o:any,i:number)=><div key={i} {...feedbackTargetProps(feedback,'observation',i,noticeId)}>{o.left.map((v:number)=>v+1).join('・')} <b>{o.result===0?'＝':o.result<0?'＜':'＞'}</b> {o.right.map((v:number)=>v+1).join('・')}<small>{o.result===0?'おなじ':o.result<0?'ひだりが かるい':'みぎが かるい'}</small></div>)}</div></>;
 if(id==='codebreak')return <><small>{d.repeats?'おなじ しるしも つかうよ':'おなじ しるしは 1かいだけ'}</small><div className="code-slots">{guess.map((v,i)=><button type="button" key={i} className={slot===i?'selected':''} onClick={()=>setSlot(i)} aria-label={`${i+1}ばんの しるし`}><SymbolCard s={{shape:v%3,color:Math.floor(v/3),count:1}}/></button>)}</div><div className="code-palette">{range(d.alphabet).map(v=><button type="button" key={v} onClick={()=>{setGuess(a=>a.map((old,i)=>i===slot?v:old));setSlot(i=>(i+1)%d.length);}} aria-label={`しるし ${v+1}`}><SymbolCard s={{shape:v%3,color:Math.floor(v/3),count:1}}/></button>)}</div><button type="button" className="primary-action" onClick={()=>onMove([...guess])}>しらべる</button><div className="code-history">{[...s.history].reverse().map((row:any,i:number)=><div key={i}><span>{s.history.length-i}</span>{row.guess.map((v:number,j:number)=><SymbolCard key={j} s={{shape:v%3,color:Math.floor(v/3),count:1}}/>)}<b>◎{row.exact}　△{row.near}</b></div>)}</div><small>◎＝しるしも ばしょも　△＝しるしだけ</small></>;
 if(id==='flood')return <>{badge(`${s.used} / ${d.budget}て いない`)}<MiniGrid n={d.n} values={d.regions.map((region:number,i:number)=>{const owned=!!(s.mask&(1<<region)),color=owned?s.color:d.colors[region];return <span className={`flood-cell ${owned?'owned':''}`} style={{background:COLORS[color]}}>{i===0?'★':color+1}</span>;})}/><div className="control-row flood-palette">{range(d.palette).map(v=><button type="button" key={v} disabled={v===s.color} style={{background:COLORS[v]}} onClick={()=>onMove(v)}>{v+1}</button>)}</div></>;
 return null;
}
