/** Semantic difficulty for offline stage selection. Scores are comparable within one game and curriculum theme. */
import{range,key,equal,normalize,rotate,perimeter,type Puzzle}from'../../../lib/engine/shared.ts';
import{cross,pointInside,hullIndices,beamTrace,tileEdges}from'../../../lib/engine/plane.ts';
export const PLANE_GOALS:Record<string,[string,string,string,string,string]>={
 rotate:['でっぱりを 90ど まわす','はんかいてんを みわける','かがみの にせものを みわける','あなの いちも まわす','くぼみと あなの かんけいを たもつ'],
 mirror:['ひだりと みぎを いれかえる','まわした かたちと みくらべる','こまかい でっぱりを うつす','あなも かがみに うつす','あなと くぼみを いっしょに うつす'],
 fit:['ふたつの かたまりを あわせる','いりくんだ ピースを あわせる','かさなる マスを 1つに する','かさなっても あなは のこす','あなと くぼみの かたちを たしかめる'],
 square:['たてよこの せいほうけいを みつける','ななめの せいほうけいを みつける','ちかい にせものの てんを よける','へんの ながさと かどを たしかめる','たくさんの てんから 4つを きめる'],
 symmetry:['たての せんで おりかえす','よこの せんで おりかえす','ななめの せんで おりかえす','はんたいの ななめで おりかえす','せんの むきを みて おりかえす'],
 area:['たてと よこの まとまりで かぞえる','かけた マスを ひく','しかくに わけて ひろさを たす','あなの ひろさを ひく','あなと へこみを いっしょに ひく'],
 perimeter:['そとの へんを たどる','へこみの へんも かぞえる','あなの まわりも かぞえる','ふたつの あなの まわりを かぞえる','そとと なかの まわりを わけて たす'],
 tiling:['まっすぐな へんを あわせる','まわして かどを あわせる','おおきさの ちがう ピースを しきつめる','くぼみに はまる ピースを さがす','のこりの すきまから おきかたを きめる'],
 equalparts:['にわ 1つの マスすうを きめる','3つの にわを つなげて わける','となりあう いえの にわを わける','ほそい つながりを のこして わける','5つの にわの ひろさと つながりを そろえる'],
 translate:['1つの むきに ずらす','たてと よこを くみあわせる','はんたいの やじるしを うちけす','まがる じゅんばんを たどる','はなれた やじるしも うちけして まとめる'],
 foldpunch:['1かい おった かみを ひらく','たてよこに おった かみを ひらく','おなじ むきの 2つの おりめを もどす','くりかえす おりめを じゅんに もどす','4つの おりめと あなを くみあわせる'],
 angles:['90どから のこりを もとめる','180どから のこりを もとめる','2つの かくどを たして ひく','1しゅう 360どから もとめる','いくつもの かくどを まとめて ひく'],
 circlecenter:['むかいあう 2てんの まんなかを みる','3てんめまでの きょりも みる','むかいあわない 3てんから さがす','ちかい こたえを きょりで くらべる','かたよりの ある 3てんでも まんなかを さがす'],
 triangulate:['1つの かどから さんかくを つくる','きんしせんを よけて わける','1つの かどだけに たよらず わける','ひける せんが すくない かどから きめる','のこりの へやも さんかくに できるか よむ'],
 pairroutes:['ペアを つなぎ ぜんぶの マスを つかう','とおまわりで あきマスを なくす','ほかの ペアの みちを のこす','まんなかの ペアの でぐちを つくる','ながい とおまわりを くみあわせる'],
 mapcolor:['となりあう ちいきを べついろに する','3いろで ぬりわける','3つが たがいに となりあう ところを みる','となりの となりまで いろを つなぐ','3いろの くみあわせを ぜんたいで そろえる'],
 inside:['かこいの うちと そとを みわける','Lじの へこみを みわける','Uじの へこみを みわける','いくつもの へこみを たどる','ななめの へんの うちと そとを みわける'],
 jigsaw:['0を そとへ むけて へんを あわせる','まわして ＋と−を あわせる','まんなかの ピースも あわせる','おなじ すうじの にせものを みわける','4つの へんを いっしょに たしかめる'],
 mirrorbeam:['1つの かがみで みちを かえる','2つの かがみを つなげる','とちゅうの まがりかたを くみあわせる','でぐちからも みちを たどる','5ついじょうの かがみを くみあわせる'],
 scale:['たても よこも 2ばいに する','へこみの はばも 2ばいに する','3ばいの はばと たかさを たしかめる','あなの ひろがりかたを たしかめる','あなと そとがわを いっしょに 3ばいに する'],
 separator:['たてか よこの せんで わける','ななめの せんで わける','たてよこが かさなる 2ぐみを わける','せまい すきまを とおす','ぜんぶの てんを みて せんの かたむきを きめる'],
 hull:['いちばん そとの 4つの かどを さがす','ななめの へんも はって かこむ','へんの とちゅうの てんを よける','へんに ちかい なかの てんを よける','へんの とちゅうと なかの てんを みわける'],
 parallel:['たてと よこの せんを みわける','ななめの おなじ むきを さがす','たてよこの すすみかたを くらべる','にている かたむきを みわける','すこしだけ ちがう かたむきを たしかめる'],
 coinparking:['かさならない 2つを えらぶ','1つ おいた あとの のこりを みる','となりあう こうほの くさりを ほどく','わの こうほを じゅんに えらぶ','1つの えらびかたが ぜんたいに およぶのを よむ'],
};
const sum=(a:number[])=>a.reduce((s,v)=>s+v,0),countBits=(n:number)=>{let c=0;while(n){n&=n-1;c++;}return c;},difference=(a:number[][],b:number[][])=>{const aa=new Set(a.map(key)),bb=new Set(b.map(key));return [...aa].filter(k=>!bb.has(k)).length+[...bb].filter(k=>!aa.has(k)).length;};
function geometry(cells:number[][]){if(!cells?.length)return{cells:0,concave:0,holes:0,perimeter:0,components:0};const set=new Set(cells.map(key)),maxX=Math.max(...cells.map(v=>v[0]))+1,maxY=Math.max(...cells.map(v=>v[1]))+1;let concave=0;for(let x=0;x<=maxX;x++)for(let y=0;y<=maxY;y++)if([[x,y],[x-1,y],[x,y-1],[x-1,y-1]].filter(p=>set.has(key(p))).length===3)concave++;const componentCount=(source:number[][])=>{const remaining=new Set(source.map(key));let components=0;while(remaining.size){components++;const q=[JSON.parse(remaining.values().next().value!)];remaining.delete(key(q[0]));for(let i=0;i<q.length;i++)for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const p=[q[i][0]+dx,q[i][1]+dy];if(remaining.delete(key(p)))q.push(p);}}return components;},air=range((maxX+2)*(maxY+2)).map(i=>[i%(maxX+2)-1,Math.floor(i/(maxX+2))-1]).filter(p=>!set.has(key(p)));return{cells:cells.length,concave,holes:componentCount(air)-1,perimeter:perimeter(cells),components:componentCount(cells)};}
const lineDistance=(p:number[],a:number[],b:number[])=>Math.abs(cross(a,b,p))/Math.hypot(b[0]-a[0],b[1]-a[1]);
function triangulationCount(n:number,banned:number[][]){const ban=new Set(banned.map(key)),memo=new Map<string,number>();function go(a:number,b:number):number{if(b-a<2)return 1;const k=a+','+b;if(memo.has(k))return memo.get(k)!;let total=0;for(let j=a+1;j<b;j++)if(!(j-a>1&&ban.has(key([a,j])))&&!(b-j>1&&ban.has(key([j,b]))))total+=go(a,j)*go(j,b);memo.set(k,total);return total;}return go(0,n-1);}
function parkingStats(d:any){const masks=d.points.map((p:number[],i:number)=>d.points.reduce((m:number,q:number[],j:number)=>i!==j&&(p[0]-q[0])**2+(p[1]-q[1])**2<4*d.radius**2?m|(1<<j):m,0)),valid=new Uint8Array(1<<d.points.length),sizes=new Uint8Array(valid.length);valid[0]=1;let solutions=0,maximum=0,triangles=0;for(let m=1;m<valid.length;m++){const bit=m&-m,i=31-Math.clz32(bit),rest=m^bit;if(valid[rest]&&!(masks[i]&rest)){valid[m]=1;sizes[m]=sizes[rest]+1;maximum=Math.max(maximum,sizes[m]);if(sizes[m]===d.k)solutions++;}}for(let i=0;i<masks.length;i++)for(let j=i+1;j<masks.length;j++)for(let k=j+1;k<masks.length;k++)if(masks[i]&(1<<j)&&masks[i]&(1<<k)&&masks[j]&(1<<k))triangles++;return{solutions,maximum,triangles,conflicts:sum(masks.map(countBits))/2,isolated:masks.filter((v:number)=>!v).length};}
function minimumPlacementCost(options:{mask:number;cost:number}[][],limit=200000){let best=Infinity,nodes=0,capped=false;const memo=new Map<string,number>();function visit(used:number,left:number,cost:number){if(cost>=best)return;if(++nodes>limit){capped=true;return;}if(!left){best=cost;return;}const signature=used+'/'+left,old=memo.get(signature);if(old!==undefined&&old<=cost)return;memo.set(signature,cost);let selected=-1,valid:{mask:number;cost:number}[]=[];for(let i=0;i<options.length;i++)if(left&(1<<i)){const next=options[i].filter(p=>!(p.mask&used));if(!next.length)return;if(selected<0||next.length<valid.length){selected=i;valid=next;}}for(const p of [...valid].sort((a,b)=>a.cost-b.cost))visit(used|p.mask,left^(1<<selected),cost+p.cost);}visit(0,(1<<options.length)-1,0);return{minimum:best,nodes,capped};}
function tileDifficulty(d:any){const options=d.pieces.map((piece:number[][])=>{const forms=[...new Map(range(4).map(q=>{const v=rotate(piece,q);return[key(v),v] as const;})).values()],out:{mask:number;cost:number}[]=[];for(const v of forms){const w=Math.max(...v.map(p=>p[0]))+1,h=Math.max(...v.map(p=>p[1]))+1;for(let y=0;y<=d.rows-h;y++)for(let x=0;x<=d.n-w;x++)out.push({mask:v.reduce((m,[a,b])=>m|(1<<((y+b)*d.n+x+a)),0),cost:equal(v,piece)?0:1});}return out;}),result=minimumPlacementCost(options);return{minimumRotations:result.capped||!Number.isFinite(result.minimum)?0:result.minimum,rotationProofExact:!result.capped,rotationSearchNodes:result.nodes};}
function rectangleDistrictsPossible(d:any){const area=d.n*d.rows/d.k,options=d.homes.map((home:number)=>{const out:{mask:number;cost:number}[]=[];for(let w=1;w<=d.n;w++){if(area%w)continue;const h=area/w;if(h>d.rows)continue;for(let y=0;y<=d.rows-h;y++)for(let x=0;x<=d.n-w;x++){const covers=(at:number)=>at%d.n>=x&&at%d.n<x+w&&Math.floor(at/d.n)>=y&&Math.floor(at/d.n)<y+h;if(!covers(home)||d.homes.some((v:number)=>v!==home&&covers(v)))continue;out.push({mask:range(w*h).reduce((m,i)=>m|(1<<((y+Math.floor(i/w))*d.n+x+i%w)),0),cost:0});}}return out;});return Number.isFinite(minimumPlacementCost(options).minimum);}
export function planeMetrics(p:Puzzle):{score:number;features:Record<string,number|string|boolean>}{
 const d=p.data,id=p.id,f:Record<string,number|string|boolean>={concept:d.concept??Math.floor((p.level-1)/4)};let score=0;
 if(['rotate','mirror','fit','area'].includes(id)){const g=geometry(d.shape);Object.assign(f,g);const mirrored=normalize(d.shape.map(([x,y]:number[])=>[-x,y]));f.mirrorInvariant=equal(mirrored,normalize(d.shape));if(id==='area'){const box=(Math.max(...d.shape.map((v:number[])=>v[0]))+1)*(Math.max(...d.shape.map((v:number[])=>v[1]))+1);f.missingFromRectangle=box-g.cells;score=.25*g.cells+2*g.concave+5*g.holes;}
  else{const correct=p.options![p.solution],wrong=p.options!.filter((_,i)=>i!==p.solution),near=Math.min(...wrong.map(a=>difference(a,correct)));f.closestDistractorEdits=near;f.equalAreaDistractors=wrong.filter(a=>a.length===correct.length).length;score=.2*g.cells+g.concave+2*g.holes+6/(1+near);if(id==='rotate'){f.minimumQuarterTurns=Math.min(...range(4).filter(q=>equal(rotate(d.shape,q),correct)).map(q=>Math.min(q,4-q)));f.reflectionDistractor=wrong.some(a=>equal(normalize(a),mirrored));score+=2*Number(f.minimumQuarterTurns)+3*Number(f.reflectionDistractor);}if(id==='mirror'){f.mirrorChange=difference(d.shape,mirrored);f.identityAnswer=equal(normalize(d.shape),correct);score+=2*Number(!f.identityAnswer)+.25*Number(f.mirrorChange);}if(id==='fit'){const overlap=d.parts[0].filter((v:number[])=>d.parts[1].some((a:number[])=>equal(a,v))).length;f.overlap=overlap;f.partComponents=sum(d.parts.map((v:number[][])=>geometry(v).components));score+=overlap+Number(f.partComponents);}}}
 else if(id==='square'){const pts=p.solution.map((at:number)=>[at%d.n,Math.floor(at/d.n)]),a=pts[0],b=pts[1];f.tilted=a[0]!==b[0]&&a[1]!==b[1];f.sideSquared=(a[0]-b[0])**2+(a[1]-b[1])**2;f.distractorPoints=d.dots.length-4;f.nearVertexDecoys=d.dots.filter((i:number)=>!p.solution.includes(i)&&p.solution.some((j:number)=>Math.abs(i%d.n-j%d.n)+Math.abs(Math.floor(i/d.n)-Math.floor(j/d.n))===1)).length;score=2*Number(f.tilted)+Number(f.distractorPoints)+2*Number(f.nearVertexDecoys);}
 else if(id==='symmetry'){const coords=(d.sourceIndices??range(d.left.length).map(i=>Math.floor(i/(d.n/2))*d.n+i%(d.n/2))).flatMap((at:number,i:number)=>d.left[i]?[[at%d.n,Math.floor(at/d.n)]]:[]),g=geometry(coords);Object.assign(f,g);f.axis=d.axis??'vertical';f.editableCells=p.solution.length;f.axisDistance=sum(coords.map(([x,y]:number[])=>f.axis==='vertical'?Math.abs(d.n/2-.5-x):f.axis==='horizontal'?Math.abs(d.n/2-.5-y):f.axis==='diagonal'?Math.abs(x-y)/Math.SQRT2:Math.abs(x+y-d.n+1)/Math.SQRT2));score=.35*g.cells+g.components+.15*g.perimeter+.1*Number(f.axisDistance);}
 else if(id==='perimeter'){const g=geometry(d.cells);Object.assign(f,g);f.sharedEdges=(4*g.cells-g.perimeter)/2;score=.25*g.perimeter+2*g.concave+5*g.holes;}
 else if(id==='tiling'){f.pieces=d.pieces.length;f.boardCells=d.n*d.rows;f.pieceConcavity=sum(d.pieces.map((a:number[][])=>geometry(a).concave));f.distinctShapes=new Set(d.pieces.map((a:number[][])=>range(4).map(q=>key(rotate(a,q))).sort()[0])).size;f.placementOptions=sum(d.pieces.map((a:number[][])=>{const forms=[...new Map(range(4).map(q=>{const v=rotate(a,q);return[key(v),v] as const;})).values()];return sum(forms.map(v=>(d.n-Math.max(...v.map(p=>p[0])))*(d.rows-Math.max(...v.map(p=>p[1])))).map(v=>Math.max(0,v)));}));Object.assign(f,tileDifficulty(d));score=Number(f.pieceConcavity)+2*Number(f.distinctShapes)+2*Number(f.minimumRotations)+.08*Number(f.placementOptions);}
 else if(id==='equalparts'){f.regions=d.k;f.regionArea=d.n*d.rows/d.k;f.adjacentHomes=d.homes.reduce((s:number,a:number,i:number)=>s+d.homes.slice(i+1).filter((b:number)=>Math.abs(a%d.n-b%d.n)+Math.abs(Math.floor(a/d.n)-Math.floor(b/d.n))===1).length,0);f.interiorHomes=d.homes.filter((i:number)=>i%d.n>0&&i%d.n<d.n-1&&i>=d.n&&i<d.n*(d.rows-1)).length;f.rectanglePartitionPossible=rectangleDistrictsPossible(d);score=2*Number(f.adjacentHomes)+Number(f.interiorHomes)+8*Number(!f.rectanglePartitionPossible)+Number(f.regionArea);}
 else if(id==='translate'){f.moves=d.moves.length;f.netDistance=Math.abs(d.pos[0]-d.start[0])+Math.abs(d.pos[1]-d.start[1]);f.canceledSteps=d.moves.length-Number(f.netDistance);f.axes=new Set(d.moves.map((v:number)=>v%2)).size;f.turns=d.moves.slice(1).filter((v:number,i:number)=>v%2!==d.moves[i]%2).length;f.noOp=Number(f.netDistance)===0;score=d.moves.length+2*Number(f.axes)+Number(f.turns)+.3*Number(f.canceledSteps)-5*Number(f.noOp);}
 else if(id==='foldpunch'){f.folds=d.folds.length;f.axes=new Set(d.folds).size;f.punches=d.holes.length;f.answerCells=p.solution.filter(Boolean).length;f.repeatedAxes=d.folds.length-Number(f.axes);f.punchSpread=d.holes.length>1?Math.max(...d.holes.map((a:number)=>Math.max(...d.holes.map((b:number)=>Math.abs(a%d.w-b%d.w)+Math.abs(Math.floor(a/d.w)-Math.floor(b/d.w)))))):0;f.foldDistance=sum(d.holes.map((i:number)=>d.w-1-i%d.w+d.h-1-Math.floor(i/d.w)))/d.holes.length;score=4*Number(f.folds)+2*Number(f.axes)+2*Number(f.punches)+Number(f.repeatedAxes)+.2*Number(f.punchSpread)+.1*Number(f.foldDistance);}
 else if(id==='angles'){f.total=d.total;f.given=d.parts.length-1;f.nonRightGiven=d.parts.filter((v:number,i:number)=>i!==d.missing&&v%90!==0).length;f.nonThirtyGiven=d.parts.filter((v:number,i:number)=>i!==d.missing&&v%30!==0).length;f.givenSum=d.total-d.parts[d.missing];score=3*Number(f.given)+Number(f.nonRightGiven)+Number(f.nonThirtyGiven)+.01*Number(f.givenSum);}
 else if(id==='circlecenter'){const errors=d.candidates.map((a:number[])=>{const ds=d.points.map((p:number[])=>(p[0]-a[0])**2+(p[1]-a[1])**2);return Math.max(...ds)-Math.min(...ds);}),center=d.candidates[errors.indexOf(0)],radius=(d.points[0][0]-center[0])**2+(d.points[0][1]-center[1])**2,ds=d.points.map((a:number[],i:number)=>{const b=d.points[(i+1)%3];return(a[0]-b[0])**2+(a[1]-b[1])**2;});f.radiusSquared=radius;f.diametricPair=ds.includes(4*radius);f.scalene=new Set(ds).size===3;f.closestDecoyRelativeError=Math.min(...errors.filter((v:number)=>v>0))/radius;score=4*Number(!f.diametricPair)+2*Number(f.scalene)+5/(.2+Number(f.closestDecoyRelativeError));}
 else if(id==='triangulate'){f.vertices=d.n;f.requiredDiagonals=d.n-3;f.banned=d.banned.length;f.validTriangulations=triangulationCount(d.n,d.banned);f.unrestrictedTriangulations=triangulationCount(d.n,[]);score=Number(f.requiredDiagonals)+Math.log2((Number(f.unrestrictedTriangulations)+1)/(Number(f.validTriangulations)+1))+d.banned.length*.3;}
 else if(id==='pairroutes'){f.pairs=d.pairs.length;f.endpointDistance=sum(d.pairs.map(([a,b]:number[])=>Math.abs(a%d.n-b%d.n)+Math.abs(Math.floor(a/d.n)-Math.floor(b/d.n))));f.requiredDetourSteps=d.n*d.n-d.pairs.length-Number(f.endpointDistance);f.interiorEndpoints=d.pairs.flat().filter((i:number)=>i%d.n>0&&i%d.n<d.n-1&&i>=d.n&&i<d.n*(d.n-1)).length;f.adjacentPairs=d.pairs.filter(([a,b]:number[])=>Math.abs(a%d.n-b%d.n)+Math.abs(Math.floor(a/d.n)-Math.floor(b/d.n))===1).length;score=2*Number(f.requiredDetourSteps)+Number(f.interiorEndpoints)+Number(f.adjacentPairs);}
 else if(id==='mapcolor'){f.colors=d.colors;f.regions=d.k;f.blanks=d.initial.filter((v:number)=>v<0).length;f.edges=d.edges.length;let triangles=0;for(let a=0;a<d.k;a++)for(let b=a+1;b<d.k;b++)for(let c=b+1;c<d.k;c++)if([[a,b],[a,c],[b,c]].every(e=>d.edges.some((v:number[])=>equal(v,e))))triangles++;f.triangles=triangles;f.maximumDegree=Math.max(...range(d.k).map(i=>d.edges.filter((e:number[])=>e.includes(i)).length));score=Number(f.blanks)+Number(f.maximumDegree)+3*triangles+2*(4-d.colors);}
 else if(id==='inside'){const hull=hullIndices(d.poly).map(i=>d.poly[i]);f.vertices=d.poly.length;f.points=d.points.length;f.notchDecoys=d.points.filter((v:number[])=>!pointInside(v,d.poly)&&pointInside(v,hull)).length;f.slantedEdges=d.poly.filter((v:number[],i:number)=>{const b=d.poly[(i+1)%d.poly.length];return v[0]!==b[0]&&v[1]!==b[1];}).length;f.nearEdges=d.points.filter((p:number[])=>Math.min(...d.poly.map((a:number[],i:number)=>{const b=d.poly[(i+1)%d.poly.length],vx=b[0]-a[0],vy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*vx+(p[1]-a[1])*vy)/(vx*vx+vy*vy)));return Math.hypot(p[0]-a[0]-t*vx,p[1]-a[1]-t*vy);}))<.6).length;score=2*Number(f.notchDecoys)+Number(f.slantedEdges)+Number(f.nearEdges)+.2*d.points.length;}
 else if(id==='jigsaw'){f.pieces=d.tiles.length;f.edgePairs=2*d.n*(d.n-1);f.labels=new Set(d.tiles.flat().map(Math.abs).filter(Boolean)).size;f.repeatedLabels=Number(f.edgePairs)-Number(f.labels);f.signReversals=d.tiles.reduce((s:number,t:number[])=>s+t.filter(v=>v<0).length,0);const opts=range(d.n*d.n).map(at=>d.tiles.flatMap((t:number[],tile:number)=>range(4).map(q=>tileEdges(t,q)).filter(e=>(at<d.n)===(e[0]===0)&&(at%d.n===d.n-1)===(e[1]===0)&&(at>=d.n*(d.n-1))===(e[2]===0)&&(at%d.n===0)===(e[3]===0)).map(edges=>({tile,edges}))));let nodes=0,solved=false;const grid:number[][]=[];function visit(at:number,used:number){if(solved||nodes>=50000)return;nodes++;if(at===d.n*d.n){solved=true;return;}for(const{tile,edges:e}of opts[at])if(!(used&(1<<tile))&&(at<d.n||e[0]+grid[at-d.n][2]===0)&&(at%d.n===0||e[3]+grid[at-1][1]===0)){grid[at]=e;visit(at+1,used|(1<<tile));}}visit(0,0);f.searchNodes=nodes;f.searchCapped=!solved;score=2*Number(f.repeatedLabels)+Math.log2(nodes+1)+d.tiles.length*.2;}
 else if(id==='mirrorbeam'){f.minimumFlips=d.minimum;f.mirrors=d.mirrors.length;let goals=0,minBends=Infinity;for(let m=0;m<2**d.mirrors.length;m++){const trace=beamTrace(d.n,d.mirrors,range(d.mirrors.length).map(i=>(m>>i)&1),d.row);if(equal(trace.exit,d.target)){goals++;minBends=Math.min(minBends,trace.cells.filter(at=>d.mirrors.includes(at)).length);}}f.goalStates=goals;f.minimumGoalBends=minBends;f.goalFraction=goals/(2**d.mirrors.length);score=5*d.minimum+2*minBends+2*(1-Number(f.goalFraction));}
 else if(id==='scale'){const g=geometry(d.cells);Object.assign(f,g);f.factor=d.factor;f.sameAreaDistractors=p.options!.filter((v:any,i:number)=>i!==p.solution&&v.cells.length===p.options![p.solution].cells.length).length;score=g.concave+4*g.holes+2*Number(f.sameAreaDistractors)+d.factor;}
 else if(id==='separator'){let margins:number[]=[];for(let a=0;a<d.anchors.length;a++)for(let b=a+1;b<d.anchors.length;b++){const signs=d.points.map((p:number[])=>Math.sign(cross(d.anchors[a],d.anchors[b],p)));if(signs.every((v:number,i:number)=>v!==0&&v===(d.groups[i]===d.groups[0]?signs[0]:-signs[0])))margins.push(Math.min(...d.points.map((p:number[])=>lineDistance(p,d.anchors[a],d.anchors[b]))));}f.validLines=margins.length;f.bestMargin=Math.max(...margins);f.points=d.points.length;const groups=[0,1].map(g=>d.points.filter((_:number[],i:number)=>d.groups[i]===g));f.axisSeparable=[0,1].some(j=>Math.min(...groups.map(v=>Math.max(...v.map((p:number[])=>p[j]))))<Math.max(...groups.map(v=>Math.min(...v.map((p:number[])=>p[j])))));score=4*Number(!f.axisSeparable)+8/(1+margins.length)+4/(.25+Number(f.bestMargin))+.2*d.points.length;}
 else if(id==='hull'){const hull=p.solution.map((i:number)=>d.points[i]),inside=d.points.filter((_:number[],i:number)=>!p.solution.includes(i)),dist=inside.map((p:number[])=>Math.min(...hull.map((a:number[],i:number)=>lineDistance(p,a,hull[(i+1)%hull.length]))));f.hullVertices=hull.length;f.collinearBoundary=dist.filter((v:number)=>v<1e-8).length;f.nearBoundaryInterior=dist.filter((v:number)=>v>=1e-8&&v<=.8).length;f.interior=inside.length;f.minimumInteriorGap=Math.min(9,...dist.filter((v:number)=>v>1e-8));score=hull.length+3*Number(f.collinearBoundary)+2*Number(f.nearBoundaryInterior)+.4*inside.length+3/(.4+Number(f.minimumInteriorGap));}
 else if(id==='parallel'){const vector=d.vector,wrong=d.cards.map((v:any)=>v.vector).filter((v:number[])=>v[0]*vector[1]!==v[1]*vector[0]),angles=wrong.map((v:number[])=>Math.acos(Math.min(1,Math.abs(v[0]*vector[0]+v[1]*vector[1])/(Math.hypot(...v)*Math.hypot(...vector))))*180/Math.PI);f.cards=d.cards.length;f.targets=p.solution.length;f.closestWrongAngle=Math.min(90,...angles);f.nearAngleDistractors=angles.filter((v:number)=>v<20).length;f.oblique=vector[0]!==0&&vector[1]!==0;score=20/(1+Number(f.closestWrongAngle))+Number(f.nearAngleDistractors)+.2*d.cards.length;}
 else if(id==='coinparking'){Object.assign(f,parkingStats(d));f.target=d.k;f.points=d.points.length;score=Number(f.conflicts)+Number(f.triangles)+4/(1+Number(f.solutions))-Number(f.isolated);}
 else return{score:0,features:{}};
 if(!Number.isFinite(score))throw Error(`Invalid plane score ${id}`);return{score,features:f};
}

/** Canonical tray order and arbitrary edge labels; signs and displayed orientations remain meaningful. */
function canonicalJigsawTiles(tiles:number[][]):number[][]{
 function visit(left:number[],labels:Map<number,number>):number[][]{
  if(!left.length)return[];
  let first:string|undefined;const candidates:{at:number;row:number[];labels:Map<number,number>}[]=[],seen=new Set<string>();
  for(const at of left){const raw=key(tiles[at]);if(seen.has(raw))continue;seen.add(raw);const next=new Map(labels),row=tiles[at].map(v=>{if(!v)return 0;const label=Math.abs(v);if(!next.has(label))next.set(label,next.size+1);return Math.sign(v)*next.get(label)!;}),signature=key(row);
   if(first===undefined||signature.localeCompare(first)<0){first=signature;candidates.length=0;}if(signature===first)candidates.push({at,row,labels:next});
  }
  let best:number[][]|undefined,bestKey:string|undefined;for(const candidate of candidates){const rows=[candidate.row,...visit(left.filter(i=>i!==candidate.at),candidate.labels)],signature=key(rows);if(bestKey===undefined||signature.localeCompare(bestKey)<0){best=rows;bestKey=signature;}}return best!;
 }
 return visit(range(tiles.length),new Map());
}

/** Logical task body for stage dedup; presentation order/labels are intentionally absent. */
export function planeQuestionBody(p:Puzzle):unknown{
 const d=p.data,sort=(a:any[])=>[...a].sort((x,y)=>key(x).localeCompare(key(y))),points=(a:number[][])=>sort(a.map(v=>[...v])),cycle=(a:number[][])=>sort([a,[...a].reverse()].flatMap(v=>range(v.length).map(i=>[...v.slice(i),...v.slice(0,i)])))[0];
 switch(p.id){
 case'rotate':case'mirror':case'area':return{shape:points(d.shape)};
 case'fit':return{parts:sort(d.parts.map(points))};
 case'square':return{n:d.n,dots:sort(d.dots)};
 case'symmetry':return{n:d.n,axis:d.axis??'vertical',source:d.sourceIndices?sort(d.sourceIndices.map((at:number,i:number)=>[at,d.left[i]])):d.left};
 case'perimeter':return{cells:points(d.cells)};
 case'tiling':return{n:d.n,rows:d.rows,pieces:sort(d.pieces.map(points))};
 case'equalparts':return{n:d.n,rows:d.rows,k:d.k,homes:sort(d.homes)};
 case'translate':return{n:d.scene.n,cells:points(d.scene.cells),moves:d.moves};
 case'foldpunch':return{n:d.n,folds:sort(d.folds),w:d.w,h:d.h,holes:sort(d.holes)};
 case'angles':return{total:d.total,given:sort(d.parts.filter((_:number,i:number)=>i!==d.missing))};
 case'circlecenter':{const origin=[0,1].map(i=>Math.min(...d.points.map((v:number[])=>v[i]))),shift=(a:number[][])=>points(a.map(v=>v.map((x,i)=>x-origin[i])));return{points:shift(d.points),candidates:shift(d.candidates)};}
 case'triangulate':return{n:d.n,banned:sort(d.banned.map(sort))};
 case'pairroutes':return{n:d.n,pairs:sort(d.pairs.map(sort))};
 case'mapcolor':{const oldIds=[...new Set(d.regions)] as number[],regions=d.regions.map((v:number)=>oldIds.indexOf(v)),initial=oldIds.map(v=>d.initial[v]),oldColors=[...new Set(initial.filter((v:number)=>v>=0))];return{n:d.n,regions,colors:d.colors,initial:initial.map((v:number)=>v<0?-1:oldColors.indexOf(v))};}
 case'inside':return{poly:cycle(d.poly),points:points(d.points)};
 case'jigsaw':return{n:d.n,tiles:canonicalJigsawTiles(d.tiles)};
 case'mirrorbeam':return{n:d.n,row:d.row,target:d.target,mirrors:sort(d.mirrors.map((at:number,i:number)=>[at,d.initial[i]]))};
 case'scale':return{cells:points(d.cells),factor:d.factor};
 case'separator':return{n:d.n,anchors:points(d.anchors),groups:sort([0,1].map(g=>points(d.points.filter((_:number[],i:number)=>d.groups[i]===g))))};
 case'hull':return{n:d.n,points:points(d.points)};
 case'parallel':{const gcd=(a:number,b:number):number=>b?gcd(b,a%b):a,slope=([x,y]:number[])=>{const divisor=gcd(Math.abs(x),Math.abs(y)),sign=x<0||x===0&&y<0?-1:1;return[x/divisor*sign,y/divisor*sign];};return{reference:slope(d.vector),cards:sort(d.cards.map((c:any)=>slope(c.vector)))};}
 case'coinparking':return{n:d.n,radius:d.radius,k:d.k,points:points(d.points)};
 default:return d;
 }
}
